### ISSUE TITLE
missing i18n translation and correct formatting archive pages year listing 

### ISSUE THREAD

**Issue by rainerrose** [razonyang/hugo-theme-bootstrap#1003]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

Similar to discussion https://github.com/razonyang/hugo-theme-bootstrap/discussions/998, there is a problem with the ` dateFormat parameter`  in the archive listing year

The default english and default dateFormat in the lines with the page title and the month paragraphs are ignored.

The current appearance
~~~
October
2 Beiträge insgesamt
Sonstiges   Oct 30
GIT         Oct 11
~~~

The expected look
~~~
Oktober
2 Beiträge insgesamt
Sonstiges   Okt 30
GIT         Okt 11
~~~

### Steps to reproduce

`config/_default/languages.toml`

~~~ toml
[de]
  languageName = "Deutsch"
  weight = 1
  defaultContentLanguage = "de"
  [de.params]
    dateFormat = ':date_full'
    description = "Anleitungen, HowTos, Code-Schnipsel & Blog"
    pygmentsUseClasses = true
    comment = false
  [de.params.archive]
    dateFormat = "1. Jan"
 ~~~

### Expected behavior

The expected appearance would be a translation into german
~~~
Oktober
2 Beiträge insgesamt
Sonstiges   Okt 30
GIT         Okt 11
~~~

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of theme are you using?

pull master-branch a few minutes ago

### What version of Hugo are you using?

0.119.0

### What version of Git are you using?

2.42.0

### Additional context

The error should be in this file:

`/layouts/partials/archives/year.html` 

in the lines 7 and 20:

https://github.com/razonyang/hugo-theme-bootstrap/blob/master/layouts/partials/archives/year.html#L7
https://github.com/razonyang/hugo-theme-bootstrap/blob/master/layouts/partials/archives/year.html#L20

**Comment by rainerrose** [comment]
In line 20 I've a look at  /layouts/partials/archives/list.html and "copied" it:

~~~ html
<span class="float-end post-date">{{ .Date | time.Format (default "Jan 2" site.Params.archive.dateFormat) }}</span>
~~~

Unfortunately I have no idea for line 4

~~~ 
{{- $yearPage := $page.GetPage (printf "%s%s/" $basePath .Key) -}}
~~~

**Comment by razonyang** [comment]
Fixed by cde8594c0d3a32d2a8615da9e9bda36f7e1ef659

**Comment by razonyang** [comment]
Thank you.

**Comment by rainerrose** [comment]
> Fixed by [cde8594](https://github.com/razonyang/hugo-theme-bootstrap/commit/cde8594c0d3a32d2a8615da9e9bda36f7e1ef659)

Because you've already closed it

May I politely ask if you have any ideas for line 4?

**Comment by razonyang** [comment]
1. The `basePath` is `/archives` by default, which was passed from the https://github.com/razonyang/hugo-theme-bootstrap/blob/f663634be27a3e0ef421e5582ea5d17b7e0762df/layouts/_default/archives.html#L18.
2. The `.Key` is the year part of post's date.

That code is used to get the archives pages that group by year.

**Comment by razonyang** [comment]
Seems that I missed one, do you want this to be cofigured?

![image](https://github.com/razonyang/hugo-theme-bootstrap/assets/17720932/41d8aa8d-7689-419e-b125-c5de8a20f5e0)

**Comment by rainerrose** [comment]
> Seems that I missed one, do you want this to be cofigured?
> 
> ![image](https://user-images.githubusercontent.com/17720932/280531087-41d8aa8d-7689-419e-b125-c5de8a20f5e0.png)

Ah yes! That's right. That's what I was trying to describe. I think line 4 should be changed here, but my tries so far have been unsuccessful.

**Comment by razonyang** [comment]
@rainerrose I didn't find a localization date format for month only on https://gohugo.io/functions/time/format/#localization, it may be impossible.

But I can add a parameter to format it as number instead, e.g. `01`.

**Comment by rainerrose** [comment]
> @rainerrose I didn't find a localization date format for month only on https://gohugo.io/functions/time/format/#localization, it may be impossible.

Ah. Uh. What a pity.

> But I can add a parameter to format it as number instead, e.g. `01`.

That would be great! Thank you.

**Comment by razonyang** [comment]
@rainerrose Added, see https://hbs.razonyang.com/v1/en/docs/layouts/archives/, you can also use the localization token in the future if there is any format for month only.

**Comment by rainerrose** [comment]
> @rainerrose Added (`archive.monthFormat`), see https://hbs.razonyang.com/v1/en/docs/layouts/archives/, you can also use the localization token in the future if there is any format for month only, since I'm not sure there is one.

Thank you very much! That was once again very fast. I just have to do something else (family time) and will try this a little later.

**Comment by rainerrose** [comment]
Works fine! Thanks a lot.

**Comment by rainerrose** [comment]
> @rainerrose I didn't find a localization date format for month only on https://gohugo.io/functions/time/format/#localization, it may be impossible.

I submit an feature request https://github.com/gohugoio/hugo/issues/11673

**Comment by razonyang** [comment]
@rainerrose I looked into the Hugo source code, month only format is supported, I pushed a bugfix to master branch, you can try and close that feature request.

**Comment by rainerrose** [comment]
First of all, thank you very much.
The request has already been closed. I neglected to use the forum first.

Thanks for the patch. Now it looks the way I would like it to. Thank you very much for your work.

![month](https://github.com/razonyang/hugo-theme-bootstrap/assets/99129105/61bfea86-4aaa-42a0-af72-5e1610359859)
