### ISSUE TITLE
A way to disable numberifyHeading per post

### ISSUE THREAD

**Issue by qu1ck** [razonyang/hugo-theme-bootstrap#1008]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests

### Proposal

Add a front matter param to disable auto numbering of headings.

### Motivation and context

It's good to have auto numbering of headings enabled globally but I would like to be able to disable it for specific posts where it does not make sense.

**Comment by razonyang** [comment]
Added, specify the `numberifyHeadings` as `false` on front matter to disable it.
