### ISSUE TITLE
Unable to replace logo and profile images

### ISSUE THREAD

**Issue by jymchng** [razonyang/hugo-theme-bootstrap#1015]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

@razonyang How to change the logo and picture of the website? I put `logo.webp` and `profile.webp` under `static/images` folder but it still does not work.

### Steps to reproduce

@razonyang How to change the logo and picture of the website? I put `logo.webp` and `profile.webp` under `static/images` folder but it still does not work.

### Expected behavior

@razonyang How to change the logo and picture of the website? I put `logo.webp` and `profile.webp` under `static/images` folder but it still does not work.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of theme are you using?

require github.com/razonyang/hugo-theme-bootstrap v1.2.2 // indirect

### What version of Hugo are you using?

hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended windows/amd64 BuildDate=2023-08-07T12:49:48Z VendorInfo=gohugoio

### What version of Node.js are you using?

v18.18.0

### What version of Git are you using?

git version 2.38.1.windows.1

**Comment by razonyang** [comment]
Seems you're doing it right, does `CTRL` + `F5` to force refresh helps?

It would be helpful to reproduce this issue if you can provide a public repo.

**Comment by jymchng** [comment]
Okay, I managed to resolve it @razonyang, thank you! :)
