### ISSUE TITLE
How to add Google AdSense to your theme

### ISSUE THREAD

**Issue by jymchng** [razonyang/hugo-theme-bootstrap#1021]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

I have read the blog of someone who provided a guide on how to add Google AdSense to his blog: https://jh123x.com/blog/2022/how-to-add-ads-to-hugo/.

In it, it says he has to add some HTML to `extend-head.html`.

For your theme, what is it that I need to do?

### Steps to reproduce

I have read the blog of someone who provided a guide on how to add Google AdSense to his blog: https://jh123x.com/blog/2022/how-to-add-ads-to-hugo/.

In it, it says he has to add some HTML to `extend-head.html`.

For your theme, what is it that I need to do?

### Expected behavior

Able to add Google AdSense.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of theme are you using?

require github.com/razonyang/hugo-theme-bootstrap v1.2.2 // indirect

### What version of Hugo are you using?

hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended windows/amd64 BuildDate=2023-08-07T12:49:48Z VendorInfo=gohugoio

### What version of Node.js are you using?

v18.18.0

### What version of Git are you using?

git version 2.38.1.windows.1

**Comment by razonyang** [comment]
Specify the `googleAdsense` parameter should work.

```yaml
// params.yaml
googleAdsense: "CA-XXX-XXXXXXX"
```

**Comment by jymchng** [comment]
Cool, let me try it, thank you @razonyang sir!
