### ISSUE TITLE
Add Rust code snippets that can be run with Rust Playground

### ISSUE THREAD

**Issue by jymchng** [razonyang/hugo-theme-bootstrap#1022]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

I have read [https://github.com/sam-ma/hugo-shortcodes/tree/master](https://github.com/sam-ma/hugo-shortcodes/tree/master?tab=readme-ov-file#2-rust---for-something-similar-to-rust-book) to learn how to add Rust code snippets such that it can be ran with Rust Playground.

Step 4 of it says:

> Copy [your hugo site home]/themes/[the theme you choose]/layouts/partials/head.html to [your hugo site home]/layouts/partials/header.html

But your theme doesn't have `layouts/partials/head.html`.

Same for Step 6 which says:

> Copy [your hugo site home]/themes/[the theme you choose]/layouts/partials/footer.html to [your hugo site home]/layouts/partials/footer.html

### Steps to reproduce

I have read [https://github.com/sam-ma/hugo-shortcodes/tree/master](https://github.com/sam-ma/hugo-shortcodes/tree/master?tab=readme-ov-file#2-rust---for-something-similar-to-rust-book) to learn how to add Rust code snippets such that it can be ran with Rust Playground.

Step 4 of it says:

> Copy [your hugo site home]/themes/[the theme you choose]/layouts/partials/head.html to [your hugo site home]/layouts/partials/header.html

But your theme doesn't have `layouts/partials/head.html`.

Same for Step 6 which says:

> Copy [your hugo site home]/themes/[the theme you choose]/layouts/partials/footer.html to [your hugo site home]/layouts/partials/footer.html

### Expected behavior

Able to run Rust code snippets on Rust Playground.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of theme are you using?

require github.com/razonyang/hugo-theme-bootstrap v1.2.2 // indirect

### What version of Hugo are you using?

hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended windows/amd64 BuildDate=2023-08-07T12:49:48Z VendorInfo=gohugoio

### What version of Node.js are you using?

v18.18.0

### What version of Git are you using?

git version 2.38.1.windows.1

**Comment by razonyang** [comment]
You can add any HTML via [hooks](https://hbs.razonyang.com/v1/en/docs/advanced/hooks/).

**Comment by jymchng** [comment]
When I add the `head-end.html` and the `footer-begin.html` as what the guide to add Rust Playground code snippets says, I got the following on my website - which is ugly.

![image](https://github.com/razonyang/hugo-theme-bootstrap/assets/27895426/1becce39-898b-4d1d-a15a-ae6a42c79d14)

`head-end.html`
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/rust.min.js"></script>
<link rel="stylesheet" type="text/css" href="{{ .Site.BaseURL }}css/rust.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css">
```

`footer-begin.html`
```
<script src="{{ .Site.BaseURL }}js/rust.js"></script>
```

**Comment by jymchng** [comment]
How do you think I can resolve it? @razonyang Thank you.

**Comment by razonyang** [comment]
Have no idea, I haven't use that shortcode, I don't know how it looks originally.
Perhaps it was affected by Bootstrap, you'll need to tweak the styles (requires CSS skill), see https://hbs.razonyang.com/v1/en/docs/advanced/custom-assets/#internal-assets.
