### ISSUE TITLE
Errors when using the new version of Hugo - 0.123

### ISSUE THREAD

**Issue by wildserver** [razonyang/hugo-theme-bootstrap#1026]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

After updating to the latest version of hugo 0.123 Multiple errors:

```bash
hugo server -D
hugo: collected modules in 559 ms
Watching for changes in /sudakov.spb.ru/{archetypes,assets,content,data,layouts,package.hugo.json,package.json,static}
Watching for config changes in /sudakov.spb.ru/config/_default, /sudakov.spb.ru/go.mod
Start building sites … 
hugo v0.123.0-3c8a4713908e48e6523f058ca126710397aa4ed5+extended linux/amd64 BuildDate=2024-02-19T16:32:38Z VendorInfo=snap:0.123.0

ERROR render of "page" failed: "/.cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/razonyang/hugo-theme-bootstrap@v1.5.3/layouts/_default/baseof.html:11:38": execute of template failed: template: _default/single.html:11:38: executing "title$htmltemplate_stateRCDATA_elementTitle" at <partial "head/title" .>: error calling partial: "/.cache/hugo_cache/modules/filecache/modules/pkg/mod/github.com/razonyang/hugo-theme-bootstrap@v1.5.3/layouts/partials/head/title.html:21:19": execute of template failed: template: partials/head/title.html:21:19: executing "partials/head/title.html" at <.Paginate>: error calling Paginate: pagination not supported for this page: kind: "page", path: "/blog/readme", file: "/sudakov.spb.ru/content/blog/readme/index.md"
...
```
When running in the older version of Hugo 0.122, everything is generated normally.

I have long come to terms with this message; it does not interfere with my life :grin::

```bash
Watching for changes in /sudakov.spb.ru/{archetypes,assets,content,data,layouts,package.hugo.json,package.json,static}
Watching for config changes in /sudakov.spb.ru/config/_default, /sudakov.spb.ru/go.mod
```
If annoying, run with these parameters:
` hugo server -w=false`

In Windows 10 I rolled back to hugo version 0.122. But in Debian 10 I don’t know what to do to use the latest version of hugo. Maybe someone can tell me how to roll back to version 0.122 in Debian?

### Steps to reproduce

hugo server -D

### Expected behavior

```bash
Start building sites … 
hugo v0.122.0-b9a03bd59d5f71a529acb3e33f995e0ef332b3aa+extended windows/amd64 BuildDate=2024-01-26T15:54:24Z VendorInfo=gohugoio

...

Total in 3739 ms
```

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What version of theme are you using?

github.com/razonyang/hugo-theme-bootstrap v1.5.3

### What version of Hugo are you using?

0.123

### What version of Node.js are you using?

v12.22.12

### What version of Git are you using?

2.30.2

**Comment by razonyang** [comment]
Thanks for reporting this, will check later.

> Maybe someone can tell me how to roll back to version 0.122 in Debian?

To downgrade Hugo to v0.122.0 on Debain/Ubuntu.

```sh
wget https://github.com/gohugoio/hugo/releases/download/v0.122.0/hugo_0.122.0_linux-amd64.tar.gz

tar -xvf hugo_0.122.0_linux-amd64.tar.gz

sudo cp hugo_0.122.0_linux-amd64/hugo /usr/local/bin/hugo-122

hugo-122 version
```
