### ISSUE TITLE
can not find ref

### ISSUE THREAD

**Issue by phenix3443** [razonyang/hugo-theme-bootstrap#1035]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

<img width="1426" alt="image" src="https://github.com/razonyang/hugo-theme-bootstrap/assets/1721532/45d7c4d8-29f6-4423-add7-80cb33e54a6f">
今天使用hugo server -D 启动的时候突然出现找不到文章引用的情况

### Steps to reproduce

https://github.com/phenix3443/blog/actions/runs/8353853479/job/22866241342

### Expected behavior

应该可以正常编译出网页产物

### What operating system(s) are you seeing the problem on?

macOS, Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of theme are you using?

master

### What version of Hugo are you using?

hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended

**Comment by razonyang** [comment]
链接所对应的日志和截图对不上，就链接对应的日志来讲，安装依赖那一步错了，但并没有报错。

![image](https://github.com/razonyang/hugo-theme-bootstrap/assets/17720932/eda2653d-f945-4d10-87cc-b1eea133028a)

**Comment by razonyang** [comment]
Hugo v0.123.* 以后的版本会出现这个问题，我不确定是这不是 Bug，我在官方论坛问了，https://discourse.gohugo.io/t/ref-not-working-when-using-relative-path-since-v0-123-0/48939。

你可以降低 Hugo 的版本（v0.122.* 或以下）以正常部署，等官方回复再确定是否需要修改。

**Comment by razonyang** [comment]
官方回复说`0.123.0`之后的逻辑路径改了，详情参阅 https://gohugo.io/methods/page/path/#logical-tree 。

**Comment by phenix3443** [comment]
好的，问题已经解决了，感谢解答

**Comment by phenix3443** [comment]
> 官方回复说`0.123.0`之后的逻辑路径改了，详情参阅 https://gohugo.io/methods/page/path/#logical-tree 。
那当前有跟随 hugo 0.123 版本做更改么？

**Comment by razonyang** [comment]
> 那当前有跟随 hugo 0.123 版本做更改么？

若你是指主题的话，这个问题和主题无关（`ref` 和 `relref` 是 Hugo 内置的短代码），而且我一般使用的是绝对路径，所以主题应该没什么影响和需要改动的。而你则需要改动 `ref`/`relref` 的路径，因为现在其改为**逻辑路径**，和**文件路径**不等同。

**Comment by razonyang** [comment]
> pagination not supported for this page: kind: "page"

这个已于 v1.5.4 中修复，升级到主题的最新版本应该可以解决，https://github.com/razonyang/hugo-theme-bootstrap/releases。

**Comment by phenix3443** [comment]
应该如何升级主题？直接修改 go.mod中的版本么？

Razon Yang ***@***.***> 于2024年4月16日周二 16:30写道：
