### ISSUE TITLE
Configuration parameter to prevent reduction in font size of left sidebar in docs layout

### ISSUE THREAD

**Issue by sagarbehere** [razonyang/hugo-theme-bootstrap#1045]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests

### Proposal

Add a configuration parameter to prevent reduction in font size in the left sidebar of the docs layout. For example, something like
```
docs:
  reduceFontSize: false
```
Alternatively, just remove the font size reduction entirely.

### Motivation and context

The navigation sidebar (left sidebar) in docs layout keeps reducing the font size as you go deeper into the hierarchy. At deeper levels in the hierarchy, the font size becomes too small to easily read. For example, in the image below, the font size has become very small for text like 'add-backlinks' 
![reducingFontSize](https://github.com/user-attachments/assets/181f7cba-d73d-4be5-ad7c-a57c62e50e2f)

In the older version of the theme I am currently using, there is no font size reduction and all the text is readable even if it is deep in the hierarchy. See below the same example, but with older version of the theme.
![sameFontSize](https://github.com/user-attachments/assets/eedd881f-dfab-4262-b428-38b9c08276e8)

I have very deep hierarchies in my docs layout.. so I would like to prevent font size reduction to keep the text readable.

**Comment by razonyang** [comment]
> Alternatively, just remove the font size reduction entirely.

Removing `fontSize` block from `params.yaml` may help, I'm not quite sure.

**Comment by sagarbehere** [comment]
@razonyang Removing `fontSize` block from `params.yaml` does not help. That just removes the option to change font sizes from the top bar.

**Comment by razonyang** [comment]
I see, I'm misundertanding this request, will create a parameter for this.

**Comment by razonyang** [comment]
To do this, please upgrade to v1.6.0, and configure the following parameter.

```yaml
// params.yaml
docsNav:
  reduceFontSize: false
```

**Comment by sagarbehere** [comment]
@razonyang Thanks. This works perfectly. 

Just a minor comment. My `config/_default/params.yaml` looks like this right now
```
#docs:
  # nav:
    # expand: true # Expand docs navigations.

docsNav:
  reduceFontSize: false
```
Since there is already a top level section named `docs` in the `params.yaml` file, it might have been more logical to make this configuration under the existing `docs`. For example, something like
```
docs:
  nav:
    expand: false
    reduceFontSize: false
```

**Comment by razonyang** [comment]
@sagarbehere thanks for pointing it out, I don't remmember there is, I'm renaming it to `docs.nav.reduceFontSize`, and draft a new release later.

**Comment by razonyang** [comment]
Renamed since v1.6.1.

**Comment by sagarbehere** [comment]
I just tested with v1.6.1. It works. Thank you for the quick fix.
