### ISSUE TITLE
有没有config.toml啊，自己菜鸟不会配置啊。

### ISSUE THREAD

**Issue by xiaoyaozz** [razonyang/hugo-theme-bootstrap#105]
如题！

**Comment by razonyang** [comment]
[exampleSite](https://github.com/razonyang/hugo-theme-bootstrap/tree/master/exampleSite/config) 里面有。

**Comment by razonyang** [comment]
你可以将整个[exampleSite](https://github.com/razonyang/hugo-theme-bootstrap/tree/master/exampleSite/)复制，然后再进行修改也可以的。

https://github.com/razonyang/hugo-theme-bootstrap/blob/master/README.zh-CN.md#%E5%AE%89%E8%A3%85
