### ISSUE TITLE
Code block maxlines and linenos not working in case of without specifying code fence.

### ISSUE THREAD

**Issue by razonyang** [razonyang/hugo-theme-bootstrap#1052]

**Comment by razonyang** [comment]
@sagarbehere I just tested with latest version, seems everything is OK, could you please confirm that?

**Comment by sagarbehere** [comment]
@razonyang 

> I just tested with latest version, seems everything is OK, could you please confirm that?

I tested with v1.6.2. Everything is not okay yet. Here's what I see:

In the image below, the code fence has no specification, the left image is v1.6.1 and the right image is v1.6.2
![61-vs-62](https://github.com/user-attachments/assets/2b12000e-1791-4c31-b0d2-98becd544205)

As you can see, v1.6.2 does create a smaller window with scrollbars for the code block, but it still seems that there are more lines visible than `codeBlocks.maxLines` AND the line numbers are missing entirely.

However, if I specify the code fence with ` ```docker `, then v1.6.2 will format everything correctly, as shown in the image below
![Screenshot_20240819_121559](https://github.com/user-attachments/assets/1d540cfe-03fa-4587-8ac1-8294b43abd8e)

What I think should be possible, is to get something like the above WITHOUT specifying ` ```docker` in the .md file.

**Comment by razonyang** [comment]
Enable `markup.highlight.guessSyntax` to allow doing so, but keep in mind that it's not perfect, you probably see the wrong code fence (language) shown in the top-right of code block, I'd suggest always specifying the correct code fence manually.
But it still is the best solution for the existing content, you can modifying it later if code fence guessing is incorrect.

```
// config.yaml/hugo.yaml
markup:
  highlight:
    guessSyntax: true
```

It's not an issue that can be solved in theme, I'm closing it.
