### ISSUE TITLE
Incorrect layout of some pages in docs layout in v1.6.3 and beyond

### ISSUE THREAD

**Issue by sagarbehere** [razonyang/hugo-theme-bootstrap#1059]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

After going from v1.6.2 to v1.6.3, some of the content pages in the `docs/` layout are not rendered in their usual position next to the left sidebar. Instead, the content is rendered _below_ the left sidebar. See attached video. The same problem happens with v1.6.4. Reverting back to v1.6.2 make the problem disappear. 

https://github.com/user-attachments/assets/69a04f6c-303e-45aa-839c-63292c95990f

### Steps to reproduce

Follow the exact same steps as in https://github.com/razonyang/hugo-theme-bootstrap/issues/449#issuecomment-2295324813 (i.e. clone the hbs-skeleton theme, add the `Plausible.md` file in the `content/docs/` folder and run `hugo server` with v1.6.2. There will be no problem (as shown in the video above). Upgrade to v1.6.3 and the problem appears (as shown in the video above).

### Expected behavior

The content should appear in its usual position, next to the left sidebar.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of theme are you using?

v1.6.3

### What version of Hugo are you using?

0.118.2

### What version of Node.js are you using?

v12.22.9

### What version of Git are you using?

2.34.1

**Comment by razonyang** [comment]
Will check this out later.
