### ISSUE TITLE
Top bar sizing in v1.6.6

### ISSUE THREAD

**Issue by sagarbehere** [razonyang/hugo-theme-bootstrap#1063]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

I upgraded to v1.6.6 in order to test the solution for #1059 and also upgraded Hugo to v0.133.0-extended (since the release notes for v1.6.5 say that Hugo needs to be upgraded at least to v.0.125).

After the upgrade, the size of the top bar is too much in the vertical direction and it is not possible to see the content. See the video below.

https://github.com/user-attachments/assets/4c8627ab-fc98-4dae-a03e-3786ed3d65cc

### Steps to reproduce

Upgrade theme from v1.6.2 to v1.6.6

### Expected behavior

Top bar has fixed size, as with previous versions of the theme.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of theme are you using?

v1.6.6

### What version of Hugo are you using?

0.133.0-extended

### What version of Node.js are you using?

v12.22.9

### What version of Git are you using?

2.34.1

**Comment by razonyang** [comment]
It's weird, there is no changes about top bar, and I couldn't reproduce it with the [template](https://hbs-skeleton.netlify.app/), which already [upgrade to v1.6.6](https://github.com/razonyang/hugo-theme-bootstrap-skeleton/blob/main/go.mod).

I can't image what is happening, I've tried on Chrome and FireFox, couldn't reproduce it.

**Comment by sagarbehere** [comment]
@razonyang Hmmm.. let me play around with the template and I will report back.

**Comment by razonyang** [comment]
OK, if the issue still exist after clearing cache, please share a repo with me via email or github repo invitation, I'll check it morning/afternoon.

**Comment by sagarbehere** [comment]
@razonyang Interesting.. this isn't happening with the template. But it IS happening with my site. My site is based on the theme instructions of "Using the theme with an existing site". If I roll back my website to v1.6.5 the top bar sizing problem disappears. If I upgrade to v1.6.6, at appears again. See video below

https://github.com/user-attachments/assets/1f5dcd5f-a28c-4499-a95c-4b39501c2453

I will play around a bit more and report what I see and share the repo with you. I will also try to create the site again based on the latest version of the template, but I'd like to avoid doing that if there is another easier solution.

**Comment by sagarbehere** [comment]
@razonyang I figured out how to reproduce the issue in the template theme. Edit `config/_default/params.yaml` and remove the # from `fixed: true` in the `sidebar` section

```
sidebar:
  fixed: true
  # archives: true # Enable archives widget
  # taxonomiesToggle: false # Disable taxonomy toggle
```

Once you do this and run `hugo server`, you should be able to see the issue with the top bar size. 

Please let me know if you can reproduce it this way. Else I will send you a minimum example.

**Comment by razonyang** [comment]
Thanks, there is a function used by several areas, but I forgot it, I'm working on it.
