### ISSUE TITLE
Navigation links on docs pages are incorrect

### ISSUE THREAD

**Issue by sdwheeler** [razonyang/hugo-theme-bootstrap#1079]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

There are two issues:
1. The left-hand link should point to the previous item and the right-hand link should point to the next item.
2. The prev/next links are not following the Nav order in the TOC

### Steps to reproduce

In this screenshot you can see (from the TOC) that I am viewing the [Docs Layout](https://hbs.razonyang.com/v1/en/docs/layouts/docs/) page.
![image](https://github.com/user-attachments/assets/bdc50f85-7b56-4005-b732-6aaba5b199a4)

In the navigation links at the bottom of the page
- The previous link (left side) is pointing to _FAQ Layout_, which is the next item in the TOC
- The next link (right site) is pointing to _Landing Page Layout_, which is after _FAQ Layout_ in the TOC.

### Expected behavior

- The previous link (left side) should point to _Contact Form_
- The next link (right site) should point to _FAQ Layout_

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of theme are you using?

hugo-theme-bootstrap v1.7.3

### What version of Hugo are you using?

hugo v0.134.3

### What version of Node.js are you using?

v20.16.0

### What version of Git are you using?

git version 2.47.0.windows.2

### Additional context

Part of the problem is in `partials/post/nav.html`. To fix this I swapped the order of the next/prev divs.

```html
{{- if and (default true .Site.Params.post.nav) (default true .Params.nav) (or .PrevInSection .NextInSection) -}}
<div class="card-footer">
  <div class="post-navs d-flex justify-content-evenly">
    {{- with .NextInSection -}}
    <div class="post-nav post-next">
      <i class="fas fa-fw fa-chevron-down post-next-icon ms-1" data-fa-transform="rotate-90"></i>
      <a href="{{ .RelPermalink }}">{{ partial "helpers/title" . }}</a>
    </div>
    {{- end -}}
    {{- with .PrevInSection -}}
    <div class="post-nav post-prev">
      <a href="{{ .RelPermalink }}">{{ partial "helpers/title" . }}</a>
      <i class="fas fa-fw fa-chevron-down post-prev-icon me-1" data-fa-transform="rotate-270"></i>
    </div>
    {{- end -}}
  </div>
</div>
{{- end -}}
```

**Comment by razonyang** [comment]
Thank you for your feedback.
