### ISSUE TITLE
Adding assThis id doesn't show sharing buttons anywhere

### ISSUE THREAD

**Issue by sudipghimire533** [razonyang/hugo-theme-bootstrap#108]
I have been testing the theme and everything is going well but share buttons. I add my addThis id in `params.toml` as
```
[share]
    addThis = "my-id"
```
But the share buttons doesn't show at all even I set floating or inline style from addThis dashboard

**Comment by razonyang** [comment]
Does the console display any error messages?

> If you're using Chrome, press `F12` and navigate to the `Console` tab.

**Comment by sudipghimire533** [comment]
Console shows `net::ERR_BLOCKED_BY_CLIENT` and one of my extension may be blocking the required javascript
