### ISSUE TITLE
从源码包下载 把主题放在content 运行的时候提示 没有找到 template for shortcode "mermaid" not found

### ISSUE THREAD

**Issue by Driven3q** [razonyang/hugo-theme-bootstrap#1085]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

[root@mark hugo]# docker run --rm -it   -v $(pwd)/src:/src   -p 1313:1313   klakegg/hugo:latest-ext   server
Start building sites … 
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended linux/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=hugoguru
Error: Error building site: "/src/content/posts/diagram/index.md:71:1": failed to extract shortcode: template for shortcode "mermaid" not found
Built in 1 ms

### Steps to reproduce

[root@mark src]# cd content/
[root@mark content]# ls
about  posts
[root@mark content]# cd posts/
[root@mark posts]# ls
diagram  emoji-support  _index.fr.md  _index.ja.md  _index.md  _index.zh-hans.md  _index.zh-hant.md  markdown-syntax  math-typesetting  placeholder-text  rich-content
[root@mark posts]# cd diagram/
[root@mark diagram]# ls
index.md
[root@mark diagram]# cat index.md 
+++
title = "Diagram Guide"
description = "Guide to diagram usage in Markdown"
date = 2021-09-01T11:36:50+08:00
featured = false
draft = false
comment = true
toc = true
reward = true
categories = [
  "Markdown"
]
tags = [
  "Diagram"
]
series = [
  "Docs"
]
authors = ["RazonYang"]
+++

This article offers a sample of basic diagram usage that can be used in Hugo content files.

Please see also [Mermaid](https://mermaid-js.github.io).

### Via Shortcode

```markdown
{{</* mermaid */>}}
YOUR DIAGRAM INSTRUCTIONS
{{</* /mermaid */>}}
```

You can also wrap the shortcode with other shortcodes, such as `text/align-center`.

```markdown
{{%/* text/align-center */%}}
{{</* mermaid */>}}
YOUR DIAGRAM INSTRUCTIONS
{{</* /mermaid */>}}
{{%/* /text/align-center */%}}
```

### Mermaid code block

````markdown
```mermaid
YOUR DIAGRAM INSTRUCTIONS
```
````

### Flow Chart

```markdown
{{</* mermaid */>}}
graph TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fas:fa-car Car]
{{</* /mermaid */>}}
```

{{% text/align-center %}}
{{< mermaid >}}
graph TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fas:fa-car Car]
{{< /mermaid >}}
{{% /text/align-center %}}

We need to [import the `faCar` solid icon]({{< ref "docs/look-and-feel#icons" >}}) first, in order to use the `fas:fa-car` FontAwesome icon.

### Sequence Diagram

```markdown
{{</* mermaid */>}}
sequenceDiagram
    Alice->>+John: Hello John, how are you?
    Alice->>+John: John, can you hear me?
    John-->>-Alice: Hi Alice, I can hear you!
    John-->>-Alice: I feel great!
{{</* /mermaid */>}}
```

{{% text/align-center %}}
{{< mermaid >}}
sequenceDiagram
    Alice->>+John: Hello John, how are you?
    Alice->>+John: John, can you hear me?
    John-->>-Alice: Hi Alice, I can hear you!
    John-->>-Alice: I feel great!
{{< /mermaid >}}
{{% /text/align-center %}}

### Class Diagram

````markdown
```mermaid
classDiagram
    Animal <|-- Duck
    Animal <|-- Fish
    Animal <|-- Zebra
    Animal : +int age
    Animal : +String gender
    Animal: +isMammal()
    Animal: +mate()
    class Duck{
      +String beakColor
      +swim()
      +quack()
    }
    class Fish{
      -int sizeInFeet
      -canEat()
    }
    class Zebra{
      +bool is_wild
      +run()
    }
```
````

```mermaid
classDiagram
    Animal <|-- Duck
    Animal <|-- Fish
    Animal <|-- Zebra
    Animal : +int age
    Animal : +String gender
    Animal: +isMammal()
    Animal: +mate()
    class Duck{
      +String beakColor
      +swim()
      +quack()
    }
    class Fish{
      -int sizeInFeet
      -canEat()
    }
    class Zebra{
      +bool is_wild
      +run()
    }
```

### Expected behavior

没了

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of theme are you using?

hugo-theme-bootstrap-1.8.4.tar.gz

### What version of Hugo are you using?

latest

### What version of Node.js are you using?

latest

### What version of Git are you using?

git version 1.8.3.1

**Comment by razonyang** [comment]
请问你是如何安装的？

如果没理解错，你是打算手动下载，若此，将压缩包解压到 themes 目录下，比如保存为 `themes/hugo-theme-bootstrap` ，并于配置中将 `theme` 设置为 `themes/hugo-theme-bootstrap`。

若还不能正常运行，请提供可重现的代码仓库。

另外我不推荐此种安装方法，后续主题不好更新，推荐的安装方法可在 https://hbs.razonyang.com/v1/zh-hans/docs/getting-started/installation/ 找到。

**Comment by razonyang** [comment]
题外话， ` klakegg/hugo` 已经一两年没更新了，最新的标签是 `v0.111.3`，而 Hugo 最新版本为 `0.139.3`，可以考虑替换为 [hugomods/hugo](https://docker.hugomods.com/zh-hans/docs/development/)

**Comment by Driven3q** [comment]
好

---- 回复的原邮件 ----
| 发件人 | Razon ***@***.***> |
| 发送日期 | 2024年12月05日 22:48 |
| 收件人 | razonyang/hugo-theme-bootstrap ***@***.***> |
| 抄送人 | Marks ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [razonyang/hugo-theme-bootstrap] 从源码包下载 把主题放在content 运行的时候提示 没有找到 template for shortcode "mermaid" not found (Issue #1085) |

题外话， klakegg/hugo 已经一两年没更新了，最新的标签是 v0.111.3，而 Hugo 最新版本为 0.139.3，可以考虑替换为 hugomods/hugo

**Comment by razonyang** [comment]
有任何新进展吗？没有的话我就先关闭了，后续请随时于下方补充。

**Comment by Driven3q** [comment]
可以的 多谢

---- 回复的原邮件 ----
| 发件人 | Razon ***@***.***> |
| 发送日期 | 2024年12月21日 09:57 |
| 收件人 | razonyang/hugo-theme-bootstrap ***@***.***> |
| 抄送人 | Marks ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [razonyang/hugo-theme-bootstrap] 从源码包下载 把主题放在content 运行的时候提示 没有找到 template for shortcode "mermaid" not found (Issue #1085) |

有任何新进展吗？没有的话我就先关闭了，后续请随时于下方补充。
