### ISSUE TITLE
Add about label without need of creating new file

### ISSUE THREAD

**Issue by sudipghimire533** [razonyang/hugo-theme-bootstrap#109]
I just came to realize that the `about` in author section will only appear if I have `about/index.md` inside `content/en/post`. It would be more easier to add that without needing to create such file. The best I can think of is to do something like this in `config/_default/author.toml`
```
name = "name"
bio = ""
....
about = "https://about.me"
```
or something like this.

**Comment by razonyang** [comment]
Yep, that is how it designs. 

In my opinion, the `about` page has multiple translations in a multilingual site. In this case, it's more complicated to make the `about` as a parameter. We will be need to specify the `about` parameter per each language, such as `author.en.toml`, `author.zh.toml`.

But the way you provided is useful for specifying the `about` page that outside the site.

**Comment by sudipghimire533** [comment]
Ok I will be looking forward to link about page to external website for all language

**Comment by razonyang** [comment]
I'll keep the issue open until it has been implemented.

**Comment by razonyang** [comment]
Fixed by fe7348005875c25adbc838e82e222cebdf39d3eb(`v0.26.0`).
