### ISSUE TITLE
Deployment question

### ISSUE THREAD

**Issue by jehoshua7** [razonyang/hugo-theme-bootstrap#112]
I have installed the theme as per the instructions at https://github.com/razonyang/hugo-theme-bootstrap , and then run it locally as http://localhost:1313/en/ , and it all runs okay.

I have been able to deploy other themes and run them on a website, however I'm not able to deploy the 'hugo-theme-bootstrap' theme successfully.

Some questions please:

1.  What does this command do and why is it necessary ? `cp -a themes/hugo-theme-bootstrap/exampleSite/* .`
2. With other themes I have noticed the configuration file is in /mysite/themes/themename/exampleSite/config.toml , yet in this theme there are two files bearing that name, one ~/Hugo/mysite/themes/hugo-theme-bootstrap/exampleSite/config/production/config.toml and the other one at ~/Hugo/mysite/themes/hugo-theme-bootstrap/exampleSite/config/production/_default/config.toml .  Under the configuration options shown at https://github.com/razonyang/hugo-theme-bootstrap, I have tried modifying the "baseURL" , then deploy and upload to a site, yet the theme CSS seems missing and links do not show correctly.  
 Obviously I am doing something wrong with the deploy ??  It is simply  `~/Hugo/mysite/themes/hugo-theme-bootstrap/exampleSite$ hugo -D --themesDir ../..`

**Comment by razonyang** [comment]
The `cp` command is not necessary. The installation section shows how to create a site from scratch. If you already have a site, all you have to do is that add a git submodule and then modify your configuration.
`git submodule add https://github.com/razonyang/hugo-theme-bootstrap themes/hugo-theme-bootstrap`.

As the 2nd question, the example site uses a [configuration directory](https://gohugo.io/getting-started/configuration/#configuration-directory) instead of a single configuration file.

As the configuration path shows, `_default` means the default settings which will be merged into the target environment(production, development...).

> Default environments are **development** with hugo server and **production** with hugo.

In order to modify `baseURL`, it depends on how you configure your site:

- Single Configuration File: `/mysite/config.toml`.
- Configuration Directory: `/mysite/config/production/config.toml`.

**Comment by jehoshua7** [comment]
@razonyang - Thanks for your replies. It is obvious the directory structure for this theme is slightly different to the other themes I am testing. The theme runs fine locally, although the other themes run locally are of the nature http://localhost:1313 , yet for this theme I have to use http://localhost:1313/hugo/bootstrap/

Further testing of the deployment process still doesn't work for me. It seems to be simply related to the URL's and relative URL's.  Are there any specific instructions for deployment of this theme please ?  Also, is there a single language (english) version of the theme please ?  Thanks for your help.

**Comment by razonyang** [comment]
Applying this theme to an existing site(`myblog`):

Add a git submodule

```shell
cd myblog
git submodule add https://github.com/razonyang/hugo-theme-bootstrap themes/hugo-theme-bootstrap
```

Copy configuration

```shell
mkdir config
cp -a themes/hugo-theme-bootstrap/exampleSite/config/* ./config
```

Rename the single config file
```shell
mv config.toml config.toml.orig
```

> This step prevents the single configuration file from conflicting with the configuration directory.

Btw, you can also generate a single configuration file(`config.toml`). Take `params.toml` as an example, copy and paste the content under the `[params]` table of `config.toml`.

```
baseURL = "http://example.org/"
title = "My Blog"

[params]
  # paste params.toml content here

[social]
  # paste social.toml content here

# ...
```

**Additional steps**

Remove other language's configurations.

```shell
rm config/_default/*.zh-*.toml
```

And then remove needless language items from `languages.toml`.

You can reach me via [email](mailto:razonyang@gmail.com).

**Comment by jehoshua7** [comment]
@razonyang -  Thanks for your reply, that is awesome. It now works fine on the website.

> > This step prevents the single configuration file from conflicting with the configuration directory.

That must have been what fixed it, thank you.  I haven't dome the language modifications or the config file modifications yet, just wanted to get the theme going on the website.  Thanks  :)

**Comment by jehoshua7** [comment]
> You can reach me via [email](mailto:razonyang@gmail.com).

Thanks for your help. Have decided to use this theme on the website. Have emailed you.

**Comment by razonyang** [comment]
@jehoshua7 The pleasure is mine. 

BTW, if you followed steps I mentioned above. There is an important step for turning on **Archive** and **Search** features:

Please copy  the [archives](https://github.com/razonyang/hugo-theme-bootstrap/tree/master/exampleSite/content/en/archives) and [search](https://github.com/razonyang/hugo-theme-bootstrap/tree/master/exampleSite/content/en/search) directory to the **content** directory.

**Comment by jehoshua7** [comment]
> Remove other language's configurations.
> 
> ```shell
> rm config/_default/*.zh-*.toml
 ```
> 
> And then remove needless language items from `languages.toml`.

Just to be sure, is that `rm` in

/~/......../mysite/config/_default
    
    or
    
    /~/......../mysite/themes/hugo-theme-bootstrap/exampleSite/config/_default
    
    or both please ?

**Comment by jehoshua7** [comment]
@razonyang -  Thanks for your reply to my email, the website works again now. As per your instructions I had to modify /~/Hugo/mysite/themes/hugo-theme-bootstrap/exampleSite/config/production/config.toml
