### ISSUE TITLE
User intractable toggle to hide/show the content only (hiding the sidebar)

### ISSUE THREAD

**Issue by sudipghimire533** [razonyang/hugo-theme-bootstrap#115]
It would be wiser to put a toggling button somewhere on the top right corner (not in navbar) near post title to achive something like this
![image](https://user-images.githubusercontent.com/39845901/124242139-262df980-db3c-11eb-8387-d3fcdb39e5f2.png)

I also realized that putting that button anywhere on home page would steal current look but adding that on the post page would be plus point.

**Comment by sudipghimire533** [comment]
Reading on maximum width on https://hugo-theme-bootstrap.netlify.app/ was more good btw. So I have to scroll less and it would be no trouble for people who wants to see just the content while reading

**Comment by razonyang** [comment]
Implemented in 195ebb5a7eb7251c5be1fc3ca8a11e274b305d8e. Please upgrade the theme to the latest version(v0.28.0) or the latest commit.

**Comment by sudipghimire533** [comment]
Is that really the intended position of the fullscreen button as well as TOC button? Or is this just happening on mine
![image](https://user-images.githubusercontent.com/39845901/124601372-79c77c80-de87-11eb-8f94-1bf41f5ed017.png)
I really wish I could help you on this but currently I can't

**Comment by razonyang** [comment]
Yep, that's intended. Any suggestions are welcome.

**Comment by sudipghimire533** [comment]
Buddy! I think this one was your first miss. That's seems disturbing  (I got same feedback from couple of my mates). TOC button  placement was just perfect before.  And thing about expand button may somwhere as in below image
![image](https://user-images.githubusercontent.com/39845901/124611998-b0a29000-de91-11eb-85f3-a54ab086ffcf.png)
And we may also change icon of expanding button accordingly (if current state is expanded or not) or using the icon like this may be wise 
![image](https://user-images.githubusercontent.com/39845901/124613070-96b57d00-de92-11eb-8545-6c0b5e6097b5.png)


also persisting between session for expanded state (Same way you did fabulous job to persist color palette, and dark theme toggling) and Also what about not expanding the panel by deafult on device with smaller width (this is not that much of importance though)?

I am just another guy explaining what I think would be clean. feel free to correct me. At the same time I am also trying to praise you and not pressurize :wink:

**Comment by razonyang** [comment]
LGTM, I'll try to implement it. Thanks for your suggestions.

**Comment by razonyang** [comment]
Reopen it until it's done~

**Comment by razonyang** [comment]
@sudipghimire533 Done. You can see the change in https://hugo-theme-bootstrap.netlify.app/en/posts/markdown-syntax now.

I look forward to your feedback. I'll draft a new release after closing it.

**Comment by sudipghimire533** [comment]
Peerfect. Does there a icon that have same effect as `transfrom: rotateZ(-45deg)` And I guess persist is yet to implements

**Comment by sudipghimire533** [comment]
And what about hiding those sidbar by default in small screen?

**Comment by razonyang** [comment]
> And what about hiding those sidbar by default in small screen?

![image](https://user-images.githubusercontent.com/17720932/124696007-d7ef7080-df16-11eb-975e-47420701c1c2.png)

I don't think it's going to affect the reading in the small screen. And I'm worried that hiding the sidebar will affect the search engine index.

**Comment by razonyang** [comment]
> Does there a icon that have same effect as `transfrom: rotateZ(-45deg)` 
I didn't get it. Could you please explain it in detail?

> And I guess persist is yet to implements

Hmm, I think it's implemented, the behavior(hide/show sidebar) was stored in LocalStorage.

**Comment by sudipghimire533** [comment]
>Does there a icon that have same effect as transfrom: rotateZ(-45deg)
 I didn't get it. Could you please explain it in detail?
I mean to use the icon like that but tilted by -45deg. Just asking such icon available to use. Btw Everything looks good now. Didn't knew such thing about SEO. But ofcourse we should prioritize search engine. If hiding sidbar by default on smaller screen is to be worried with search engine then we better of not do that then

**Comment by razonyang** [comment]
Thanks for your suggestions and cooperation. I drafted a new release(v0.29.0) for that changes.
