### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by imlijq** [razonyang/hugo-theme-bootstrap#117]
我网络可以访问谷歌

![image](https://user-images.githubusercontent.com/19914442/124571400-521de780-de7a-11eb-9372-4a08cb913cbf.png)

另外建议支持关闭多语言，关闭多语言之后使用当前默认的语言比如zh-ch，language-switcher也就不显示了，页面的路径也就没有/zh-cn/2020/jsrun/了，而是直接显示/2020/jsrun/，改代码可以实现但源码支持不是更好嘛个人建议哈

**Comment by razonyang** [comment]
emm, 这个应该你那边的网络问题，我这边显示正常~

![image](https://user-images.githubusercontent.com/17720932/124573771-6f53b580-de7c-11eb-9cba-82f81ce470ac.png)

如果需要单语言版的话，删除一些配置就好了（比如 languages.toml，zh-tw、en 后缀的配置），以及修改 config.toml 中 `defaultContentLanguageInSubdir` 为 `false` 即可。

或者直接克隆以下仓库，修改内容就好：
https://github.com/razonyang/hugo-theme-bootstrap-example-site
