### ISSUE TITLE
建议添加“新建文章并设置文章属性”的快速上手指引

### ISSUE THREAD

**Issue by RuikangSun** [razonyang/hugo-theme-bootstrap#119]
今天发现了这个主题，感觉这个主题功能非常多。一些简单的hugo主题创建文章可能就是`hugo new posts/新文章.md`就搞定了，但这个主题还需要考虑多语言文章关联、shortcode等问题。因此建议添加“新建文章并设置文章属性”的快速上手指引，以满足使用者快速上手使用该主题的需要。

**Comment by RuikangSun** [comment]
另外有一个不是很重要的新功能请求：在Social Links里添加哔哩哔哩。因为B站对h5外链比较友好哈，是一个不错的第三方平台。
我查了一下在Font Awesome里没有B站的相关图标，不过可以先使用[电视图标](https://fontawesome.com/v5.15/icons/tv?style=solid)先作为代替。

**Comment by razonyang** [comment]
已经完成了，更新到最新的 commit 就好。

- [快速开始](https://github.com/razonyang/hugo-theme-bootstrap/blob/master/README.zh-CN.md#快速开始)
- Bilibili 对应 key 为 `bilibili`，值为用户 ID。
