### ISSUE TITLE
Dark theme toggler styling does not apply in firefox

### ISSUE THREAD

**Issue by sudipghimire533** [razonyang/hugo-theme-bootstrap#120]

**Comment by razonyang** [comment]
I didn't have such a problem. It works fine in Firefox(89.0.2 Windows).

Could you please provide reproduction steps?

**Comment by sudipghimire533** [comment]
![image](https://user-images.githubusercontent.com/39845901/124925163-e2dff900-e01b-11eb-97fb-46707c64c0bc.png)
Never mind. I was anware that I have old one but yes It was what it's looked like debian-amd64 firefox-esr-78
