### ISSUE TITLE
搜索功能在本地运行没问题，发布在github page 和 云服务器出现故障

### ISSUE THREAD

**Issue by pangwawa** [razonyang/hugo-theme-bootstrap#124]
搜索功能在本地运行是没问题的，

发布在github page 和 云服务器出现故障 ，不停加载

这部分功能需要做特别的配置或者优化吗

> 介意发一下线上网址吗？也可以发到我[邮箱](mailto:razonyang@gmail.com)

**Comment by razonyang** [comment]
介意发一下线上网址吗？也可以发到我[邮箱](mailto:razonyang@gmail.com)

**Comment by pangwawa** [comment]
嗯嗯

**Comment by razonyang** [comment]
我试过了，Windows 下生成的文件，会出现以下错误：

```
Failed to find a valid digest in the 'integrity' attribute for resource '***' with computed SHA-256 integrity '*'. The resource has been blocked.
```

这导致搜索的 JS 脚本无法加载。

估计是 Windows 下换行符的问题，可以尝试以下命令：

```
$ git config --global core.autocrlf true
$ git add --renormalize .
$ git commit -m "Normalize all the line endings"
```

最后重新生成静态发布测试看看。

参阅：https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by pangwawa** [comment]
不是这个原因，修改引入依赖就行了，问题已解决，谢谢老哥

**Comment by razonyang** [comment]
OK，那我就先关闭这个 issue 了
