### ISSUE TITLE
Add codeblock features found in Clarity

### ISSUE THREAD

**Issue by Monklite** [razonyang/hugo-theme-bootstrap#125]
I like the clarity theme, but think this one has more potential and is more customizable. The only thing holding me back is the lack of codeblock options. I would like the following added from the Clarity theme if possible.  

* Rich code block functions including:
    1. Copy to clipboard
    2. Toggle line wrap (dynamic)
    3. Toggle line numbers
    4. Language label
    5. Toggle block expansion/contraction (dynamic)

    To put it all in context, here is a preview showing all functionality.

    ![code block functions](https://raw.githubusercontent.com/chipzoller/hugo-clarity/master/images/syntax-block.gif)

**Comment by Monklite** [comment]
It looks like this would require some big changes to the highlight side of things, how feasible is this in your opinion? I definitely think it would be worth it, the template is otherwise impeccable.

**Comment by razonyang** [comment]
LGTM, but it may take time to implement.

**Comment by razonyang** [comment]
I created a draft PR #139 for this. Please feel free to preview and share your feedback.

If anything are OK, I'll merge into master and draft a new release.

**Comment by Monklite** [comment]
I'm testing it now. First of all, great job. At first I wasn't a fan of the scroll bar and instead preferred the three dots in the bottom left found in Clarity to show more; however, it makes more sense the way you did it. Sometimes someone will like the small form factor without having to expand it so I'd keep that.  

My only question so far is if there is a parameter in the config file that sets a max line count; for example `maxCodeLines = 8` would cap the line count for code blocks to 8 lines unless you auto-expand. I'll check out the commits now to check it out but that would be a nice addition if not already done. I will continue testing. Once again, great work.

**Comment by razonyang** [comment]
No, it's hard code so far. I'm thinking a better way to do it.

**Comment by Monklite** [comment]
That's my only gripe with it. I'm also used to line numbers being off by default, but it doesn't really bother me that they're on by default.

**Comment by razonyang** [comment]
Done. Just added two options `codeBlock.maxLines` and `codeBlock.lineNos`. You can also check out the [feature-code-block-panel](https://github.com/razonyang/hugo-theme-bootstrap/tree/feature-code-block-panel) for testing locally.

**Comment by Monklite** [comment]
> Done. Just added two options `codeBlock.maxLines` and `codeBlock.lineNos`. You can also check out the [feature-code-block-panel](https://github.com/razonyang/hugo-theme-bootstrap/tree/feature-code-block-panel) for testing locally.

I am testing it now and so far so good. I think it's ready, to be honest. Have you tested it too? I assume so lol

**Comment by razonyang** [comment]
@Monklite Yep. I tested before submitting the commit.

**Comment by Monklite** [comment]
I think it's safe to merge it. Thank you for all of your hard work, lots of good stuff this weekend.
