### ISSUE TITLE
Support for non-native color schemes

### ISSUE THREAD

**Issue by Monklite** [razonyang/hugo-theme-bootstrap#126]
Currently, code blocks/fences can only have the syntax highlighted with native themes in Chroma such as Dracula or Monokai. I am trying to make my syntax highlighting conform to the Onedark colors (native Atom theme). Perhaps it's something I missed in documentation, but it doesn't seem too clear to me how to accomplish this.  

The syntax highlighting documentation for hugo is somewhat confusing. I tried [this](https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css) and added a onedark variant of `syntax.css` to the static folder as well as the primary css folder with no luck. Perhaps I have to modify an HTML file to apply it and overwrite the default monokai style?

**Comment by razonyang** [comment]
Firstly, we need to add the `pygmentsUseClasses = true` into your config.

> You will find that the class `chroma` was added into the `pre` tag in the source code.

And then add the generated syntax.css to your page via hooks.

```html
<link rel="stylesheet" href="/css/syntax.css">
```

If you're using this theme, just copy the style to `assets/css/custom.css`.

**Comment by Monklite** [comment]
Oh yeah I tried that, turns out I forgot to set `noClasses = false` for it to take effect. All good now!
