### ISSUE TITLE
如何将scss的目录生成main.css文件

### ISSUE THREAD

**Issue by miaogaolin** [razonyang/hugo-theme-bootstrap#131]
你好，请教作者一个问题。我对前端不是太擅长，先确定一个问题，代码中的main.css文件是不是都是由scss目录下的所有scss文件生成的？
如果是的话，作者是用什么工具实现的？

**Comment by miaogaolin** [comment]
再增加个问题：bootstrap使用哪个版本

**Comment by razonyang** [comment]
> 你好，请教作者一个问题。我对前端不是太擅长，先确定一个问题，代码中的main.css文件是不是都是由scss目录下的所有scss文件生成的？
> 如果是的话，作者是用什么工具实现的？

对的，主要通过 node-sass 生成：

https://github.com/razonyang/hugo-theme-bootstrap/blob/c4880cbc2b2059094720a314c99d4d80ce0197c6/package.json#L55

如果有兴趣编辑样式，还可以看一下 https://github.com/razonyang/hugo-theme-bootstrap#develop

> 再增加个问题：bootstrap使用哪个版本

目前用的是 5.0.2

**Comment by miaogaolin** [comment]
> > 你好，请教作者一个问题。我对前端不是太擅长，先确定一个问题，代码中的main.css文件是不是都是由scss目录下的所有scss文件生成的？
> > 如果是的话，作者是用什么工具实现的？
> 
> 对的，主要通过 node-sass 生成：
> 
> https://github.com/razonyang/hugo-theme-bootstrap/blob/c4880cbc2b2059094720a314c99d4d80ce0197c6/package.json#L55
> 
> 如果有兴趣编辑样式，还可以看一下 https://github.com/razonyang/hugo-theme-bootstrap#develop
> 
> > 再增加个问题：bootstrap使用哪个版本
> 
> 目前用的是 5.0.2
太感谢了

**Comment by razonyang** [comment]
那我先关闭 issue 了
