### ISSUE TITLE
Change all references to titles to title case

### ISSUE THREAD

**Issue by Monklite** [razonyang/hugo-theme-bootstrap#134]
I think it would be good to make all references to titles as title case; for example, if the title of a .md file is "My trip to the beach", it would be displayed just like that as opposed to the title case format of "My Trip to the Beach".  

References to the title should include anything in the `list.html` layout as well as anything on the sidebar such as recent posts and featured. It would also apply to the buttons in the `post.html` that let you navigate forwards and backwards between posts since it displays the title name.  

If you want, I could do a PR and edit the html directly to accommodate this or I could arrange it such that the proposed title case format is dependent on a parameter in the config files so the choice is left to the user. Which would you prefer and is this something you would prefer to do or would you accept this PR?

Thanks!

**Comment by razonyang** [comment]
Sounds good. PR are welcome. I prefer to provide a parameter, disabled by default.

But I have no idea how to name the parameter. I'm looking forward to your PR.

**Comment by Monklite** [comment]
I will just name it `titleCase`. I'll put it under `config.toml` and will disable it by default as you requested.

**Comment by razonyang** [comment]
> I will just name it `titleCase`. I'll put it under `config.toml` and will disable it by default as you requested.

Literally, does `titleCase` have multiple values?

**Comment by Monklite** [comment]
> > I will just name it `titleCase`. I'll put it under `config.toml` and will disable it by default as you requested.
> 
> Literally, does `titleCase` have multiple values? Such as `lowercase` and `uppercase`?

It has [multiple values](https://gohugo.io/getting-started/configuration/#configure-title-case). "Set titleCaseStyle to specify the title style used by the title template function and the automatic section titles in Hugo. It defaults to AP Stylebook for title casing, but you can also set it to Chicago or Go (every word starts with a capital letter)."  

Full uppercase or full lowercase is something that can be done with CSS, I don't think that applies to title case options in Hugo. Does that make sense?

**Comment by Monklite** [comment]
I'll work on the PR now and have it submitted today.

**Comment by razonyang** [comment]
I didn't know the `titleCaseStyle` before,  thanks for letting me know.
I'm looking forward to your submission.

**Comment by Monklite** [comment]
It's almost done; however, I am having a tough time getting it to work properly with bread crumb trails as well as search lists. It seems to work fine for every other list/reference to a title. Do you want me to submit it anyways?

**Comment by razonyang** [comment]
Yep. Thanks for your work, please make a PR, I'll take care of the rest.

**Comment by Monklite** [comment]
> Yep. Thanks for your work, please make a PR, I'll take care of the rest.

Will do in a bit. Check out the breadcrumbs (I modified `breadcrumb.html`) and the search results (did not modify `search.html`

**Comment by razonyang** [comment]
> and the search results (did not modify `search.html`

Kind remind: https://github.com/razonyang/hugo-theme-bootstrap/blob/32bcbee9bc916c9354c72adf09e82923668cfebc/layouts/index.json#L4

Modify this line may help.

**Comment by Monklite** [comment]
Closing due to #136
