### ISSUE TITLE
css and a button (next/previous Post) issue

### ISSUE THREAD

**Issue by khannzxc** [razonyang/hugo-theme-bootstrap#135]
At mobile resolution, the post button appears very large and touch each other, and the copy icon scroll with the code at this post.
https://www.example.com/posts/rich-content/ 
![dellll](https://user-images.githubusercontent.com/40522970/126872303-73827a50-aad1-402f-8661-450c7fca9bdb.JPG)

**Comment by razonyang** [comment]
Don't worry, I'm working on refactoring the copy button.
![image](https://user-images.githubusercontent.com/17720932/126872484-fa88c2d2-a55c-40f8-a9ad-3598101eb1e7.png)

I'll handle those questions ASAP.

**Comment by Monklite** [comment]
> Don't worry, I'm working on refactoring the copy button.
> ![image](https://user-images.githubusercontent.com/17720932/126872484-fa88c2d2-a55c-40f8-a9ad-3598101eb1e7.png)
> 
> I'll handle those questions ASAP.

Those new features look great. Does that rectangular box with the feature buttons appear on hover?

**Comment by razonyang** [comment]
@Monklite Yep, it appears on hover.

**Comment by Monklite** [comment]
> @Monklite Yep, it appears on hover.

Love it. Can't wait for that feature to drop!

**Comment by Siddhantmi** [comment]
I am a beginner, Don't know much about contributing, I have made some changes in CSS have a look
![Screenshot (665)](https://user-images.githubusercontent.com/83053478/126902923-74eb0dc0-be9c-41de-957f-a947c001956c.png)

**Comment by razonyang** [comment]
@Siddhantmi Please follow the section [Develop](https://github.com/razonyang/hugo-theme-bootstrap#develop) for modifying style.

It looks great, you can also share your style here, I'll submit a commit with your credit.

**Comment by Monklite** [comment]
> I am a beginner, Don't know much about contributing, I have made some changes in CSS have a look

Great job!

**Comment by razonyang** [comment]
Fixed by 06267a5, I drafted a new release v0.33.0 about those changes.
Thanks for your feedbacks and help. 🚀
