### ISSUE TITLE
Weird glyphs in search results

### ISSUE THREAD

**Issue by Monklite** [razonyang/hugo-theme-bootstrap#138]
I'm not sure if it's a font issue with my computer or what, but I see these weird glyphs with search results. What am I supposed to be seeing?

![Example](https://i.imgur.com/MIvaYVH.png)

**Comment by razonyang** [comment]
![image](https://user-images.githubusercontent.com/17720932/126882292-13401ba2-2b2c-44ea-8ecc-55ed26972459.png)
It is result's score.

**Comment by Monklite** [comment]
Interesting, seems like a font issue on my end then?

**Comment by razonyang** [comment]
I think that is because your system lack of emoji font? The content is `★★★★★`

**Comment by Monklite** [comment]
I have nerd fonts installed, but not font awesome. I thought all font stuff is usually done on the server side since web servers can often tell browsers to use a specific font/download it. Perhaps I'm wrong, you know a lot lol

**Comment by razonyang** [comment]
Could you please provide details about your device? Such as OS, browser etc.

**Comment by Monklite** [comment]
Arch Linux as OS, Firefox as browser. Using the `ttf-ms-fonts` package for my fonts in Firefox to mimic MS fonts.

Below are my settings:
![Fonts](https://i.imgur.com/X3F8hjR.png)

**Comment by razonyang** [comment]
Haha, I use Arch for working. Please take a look of https://wiki.archlinux.org/title/fonts#Emoji_and_symbols
It may be fixed by installing one of those emoji fonts, such as noto-fonts-emoji.
You will need to restart your browser.

**Comment by Monklite** [comment]
I installed `noto-fonts-emoji`, restarted my browser, and still receive the issue

**Comment by razonyang** [comment]
> I installed `noto-fonts-emoji`, restarted my browser, and still receive the issue.
> 
> It's worth noting that all other glyphs seem to work fine

That is because the content is an emoji symbol, not an awesome font.
I'll check this in my Arch Linux later.

**Comment by Monklite** [comment]
> > I installed `noto-fonts-emoji`, restarted my browser, and still receive the issue.
> > It's worth noting that all other glyphs seem to work fine
> 
> That is because the content is an emoji symbol, not an awesome font.
> I'll check this in my Arch Linux later.

Ahh okay. I'm curious to know why an awesome font didn't work here, I assume you tried this during the initial design but ran into issues, so had to rely on an emoji font

**Comment by razonyang** [comment]
@Monklite Hmm, it seems awesome font is much better.

**Comment by Monklite** [comment]
> @Monklite Hmm, it seems awesome font is much better.

How do you feel about switching it?

**Comment by razonyang** [comment]
Yep. Done. Please take a look at the live demo https://hugo-theme-bootstrap.netlify.app/en/search/?q=markdown

**Comment by Monklite** [comment]
> Yep. Done. Please take a look at the live demo https://hugo-theme-bootstrap.netlify.app/en/search/?q=markdown

Perfect, thank!

**Comment by razonyang** [comment]
That is my pleasure.

**Comment by Monklite** [comment]
> That is my pleasure.

Thanks for all your work today, a lot was done quickly! Very satisfied with the upcoming code features too
