### ISSUE TITLE
Search list results do not respect [post] description parameters

### ISSUE THREAD

**Issue by Monklite** [razonyang/hugo-theme-bootstrap#141]
I use the following in my `params.toml`

```
[post]
excerpt = "description"
excerptMaxLength = 240
```

This works; however, the search results do not respect this behavior while regular lists (such as looking at the home page does).

**Comment by razonyang** [comment]
Oh, I forgot that.

**Comment by razonyang** [comment]
It's not a bug, because the content under the search result title is not the description/summary, it depends on the match keyword returned by Fuse.JS.

![image](https://user-images.githubusercontent.com/17720932/126923555-ef82da8e-0ce1-440d-9287-0860464fcd0f.png)

**Comment by Monklite** [comment]
Okay, can this not be fixed?  

Thanks again

**Comment by razonyang** [comment]
Yes, I tend to stay the same.
