### ISSUE TITLE
动态页面渲染的代码样式如何和markdown渲染的一样？

### ISSUE THREAD

**Issue by miaogaolin** [razonyang/hugo-theme-bootstrap#148]
作者你好，请教个问题

1. 动态页面指的是我的代码块可以编辑
2. 在编辑时如何和markdown中的代码样式保持统一

**Comment by razonyang** [comment]
不是很理解这个问题，能详细说说吗（比如截图等方式）？

**Comment by miaogaolin** [comment]
![image](https://user-images.githubusercontent.com/57740293/127690220-59ac6066-d823-4016-83b8-a2d1c3e7d882.png)
我的页面上可以输入代码，我想应用和markdown生成后一样的代码样式。

**Comment by razonyang** [comment]
这个没有了解过，Hugo 使用 [Chroma](https://github.com/alecthomas/chroma) 进行代码高亮，如果转换是通过 Go 服务端进行的话，应该是可以实现代码样式一致的。

相关链接：

- https://gohugo.io/content-management/syntax-highlighting/

**Comment by miaogaolin** [comment]
> 这个没有了解过，Hugo 使用 [Chroma](https://github.com/alecthomas/chroma) 进行代码高亮，如果转换是通过 Go 服务端进行的话，应该是可以实现代码样式一致的。
> 
> 相关链接：
> 
> * https://gohugo.io/content-management/syntax-highlighting/

那我再查查，你还不睡，夜猫子

**Comment by razonyang** [comment]
一般很晚睡，那我先关闭这个issue了，感觉和主题关系不大。
