### ISSUE TITLE
Different avatar card styles

### ISSUE THREAD

**Issue by Monklite** [razonyang/hugo-theme-bootstrap#149]
Hello,  

I noticed that the avatar/profile card has changed. I like it, though I prefer the smaller form factor and design of the old layout a bit better. Would it be possible to choose between the new style and old one with a site parameter?

**Comment by razonyang** [comment]
Sure, but I have no idea how to name the parameter.

**Comment by Monklite** [comment]
I think `avaterCardStyle` makes sense. To give it more context, just include snippets of each style in the `README`. Does that sound sufficient to you or do you want me to come up with a different name?

**Comment by razonyang** [comment]
Sorry, actually, what I want to ask is how to name the parameter value.

**Comment by Monklite** [comment]
> Sorry, actually, what I want to ask is how to name the parameter value.

I would just use numbers corresponding to a style. The current one can be style 1 and will be the default

**Comment by razonyang** [comment]
@Monklite I created a PR #141. The parameter and its value are defined as follows:

```toml
[params]
  layout = "compact"
```

What do you think?

**Comment by razonyang** [comment]
@Monklite I plan to remove the **about** icon, and then link the profile **name** to the about page.
![image](https://user-images.githubusercontent.com/17720932/127804738-d0e62b79-d40a-4448-ae1f-a6fdf4e39acf.png)

How do you think about it?

**Comment by Monklite** [comment]
> @Monklite I created a PR #141. The parameter and its value are defined as follows:
> 
> ```toml
> [params]
>   layout = "compact"
> ```
> 
> What do you think?

I like it! As for removing the "about" icon, I personally like having it there.

**Comment by razonyang** [comment]
OK, I'll keep the `about` icon.

**Comment by razonyang** [comment]
Fixed by #152
