### ISSUE TITLE
如何使用 CodeMirror ？

### ISSUE THREAD

**Issue by miaogaolin** [razonyang/hugo-theme-bootstrap#150]
这是一个代码编辑器, 这是地址：[https://github.com/codemirror/CodeMirror](https://github.com/codemirror/CodeMirror)

我想通过 npm 包引入，于是看到以下的话：

```
npm install codemirror
```
NOTE: This is the source repository for the library, and not the distribution channel. Cloning it is not the recommended way to install the library, and will in fact not work unless you also run the build step.

看了之后，我不知道如何使用，因为它的库是js和css。

![image](https://user-images.githubusercontent.com/57740293/127730973-1da44593-6505-4dda-924b-ae69311b676c.png)

**Comment by razonyang** [comment]
如果直接修改 src 里面的话，后续会影响到主题的升级。

你也可以通过 customCSS 和 customJS 参数导入的 CSS 和 JS。
路径可以使用 https://www.jsdelivr.com/package/npm/codemirror 或者下载特定版本的 JS CSS 文件到 static 目录即可。

详情可参阅：[自定义资源](https://github.com/razonyang/hugo-theme-bootstrap/blob/master/README.zh-CN.md#自定义资源)

**Comment by razonyang** [comment]
对了，看截图，你用的主题版本，应该是上周的，代码块样式改了不少。
你也可以预览下目前的代码块样式：https://hbs.razonyang.com/en/posts/markdown-syntax/

**Comment by miaogaolin** [comment]
> 对了，看截图，你用的主题版本，应该是上周的，代码块样式改了不少。
> 你也可以预览下目前的代码块样式：https://hbs.razonyang.com/en/posts/markdown-syntax/
谢谢作者，忘了回复了
