### ISSUE TITLE
Option for minimal layout

### ISSUE THREAD

**Issue by Monklite** [razonyang/hugo-theme-bootstrap#151]
For my website, I implemented a minimal layout that removes dates and read time along with navigation and recent posts. This type of layout works nicely for pages such as contact pages where a date, read time, and navigation menu isn't really necessary and makes it feel like any regular posts.  

I'd be happy to open a PR for this. It is specified in the front matter with `type = minimal`. It is done by simply creating a new folder under `/layouts` called `minimal` and tailoring it to remove those things.

Do you feel receptive to this idea? I can get the PR in tonight if you want this.

**Comment by razonyang** [comment]
I think it's possible to remove those elements by page'parameters.
IMO, adding new parameters is easier to maintain than introducing a new layout.
But I'm not sure it meets your needs very well.

**Comment by Monklite** [comment]
> I think it's possible to remove those elements by page's parameters.
> IMO, adding new parameters is easier to maintain than introducing a new layout.
> Does this way meet your needs?

Yeah, that would be fine too. I can do that or you can if you want, I'll test it either way

**Comment by razonyang** [comment]
PR are welcome. 🤝

**Comment by razonyang** [comment]
Fixed by 17934df
