### ISSUE TITLE
启用暗黑模式，怎么让评论的样式也跟着走？

### ISSUE THREAD

**Issue by miaogaolin** [razonyang/hugo-theme-bootstrap#156]
作者你好？请教个问题

我把评论的主题改成github-light了，想启用暗黑模式时评论改成github-dark，有啥办法没？

**Comment by razonyang** [comment]
由于是外部资源，应该没办法控制外部的样式。

不过或许可以重新渲染评论区来达到此目的。

有空我试一下，如果可行，或许会暴露一个参数来实现。

**Comment by miaogaolin** [comment]
OKOK，谢谢了

**Comment by razonyang** [comment]
效果可以在 #158 进行预览，如果没有问题的话，我明天再合并到主分支。

**Comment by miaogaolin** [comment]
可以，牛牛牛

**Comment by razonyang** [comment]
> 可以，牛牛牛

忘记说了，更新后，需要将 theme 改为空或者注释才行。
