### ISSUE TITLE
override default profile avatar

### ISSUE THREAD

**Issue by tglanz** [razonyang/hugo-theme-bootstrap#159]
Hi, I am trying to modifying the avatar path throgh configuration file at "config/author.toml" with no success.

I believe the issue is at the "avatatar.html" partital where we rebing ".Site.Author" to "." (using the with keyword) and then in the actual code, the path is still referenced through ".Site.Author.avatar" instead of just ".avatar".

Same goes for image alt.

Modified (working locally) code looking like
```html
<img class="profile-avatar rounded-circle" src="{{ absURL (default "images/profile.webp" .avatar) }}" alt="{{ .name }}" loading="lazy">
```

Thank you for this great theme!

**Comment by razonyang** [comment]
Fix by f08b5f983173fcbcce911339125563b815b07887

Thanks for reporting this bug.
