### ISSUE TITLE
Security vulnerabilities with the theme

### ISSUE THREAD

**Issue by SQLJames** [razonyang/hugo-theme-bootstrap#166]
Good afternoon, love the theme, however in doing some site testing after bringing it online it looks like there are some security vulnerabilities. 

This can be retested by running your site on [this page](https://webpagetest.org/)
[Results of the test](https://webpagetest.org/result/210820_AiDcC6_b9e881f64c100c4ce59f2f56e2a75e12/)

DATE DISCLOSED | VULNERABLE LIBRARY | VULNERABLE VERSION DETECTED | VULNERABILITY
-- | -- | -- | --
2020/06/11 | H angular | <1.8.0 | Cross-site Scripting (XSS)
2020/06/07 | M angular | <1.8.0 | Cross-site Scripting (XSS)
2020/05/19 | M jquery | <1.9.0 | Cross-site Scripting (XSS)
2020/05/11 | M buefy | <0.8.18 | Cross-site Scripting (XSS)
2020/04/29 | M jquery | >=1.2.0 <3.5.0 | Cross-site Scripting (XSS)
2020/04/28 | M lodash | <4.17.16 | Prototype Pollution
2020/04/13 | M jquery | >=1.0.3 <3.5.0 | Cross-site Scripting (XSS)
2019/07/02 | H lodash | <4.17.12 | Prototype Pollution
2019/02/15 | H lodash | <3.4.1,>=4.0.0 <4.3.1 | Cross-site Scripting (XSS)

**Comment by razonyang** [comment]
This should only be a server configuration problem. We have discussed this in #142, but I forgot to deal with it.

**Comment by razonyang** [comment]
Fixed by ff416fb7e0c1aaa121f9bd16fe69ccca9108de69, it's no need to upgrade the theme, because that is server side problem.
You can verify it again, and you will be need to add those HTTP headers via server configuration(depends on how you host your site).

**Comment by razonyang** [comment]
Btw, the table you posted above is not related to the current tested site.
![image](https://user-images.githubusercontent.com/17720932/130255064-70659135-ee86-4731-a280-155a29db7b67.png)

**Comment by SQLJames** [comment]
Sorry you are right.

**Comment by razonyang** [comment]
@SQLJames Np, thanks for reminding.
