### ISSUE TITLE
Social links and other items have Links to cross-origin destinations that are unsafe

### ISSUE THREAD

**Issue by SQLJames** [razonyang/hugo-theme-bootstrap#179]
In running https://www.dotcom-tools.com/website-speed-test, it was reported that many href anchor tags do not have the `rel="noopener"` or `rel="noreferrer"` attributes. 

More can be read about it here.
https://web.dev/external-anchors-use-rel-noopener/?utm_source=lighthouse&utm_medium=dotcom
these resources all have the `target="_blank"` however, it only needs to have these attributes if it is referencing a different website.
- powered-by.html
- social-links.html
- render-link.html
- nacbar.html
- cc.html
- meta.html 

> Lighthouse uses the following process to identify links as unsafe:
> Gather all <a> tags that contain the target="_blank" attribute but not the rel="noopener" or rel="noreferrer" attributes.
> Filter out any same-host links.
> Because Lighthouse filters out same-host links, there's an edge case you should be aware of if you're working on a large site: if one page contains a target="_blank" link to another page on your site without using rel="noopener", the performance implications of this audit still apply. However, you won't see these links in your Lighthouse results.

**Comment by razonyang** [comment]
Fixed by c99216c4ec99ad3eed0646756a528eed9a5689e0.
Thanks for reporting this issue.
