### ISSUE TITLE
image elements are missing height/width 

### ISSUE THREAD

**Issue by SQLJames** [razonyang/hugo-theme-bootstrap#180]
This page talks about how to dynamically pull the height and width of a file and place it into the html. 
https://kodify.net/hugo/functions/imageconfig-function/
This can cause an issue where your page will adjust on mobile connections/slower internet speeds and can be frustrating for the end user because they will need to scroll to that section again.  This shows with two short videos an example of this happening. https://web.dev/optimize-cls/?utm_source=lighthouse&utm_medium=dotcom#images-without-dimensions

In attempting fix this, I found the profile image did not maintain its shape when adding the height attribute. I am not really good with css, so I am not sure of the problem here, it seems like we are not maintaining the aspect ratio on some of the pictures. 
```
{{- with .Site.Author -}}
{{ $imgPath := "/static/images/profile.webp" }}
{{ if fileExists $imgPath }}
{{ $img := imageConfig $imgPath }}
<img class="profile-avatar rounded-circle" src="{{ absURL (default "images/profile.webp" .avatar) }}" width="{{ $img.Width }}" height="{{ $img.Height }}" alt="{{ .name }}" loading="lazy">
{{- end -}}
{{- end -}}
```

**Comment by razonyang** [comment]
You're right, the profile issue was fixed, the rest are still work in process.

**Comment by razonyang** [comment]
I think this issue has been fixed by the latest commit.
