### ISSUE TITLE
Image elements are missing Alt attributes

### ISSUE THREAD

**Issue by SQLJames** [razonyang/hugo-theme-bootstrap#181]
On the profile and other main pictures, not on posts, it should be easy to just add a generic alt tag, however, I am not sure how we could pass the alt tag to the images for the post. Maybe just use the title of the article and specify "image" after the title?

**Comment by razonyang** [comment]
I think you mean the cover of the post. As you said, I also think that is the right approach.

**Comment by razonyang** [comment]
Fixed by latest commit.
