### ISSUE TITLE
Archive

### ISSUE THREAD

**Issue by razonyang** [razonyang/hugo-theme-bootstrap#19]

**Comment by reatiny** [comment]
你好，我几天在研究博客方面的事，也对比了你和clarity的代码，我不知道怎么在官方clarity上增加归档这个功能，可以指导下我吗，万分感谢。

**Comment by razonyang** [comment]
> 你好，我几天在研究博客方面的事，也对比了你和clarity的代码，我不知道怎么在官方clarity上增加归档这个功能，可以指导下我吗，万分感谢。

可以参考 PR #24 
其中主要是 `layouts/_default/archive.html` 布局模板，还有一个就是添加一个 `archives` 目录，创建 `_index.md`，并指定相关模板即可:
```
+++
title = "归档"
layout = "archive"
+++
```

- 模板 `archive.html` 和目录 `archives` 的名称都可以自定义，只需要指定对应的 `layout` 就好。

**Comment by reatiny** [comment]
好的，你说的这个我是了解的，因为我对前端不是很了解，我把您这边的ayouts/_default/archive.html布局模板搬到我的上的时候，我知道是产生效果了，但是页面是没有显示的，一片空白，我是要修改这个文件的哪里吗

**Comment by razonyang** [comment]
emm，你试试将 archive.html 中的 `{{ define "content" }}` 改成 `{{ define "main" }}` 试试，因为 clarity 定义的嵌套模板名称是 [main](https://github.com/chipzoller/hugo-clarity/blob/311c1e44cca198dc4057a22235716c9aa1c98dd6/layouts/_default/baseof.html#L68).

如果还不行的话，建议将 `archive.html` 改个名字，对应的`layout`也修改一下。另外注意看下控制台又没有错误提示之类的。

**Comment by reatiny** [comment]
hai,改成main就页面就报错了，我估计可能css样式这些没带过去

**Comment by razonyang** [comment]
报错那应该是该对了，模板错误应该和css无关的，建议搜一下是什么错误，然后找下原因就好了。

**Comment by reatiny** [comment]
好的，谢谢啦

**Comment by reatiny** [comment]
十分感谢，居然成功了，点击归档内容可以跳转。只是没有样式，这个需要怎么配置呢

**Comment by razonyang** [comment]
这个就得你修改样式，布局了，我太久没用 clarity 了，只能你自己摸索一下了 😃

**Comment by reatiny** [comment]
好的吧，再次感谢

**Comment by reatiny** [comment]
好的吧，再次感谢
