### ISSUE TITLE
Eliminating render blocking css files

### ISSUE THREAD

**Issue by SQLJames** [razonyang/hugo-theme-bootstrap#191]
In the default head layout partial, the css is just rendered after the html is downloaded, meaning that we will not be able to display any value until the css is downloaded and processed.  Instead, I propose we switch the header to use preload instead of stylesheet.  This has a 93.37% adoption rate for all users. [caniuse.com](https://caniuse.com/?search=preload)

```
<link rel=stylesheet href="{{ $style.Permalink }}" integrity="{{ $style.Data.Integrity }}" crossorigin="anonymous">
```
vs
```
<link rel="preload" href="{{ $style.Permalink }}" integrity="{{ $style.Data.Integrity }}" crossorigin="anonymous" as="style" onload="this.onload=null;this.rel='stylesheet'" >
<noscript><link rel="stylesheet" href="{{ $style.Permalink }}"></noscript>
```

**Comment by razonyang** [comment]
[Fixed by 7ba50cd018c8c0b9efe8893253e26ec9a1b5f23a.

Thank you very much!
