### ISSUE TITLE
Remove fonts from css load

### ISSUE THREAD

**Issue by SQLJames** [razonyang/hugo-theme-bootstrap#195]
Moving the fonts from the critical path when rendering the site will improve site performance.  I believe we can assign the same logic to preload the font instead of putting them at the end of the css file, I will need to dig into this more to confirm.

**Comment by razonyang** [comment]
The new version uses JS+SVG instead of web fonts now.

**Comment by Mecanik** [comment]
> The new version uses JS+SVG instead of web fonts now.

Can you please explain what do you mean by JS+SVG? Thanks.

**Comment by Mecanik** [comment]
> @Mecanik The [Awesome Font JS+SVG](https://fontawesome.com/v5/docs/web/advanced/svg-javascript-core) will replace `<i>` tags with `<svg>` tags. The main purpose is to reduce the size of the bundle, because we only need dozens of icons.

Oh, understood thanks. I thought you were talking about actual web fonts.
