### ISSUE TITLE
There is a problem with the article title

### ISSUE THREAD

**Issue by xuzhijvn** [razonyang/hugo-theme-bootstrap#197]
![image](https://user-images.githubusercontent.com/20964259/131301823-14ba3be6-62e1-4360-be16-5652d5c10316.png)

![image](https://user-images.githubusercontent.com/20964259/131301854-22ea7bd1-7d3c-471c-9e00-8d57bd4825cf.png)

**Comment by razonyang** [comment]
Fixed by 4239fbd, thanks for reporting this issue.
