### ISSUE TITLE
Mermaid

### ISSUE THREAD

**Issue by MarcinKlejna** [razonyang/hugo-theme-bootstrap#201]
Do you plan to add  [Mermaid](https://mermaid-js.github.io/mermaid/#/)?

**Comment by razonyang** [comment]
LGTM

**Comment by razonyang** [comment]
FYI
https://github.com/razonyang/hugo-theme-bootstrap/blob/master/exampleSite/content/en/posts/diagram.md
https://hbs.razonyang.com/en/posts/diagram/
