### ISSUE TITLE
the <img> label missed

### ISSUE THREAD

**Issue by xuzhijvn** [razonyang/hugo-theme-bootstrap#202]
![image](https://user-images.githubusercontent.com/20964259/132079504-a83e8953-8aa1-473b-b8dd-9c6ec8b0e04e.png)

**Comment by razonyang** [comment]
Any HTML tags were omitted by default. You can turn off this by setting the `unsafe` parameter(config.toml):

```
[markup.goldmark.renderer]
unsafe= true
```

**Comment by xuzhijvn** [comment]
> HTML tags were omitted by default. You can turn off this by setting the `unsafe` parameter(config.toml):
> 
> ```
> [markup.goldmark.renderer]
> unsafe= true
> ```

Thanks for the answer.

But, the image will be out of range, when too big.

![image](https://user-images.githubusercontent.com/20964259/132087667-3a5973a8-3f39-4c1b-ac93-f33f70ba3178.png)

**Comment by razonyang** [comment]
@xuzhijvn Fixed by eed4b79
