### ISSUE TITLE
Changing Series Taxonomie

### ISSUE THREAD

**Issue by Alken123** [razonyang/hugo-theme-bootstrap#204]
How to change the series taxonomie to some other when i tried changing it it threw an error i created a new directory named genres and even created a _index.md similar to series but didn't work

**Comment by razonyang** [comment]
You'll need to modify the following configuration:

```
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
```

See also https://gohugo.io/content-management/taxonomies/#configure-taxonomies
