### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute for resource

### ISSUE THREAD

**Issue by Taunl** [razonyang/hugo-theme-bootstrap#209]
when I open "Diagram Guide" page, it don't work.
![image](https://user-images.githubusercontent.com/90607480/133765985-54ed648f-b679-493a-aa58-a14101165939.png)
but I don't change anything of the theme. it work in local site, don't work in web.
![image](https://user-images.githubusercontent.com/90607480/133766283-f203be53-917a-4740-adf5-ebb61c4e294c.png)

**Comment by Taunl** [comment]
I tried it but it didn't work then I tried follows :
```git
$ git config --global core.autocrlf false
$ git add --renormalize .
$ git commit -m "Don't normalize all the line endings"
```
It works. NICE !!! Thank you very much!
----------

The themes is really beautify, I absolutely like it. Because I don't need diagram function, it doesn’t affect my use.
I strongly recommend adding a black theme in light mode.
There is one issue about"Latex" of display. The formula is out of bounds when it is too long to display. I made it work by modifying the "custom.css".
```css
.katex-html{
	overflow:auto; /*latex公式超出浮动*/
	--hbs-accent: gray; /*latex滚动条为灰色*/
}
```
![da95108741be0f45199e75317969033](https://user-images.githubusercontent.com/90607480/134468708-c1615cdb-6caa-44a9-b9b4-d24055503d33.jpg)
.

**Comment by razonyang** [comment]
@Taunl thanks for your feedback, could you please provide the formula above, so that I can reproduce the problem in local?

**Comment by Taunl** [comment]
use follows:
```latex
$$
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
$$
```
you can get
![image](https://user-images.githubusercontent.com/90607480/134524283-4328feb0-95c1-48f7-8dcc-0b5a4743b137.png)

**Comment by razonyang** [comment]
This issue has been fixed in the new UI, you might try it.

**Comment by imattdu** [comment]
> 我认为这可能是因为[line ending](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings)。
> 
> 请执行以下命令，然后重新发布您的站点。
> 
> ```
> $ git config --global core.autocrlf true
> $ git add --renormalize .
> $ git commit -m "Normalize all the line endings"
> ```

我试了好像不行

**Comment by razonyang** [comment]
@imattdu 可以提供详细的环境信息吗？比如操作系统（如Windows，Linux，WSL）及其版本、Hugo 版本等信息，现在缺少足够的信息复现这个问题。

**Comment by imattdu** [comment]
git config --global core.autocrlf true使用这个就可以解决感谢了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Razon ***@***.***&gt;; 
发送时间: 2022年1月20日(星期四) 中午11:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [razonyang/hugo-theme-bootstrap] Failed to find a valid digest in the &#39;integrity&#39; attribute for resource (#209)





 
@imattdu 可以提供详细的环境信息吗？比如操作系统（如Windows，Linux，WSL）及其版本、Hugo 版本等信息，现在缺少足够的信息复现这个问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
