### ISSUE TITLE
URL not always correct

### ISSUE THREAD

**Issue by id027102** [razonyang/hugo-theme-bootstrap#210]
Extract from HTML 
```html
<div class="collapse navbar-collapse" id=navbarSupportedContent>
<ul class="navbar-nav me-1 mb-2 mb-lg-0"><form class="search-bar d-flex ms-1" action=http://localhost:1313/vhus/en/search>
<div class="input-group input-group-sm">
<button class="btn btn-search disabled position-absolute left-0" type=submit aria-label=submit><i class="fas fa-fw fa-search"></i></button>
<input class="form-control rounded-pill" id=searchQuery name=q type=search aria-label=Search>
</div>
</form></ul><ul class="navbar-nav me-1 mb-2 mb-lg-0 me-1 ms-auto"><li class=nav-item>
<a class=nav-link href=http://localhost:1313/en/archives/ target=_blank rel="noopener noreferrer">
<i class="fas fa-fw fa-file-archive"></i>Archives
</a>
</li><li class=nav-item>
<a class=nav-link href=http://localhost:1313/en/categories/ target=_blank rel="noopener noreferrer">
<i class="fas fa-fw fa-folder"></i>Categories
```
When using a subdomain , in the nav-bar , URLs are not correct for archives,categories,tags and series,
Good URL : http://localhost:1313/vhus/en/search
Bad URL : http://localhost:1313/en/archives/ missing **/vhus** between  "1313" and "/en"
Can somebody help ?
Thanks

**Comment by razonyang** [comment]
Please try to modify the `baseURL` configuration:

```toml
baseURL = http://localhost:1313/vhus/
```

> Note that, there are two positions of `baseURL`: config/_default/config.toml and the config/production/config.toml

**Comment by id027102** [comment]
I have a little debug and found 
The problem has nothing to do with production or not.
The problem is located in layouts/partials/header/navbar.html on line 43, you put href=" {{ $url }}"....
I found 3 variables 
|Name|Value with subdomain|Value without subdomain|
|-------|-----|-----|
|$baseURL|https://localhost:1313/subdomain/|https://localhost:1313/|
| .URL|/en/archives|/en/archives|
| $url|https://localhost:1313/en/archives|https://localhost:1313/en/archives|

So with or without subdomain $url have always the same value and lead to error 404.

So : in line 43 replacing {{ $url }} by {{$baseURL}}{{.URL}}solve the  problem.
If you had put a subdomain on ypour site to test  ....

**Comment by razonyang** [comment]
@id027102  you're right.  I'll fix it later.

**Comment by id027102** [comment]
Have put new version of theme theme : no change 
When using subdomain , subdomain disappear in menu-bar links 
Have : http://localhost:1313/en/.... i.s.o.  http://localhost:1313/<em>subdomain</em>/en/...
Back to previous version of theme.
Not really tested ?
But making more difficult to trace . (navbar.html replaced by ???)

**Comment by razonyang** [comment]
Hmm... am I missing something?

> **navbar.html** was renamed to **index.html**

https://user-images.githubusercontent.com/17720932/135424261-df2c4653-4ec8-4a52-ba9a-6fa41a102f37.mp4

**Comment by razonyang** [comment]
One possible reason is that your menu link prefix by a leading slash `/`.
| | Output |
|:---|:---|
| {{ absURL "/menu" }} | http://localhost:1313/menu 
| {{ absURL "menu" }} |  http://localhost:1313/foo/menu

**Comment by id027102** [comment]
Ok , I found :
I have now to set canonifyurls to false i.s.o. true,
Before there were also problems with canonifyurls set to false (not sure anymore which)
Something need canonifyurls to true , other need false ?????
Very difficult to find a theme fully working .
I let canonifyurls false for now , until the other problems occurs again.
Thanks for your time.
