### ISSUE TITLE
The default navbar-toggler-icon' resolution is so LOW

### ISSUE THREAD

**Issue by Chengyuan-artist** [razonyang/hugo-theme-bootstrap#214]
![image](https://user-images.githubusercontent.com/56594167/134012785-d61eaea0-6446-4857-8c99-f11cca5aaa29.png)

How can I change it to something like a svg?
Thanks!

**Comment by razonyang** [comment]
It can be overridden by saving your icon as `/static/images/icons/menu.png`.

But this icon has been removed by #215, please feel free to use the new UI.
