### ISSUE TITLE
Resize images

### ISSUE THREAD

**Issue by razonyang** [razonyang/hugo-theme-bootstrap#216]
### Discussed in https://github.com/razonyang/hugo-theme-bootstrap/discussions/212

**Comment by jehoshua7** [comment]
@razonyang - thank you

**Comment by razonyang** [comment]
Usage:

```
![foo](/images/bar.png?width=120px&height=60px)
```

**Comment by jehoshua7** [comment]
@razonyang - Thank you, that works peffectly.  :)
