### ISSUE TITLE
Bootstrap button color styles don't work

### ISSUE THREAD

**Issue by stessaris** [razonyang/hugo-theme-bootstrap#220]
If you add a BS styled button (e.g. btn-danger) the CSS "covers" its color by applying the current theme color. To reproduce the problem just create a new site by following the instructions in [README](https://github.com/razonyang/hugo-theme-bootstrap#create-a-new-site-from-scratch) and then create a hook with a button:

```
$ mkdir -p layouts/partials/hooks
$ echo '<button type="button" class="btn btn-danger">Content Begin</button>' >layouts/partials/hooks/content-begin.html
```

The button should be red because of the `btn-danger` class, but the background is overridden by the color of the current palette (the border is still red):

<img width="709" alt="Screenshot 2021-09-24 at 14 07 36" src="https://user-images.githubusercontent.com/39191293/134671877-0fe6d798-db90-4ced-866e-4936db5397e0.png">

Moreover, there's a nasty interaction with hoovering; when the mouse is over the button the color reverts to the original red:

![Screen Recording 2021-09-24 at 14 12 02](https://user-images.githubusercontent.com/39191293/134672642-0a7b9e2e-ae97-40a5-a277-f9cef7eab49f.gif)

Unfortunately I don't know much about CSS and the internals of your code to understand where's the problem, but the culprit could be in https://github.com/razonyang/hugo-theme-bootstrap/blob/eed4b79b970961f2163d6506a4253f893f8dd1fa/src/scss/_main.scss#L45-L52

**Comment by razonyang** [comment]
This theme overrides the bootstrap button style. I'll separate theme and Bootstrap styles in the next UI design(#215 WIP).
