### ISSUE TITLE
q: howto make one post the homepage

### ISSUE THREAD

**Issue by hanscees** [razonyang/hugo-theme-bootstrap#230]
Hi,

I am new to hugo, so I hope the question isnt too newbie. But I want the website to open with the latest post always. 

so for instance my post
http://192.168.0.74:1313/en/posts/econrevolt-first/

Is there a way to do that please? 

thanks

**Comment by razonyang** [comment]
It requires customizing **home.html**, I'll test it locally, and then provide some code snippets for you later.

**Comment by razonyang** [comment]
You'll need to update the theme to the latest commit, and then create a layout in your **root path** and save as **layouts/index.html**.
```html
{{ define "content" }}
<div class="col-lg-8">
  <div class="container">
    {{- partial "breadcrumb" . -}}
    {{- $sections := default (slice "posts") .Site.Params.mainSections -}}
    {{- $post := index (first 1 (where .Site.RegularPages "Type" "in" $sections)) 0 -}}
    {{- partial "post" $post -}}
  </div>
</div>
{{- partial "sidebar" . -}}
{{ end }}
```

**Comment by hanscees** [comment]
I updated the theme. 
Then do I just do 
vi  layouts/index.html
and paste your code, or do I also need to do something like
hugo new \_index.html
?

**Comment by hanscees** [comment]
yes, it works. Some polishing to do, but its life

https://www.econrevolt.com

**Comment by Mecanik** [comment]
> 

Unfortunately this now fails with the latest version as:

```
Start building sites …
hugo v0.99.1-d524067382e60ce2a2248c3133a1b3af206b6ef1+extended windows/amd64 BuildDate=2022-05-18T11:18:14Z VendorInfo=gohugoio
WARNING: calling IsSet with unsupported type "bool" (bool) will always return false.
WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.
Error: Error building site: failed to render pages: render of "home" failed: "...\hugo-theme-bootstrap-skeleton\layouts\index.html:8:8": execute of template failed: template: index.html:8:8: executing "content" at <partial "post" $post>: error calling partial: "...\hugo_cache\modules\filecache\modules\pkg\mod\github.com\razonyang\hugo-theme-bootstrap@v0.77.1\layouts\partials\post.html:25:4": execute of template failed: template: partials/post.html:25:4: executing "partials/post.html" at <partial "post/related-posts" .>: error calling partial: "....\hugo_cache\modules\filecache\modules\pkg\mod\github.com\razonyang\hugo-theme-bootstrap@v0.77.1\layouts\partials\post\related-posts.html:2:21": execute of template failed: template: partials/post/related-posts.html:2:21: executing "partials/post/related-posts.html" at <where (.Site.RegularPages.Related .) "Section" "in" .Site.Params.mainSections>: error calling where: can't iterate over <nil>
Built in 3465 ms
```

**Comment by razonyang** [comment]
@Mecanik It works after replacing the `{{- partial "post" $post -}}` with: 

```html
{{- with $post }}
    {{- partial "post" . -}}
{{- end }}
```

**Comment by Mecanik** [comment]
> 

Thank you! I`m a complete noob using Hugo. Currently rebuilding my personal blog to get rid of the nasty WP.

The sheer amount of work you input with this ready to use template is amazing, I`m very impressed in how you optimized assets to bundle them into one and other things. I will sponsor your work soon.
