### ISSUE TITLE
Error building site

### ISSUE THREAD

**Issue by lakshya111** [razonyang/hugo-theme-bootstrap#231]
**Error: Error building site: logged 9 error(s)**
Hi, when I try to build the site as per installation instructions, I face this error. 

![Screenshot from 2021-10-05 21-45-46](https://user-images.githubusercontent.com/29180173/136062938-f801d3b7-13bd-42b0-99c7-55205b5b57e9.png)

**Comment by razonyang** [comment]
I can't reproduce this issue, what version do you use?

```shell
hugo version
```

![image](https://user-images.githubusercontent.com/17720932/136078258-70d413b1-93d1-4d99-b233-45dc0b1cb4a4.png)

**Comment by lakshya111** [comment]
Hi, 
This issues was with Hugo v0.40.1, now I have updated to Hugo v0.88.1 and the site is building.

Thank you.
