### ISSUE TITLE
Copyright in posts change

### ISSUE THREAD

**Issue by AnonymousDebug** [razonyang/hugo-theme-bootstrap#232]
Hey!
So I wanted to change the copyright button which appears on the right of every post (like in the about post) to show the MIT license, I wanted to license it under the MIT license instead of the creative commons license.

Please help me!

**Comment by razonyang** [comment]
Sorry for the late reply.

There is no good solution so far, but it still can be fixed by overriding the **copyright** partial:

```shell
$ mkdir -p layouts/partials/post/panel
$ touch layouts/partials/post/panel/copyright.html
```

```shell
// layouts/partials/post/panel/copyright.html
<a class="action" data-bs-container="body" data-bs-toggle="popover" data-bs-html="true" data-bs-placement="bottom"
  data-bs-trigger="focus" tabindex="0" type="button" aria-label="Copyright" 
  data-bs-content="MIT LICENSE">
  <i class="fas fa-fw fa-copyright"></i>
</a>
```

And then restart the Hugo server for previewing.

**Comment by razonyang** [comment]
I created two hooks for customizing panel actions, which called **post-panel-begin** and **post-panel-end**.

Now you can solve it by creating a hook:

```html
// layouts/partials/hooks/post-panel-end.html
<a class="action" data-bs-container="body" data-bs-toggle="popover" data-bs-html="true" data-bs-placement="bottom"
  data-bs-trigger="focus" tabindex="0" type="button" aria-label="Copyright" 
  data-bs-content="MIT LICENSE">
  <i class="fas fa-fw fa-copyright"></i>
</a>
```

> This feature was introduced by the latest commit, you'll need to upgrade the theme.

**Comment by AnonymousDebug** [comment]
Hey!

Thank you for the reply,
After doing what you said in the first comment, it did show MIT Licence but it is showing the path above the button as shown down below.
![sss](https://user-images.githubusercontent.com/76240678/137624144-2513769f-886d-412d-ab77-0ab3a9912da9.png)

I was trying to do what you said in the second comment so I looked at the upgrade guide for your theme, but when I tried to fetch the repo `git fetch`, it said that it isn't a repo, the directory is inside another repo (my own repo).

**Comment by AnonymousDebug** [comment]
I removed the comment and it was changed but still messed up, but then I upgraded the theme again but this time by the method listed on your repo as the theme directory has info about the repo now, it is fine now.

Thanks alot for this theme and helping me!

**Comment by AnonymousDebug** [comment]
> Kind remind: the second solution is recommended, please delete the `layouts/partials/post/panel/copyright.html` of first solution.

I did this and it shows the creative commons license again, should I add it back? Will it affect my site negatively?

**Comment by AnonymousDebug** [comment]
This is my repo: https://gitlab.com/AnonymousDebug/cyborgstation-website

**Comment by AnonymousDebug** [comment]
Website: [CyborgStation](www.cyborgstation.tk)

**Comment by razonyang** [comment]
I took a close look at the source code, found that the theme does not upgrade to the latest version yet.
Please try to upgrade the theme as the [instructions](https://github.com/razonyang/hugo-theme-bootstrap#upgrade) shown.

**Comment by AnonymousDebug** [comment]
After the `git add themes/hugo-theme-bootstrap`, when I try to commit it says:

`On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean`

**Comment by razonyang** [comment]
I fork your repo and make some changes, https://gitlab.com/razonyang/cyborgstation-website, it works fine now.

**Comment by AnonymousDebug** [comment]
> I fork your repo and make some changes, https://gitlab.com/razonyang/cyborgstation-website, it works fine now.

Thanks once again, mind making a merge request?

**Comment by razonyang** [comment]
Np.

**Comment by AnonymousDebug** [comment]
> I fork your repo and make some changes, https://gitlab.com/razonyang/cyborgstation-website, it works fine now.

I cloned your repo and tried it locally, blank white screen is shown and I get this error message in the console 
![sss](https://user-images.githubusercontent.com/76240678/137627200-fcc93f86-6630-43c3-841b-876ce25c6e21.png)

**Comment by AnonymousDebug** [comment]
To merge from your repo, pipline needs to run successfully but I am blocked from gitlab pipeline. I invited you to be a maintainer.

**Comment by razonyang** [comment]
Hmm, it is a matter of taste.  Which one do you like?

> BTW, style won't harm your site.

![image](https://user-images.githubusercontent.com/17720932/137633693-3f1ef8e1-3a26-4281-99f4-93cb12a62604.png)

![image](https://user-images.githubusercontent.com/17720932/137633701-af39dd1c-449e-451f-8564-2ac9ade13306.png)

**Comment by AnonymousDebug** [comment]
> Hmm, it is a matter of taste. Which one do you like?
> 
> > BTW, style won't harm your site.
> 
> ![image](https://user-images.githubusercontent.com/17720932/137633693-3f1ef8e1-3a26-4281-99f4-93cb12a62604.png)
> 
> ![image](https://user-images.githubusercontent.com/17720932/137633701-af39dd1c-449e-451f-8564-2ac9ade13306.png)

Tbh, none of those.
I would like em both if they were INSIDE the box, but they are half in and half out and that triggers me a bit lol.

So that means that I can switch to the previous revision if it wont harm my site, right?

**Comment by AnonymousDebug** [comment]
> Yep, you can customize it via **assets/css/custom.css**:
> 
> ```css
> .post-panel {
>     right: -.35rem!important;
>     box-shadow: none!important;
>     border-radius: 0!important;
> }
> 
> .post-panel .action {
>     border-bottom: none!important;
>     padding: 0!important;
> }
> ```

Copyright button was like: Aight, I amma head out.

**Comment by AnonymousDebug** [comment]
Did it, thanks!
