### ISSUE TITLE
Profile picture shown in page gallery

### ISSUE THREAD

**Issue by simgunz** [razonyang/hugo-theme-bootstrap#251]
**Describe the bug**
The profile picture from the top right about section is shown in the image gallery of a page.

**To Reproduce**
1. Go to a page containing images
2. Click on an image
3. Click right until the last image

**Expected behavior**
The author profile picture is not in the image gallery

**Screenshots**
![Screenshot_20211030_083723](https://user-images.githubusercontent.com/466270/139523204-1d9f853b-20f2-44d3-9884-5623d3810539.jpg)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Chrome

**Comment by razonyang** [comment]
Fixed by the latest commit.
