### ISSUE TITLE
Cannot use icons

### ISSUE THREAD

**Issue by remon-hobbel** [razonyang/hugo-theme-bootstrap#268]
https://github.com/razonyang/hugo-theme-bootstrap/blob/dc606f048b0f00e9a6ca017dae49f26496deaf7f/src/js/fonts.js#L1

I'm referring to a custom icon for the [[main]] menu in config/_default/menu.toml as:

`pre = '<i class="fab fa-fw fa-certificate"></i>'`

However, all I see is a blinking error from FontAwesome. I can only use a few icons that are declared in the theme. A lot of the icons are not even working. Is there anything wrong?

**Comment by razonyang** [comment]
See #259

**Comment by razonyang** [comment]
In short, you can figure it out by setting the `customJS` parameter:

```toml
customJS = [
  "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/js/all.min.js" # Full icons set.
  # "https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.4/js/solid.js" # Solid icons.
  # ...
]
```
