### ISSUE TITLE
在手机上，两边留空的位置有点太大了，手机屏幕空间利用的不是很到位

### ISSUE THREAD

**Issue by kasusa** [razonyang/hugo-theme-bootstrap#269]
**Describe the bug**
在手机上，两边留空的位置有点太大了，手机屏幕空间利用的不是很到位。

**To Reproduce**
使用任何手机打开博客页面。

文章是有padding的，然后外面又有很大一圈的阴影，还有一个比较大的margin，导致手机上看博文的话，就是细长条一个，文字内容读起来并不舒适。
解决方案的话，我认为可以在手机上时添加一条规则取消掉文章的margin，只保留内部的padding，（padding最好也缩小点）。
详细的话，可以参考github的做法。blogger的做法也是可以的，可能他们并不会真的多显示多少文字，但是看起来就不会两边很空旷。

**Comment by razonyang** [comment]
已经做了点修改，以下是预览网址，你看下如何：
https://develop.hbs.razonyang.com

这个会在PWA完成之后，再统一合并。

**Comment by kasusa** [comment]
我感觉可以把文章主题div的margin都删掉，但是不要把padding弄少啊，看着不美观了

Razon Yang ***@***.***> 于 2021年11月22日周一 下午2:22写道：

**Comment by razonyang** [comment]
margin 去掉感觉太帖边界了，目前回调了 padding，和缩小了 margin，如果你想要在手机端去掉 margin 可以在 `assets/css/custom.css` 加几行 CSS：

```css
@media (max-width: 576px) { 
    .row {
        --hbs-gutter-x: 0;
    }
}
```
