### ISSUE TITLE
Firefox Stylesheets

### ISSUE THREAD

**Issue by SimpleAnecdote** [razonyang/hugo-theme-bootstrap#271]
**Describe the bug**
When I load the website on Firefox 78.0.2 64-bit on Ubuntu, I get the website stripped of most of the CSS. I haven't tested other browsers yet because I just got stuck on that. I've detailed the issue and suggested a fix below which works for me.

**To Reproduce**
1. Go to your website on Firefox, i.e. [https://hbs.razonyang.com/en/](https://hbs.razonyang.com/en/)
2. Alternatively, simply clone the repository, serve with `hugo server`, and navigate to [http://localhost:1313](http://localhost:1313)

**Expected behavior**
For the CSS to load properly.

**Screenshots**
![2021-11-19_20-39](https://user-images.githubusercontent.com/1707719/142688956-9feb3597-c881-4fcb-8a84-6603938ee030.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: 78.0.2 (64-bit)

**Additional context**
After a little googling I've found the following links, which all lead me to think Firefox simply has not implemented this `rel="preload"` feature the same as Chrome. It seems in the MDN examples that you need to `<link rel="preload" ...>` and then explicitly reference with another `<link rel="stylesheet" ...>`. From testing it seems changing with javascript the `rel` attribute on page load, i.e. `onload="this.rel=stylesheet"` does **not** work:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload
- https://github.com/mdn/html-examples/blob/master/link-rel-preload/js-and-css/index.html
- https://stackoverflow.com/questions/45321043/preload-css-file-not-supported-on-firefox-and-safari-mac

**Suggested fix**
Edit `layouts/partials/assets/css.html`:
- Remove the `onload=".."` attribute from `<link rel="preload" ...>`
- Remove the `<noscript>` and `</noscript>` tags from before and after the `<link rel="stylesheet" ...>`

I tested this on my instance by simply overriding the `layouts/partials/assets/css.html` file in my project with the exact same content of the theme's file and the changes prescribed above and it works quite well. Doesn't seem to be throwing up any issues on Chrome.

I believe this is related to #213 and was misidentified there. The testing at the time was possibly being affected by the FF version (as I understand they've changed the implementation of this a couple of times).

**Comment by MarcinKlejna** [comment]
I have a 64bit firefox and it runs on linux without any problems 
* OS Debian
* Browser: Firefox
* Version 91.3.0esr (64 bity)

**Comment by SimpleAnecdote** [comment]
@MarcinKlejna Thank you for double checking me (dziekuje)! I just tested on another machine with an up-to-date Firefox installation (v94.0) and the issue does not exist there. So definitely a Firefox version issue that's no longer a problem.
