### ISSUE TITLE
Cumulative Layout Shift need imrovment

### ISSUE THREAD

**Issue by itechf-s** [razonyang/hugo-theme-bootstrap#272]
**Describe the bug**
Core Web Vitals - Cumulative Layout Shift is very high

**To Reproduce**
1. Go to https://hbs.razonyang.com/en/
2. Copy home page
3. [Open Google Page Speed](https://pagespeed.web.dev/)
4. paste URL and click Analyze
5. See The Report

**Expected behavior**
recommended Cumulative Layout Shift would be 0.05

**Screenshots**
![ScreenShot](https://img.gkgud.com/2021/11/Screenshot%20from%202021-11-20%2016-29-02.png)

**Comment by razonyang** [comment]
I'll focus on this after implement the PWA #262

**Comment by razonyang** [comment]
Fixed by #276
![image](https://user-images.githubusercontent.com/17720932/143001115-ebe9b17f-957a-4b84-b7a7-548838d10b69.png)

**Comment by itechf-s** [comment]
Thank you so much for fixing this issue.
