### ISSUE TITLE
 image has no src or srcset attribute

### ISSUE THREAD

**Issue by SQLJames** [razonyang/hugo-theme-bootstrap#281]
**Describe the bug**
During the upgrade to the latest release which was for performance improvements and removing render blocking resources. It seems like images were changed to data-src instead of just src in the html. This is causing errors when validating my site through the htmlproofer container. I temporarily removed this validation from my pipeline to work around this issue. 

**To Reproduce**
1. Go to homepage
2. view the source of the website
3. find the images on the html code notice that they don't have a src tag.

**Expected behavior**
Expected the images to have a src tag.

**Additional context**
`htmlproofer ./public --http-status-ignore "999" --allow-hash-href --disable_external`
The docker image I am using to run this test https://hub.docker.com/r/18fgsa/html-proofer/

**Comment by razonyang** [comment]
Yep. It is in order to load an image on demand, instead of loading all the images at once.

https://user-images.githubusercontent.com/17720932/143561621-a08bc645-877b-43f9-bfd9-cd9a34d8a3a2.mp4

**Comment by SQLJames** [comment]
It does look like this works for loading images but it doesn't appear to be valid per html standards. This article talks about this issue more. I'm not sure how this would affect content shifts on page loads using a smaller image or performance.
https://stackoverflow.com/questions/41533464/loading-an-image-using-data-src-and-not-just-src

In digging through, could we try doing the loading="lazy" attribute mentioned on the web.dev site?

https://web.dev/lazy-loading-images/

**Comment by razonyang** [comment]
Didn't know that, thanks for the resource link, I'll test it tonight.

**Comment by SQLJames** [comment]
Appreciate the eyes and ears looking into it.

**Comment by razonyang** [comment]
Fixed by #282, thanks for pointing it out.
