### ISSUE TITLE
Maintenance Page

### ISSUE THREAD

**Issue by AnonymousDebug** [razonyang/hugo-theme-bootstrap#290]
Hey,

~~I have a maintenance HTML page and I want to redirect the user to it, I tried putting it in the content directory and removing everything else from there but it doesn't seem to work, but is accesible by going to https://www.mywebsite.com/maintenance.html. I want to user to go to https://www.mywebsite.com/ and see the maintenance page, how can I do this?~~
Also I want a custom HTML page to be accessible without adding a .html extension in the address bar, can this be possible by symlinking it? or any other way?

**Comment by razonyang** [comment]
Yep, you can do it in Hugo way.

## Layout

First of all, you need to create a layout and save it as `layouts/_default/maintenance.html`.

```HTML
{{ define "content" }}
<div class="col error text-center my-4">
  <div class="error-icon mb-4"><i class="fas fa-5x fa-fw fa-exclamation-triangle"></i></div>
  <h1 class="error-title mb-4">Under Maintenance</h1>
  <div class="mb-4 error-info text-muted">We'll be back soon.</div>
  <div class="mb-4 error-actions">
    <a class="error-action btn btn-sm btn-outline-primary" href="{{ absLangURL "/" }}">
      <i class="fas fa-fw fa-home"></i>{{ i18n "home" }}
    </a>
    <a class="error-action btn btn-sm btn-outline-primary" href="javascript: window.history.back();">
      <i class="fas fa-fw fa-arrow-left"></i>{{ i18n "go_back" }}
    </a>
  </div>
</div>
{{ end }}
````

## Page

And then create a page called `maintenance/index.md` in `content` directory with the following content:

```toml
+++
layout = 'maintenance'
+++
```

> The name of layout must be same as the layout we created above.

Now your page is landing on  https://www.example.com/maintenance.

**Comment by AnonymousDebug** [comment]
Thanks alot!
It worked as expected.
