### ISSUE TITLE
Avatar details (company, earth, about, contact us) overlaps card border

### ISSUE THREAD

**Issue by Monklite** [razonyang/hugo-theme-bootstrap#296]
**Describe the bug**
The compact avatar layout now has a new bug. Having the company and location details enabled makes the links overlap the border. I personally do not use these, but others might.

**To Reproduce**
Open a browser with standard resolution (take up the entire screen), enable the compact avatar layout, and the overlap should be there. 

**Expected behavior**
These details should not overlap the border. Perhaps company/earth can go on top if enabled and the about/contact us links can be right below it. If disabled, it will just be about/contact us

**Screenshots**
https://i.imgur.com/KpH91GM.jpg

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Firefox
 - Version 94

P.S. Thanks for fixing the initial reported bug in #294, all looks good other than this. Appreciate it!

**Comment by razonyang** [comment]
Thanks for reporting this, It seems that only Firefox has this problem.

**Comment by Monklite** [comment]
> Thanks for reporting this, It seems that only Firefox has this problem.

Hello,

I just tested on Chromium and it looks like you are correct. I've only tested those two, but it works exactly as how I described it should in Chrome so I do suppose there will be some tweak needed for Firefox to have the same behavior.

Thanks!

**Comment by razonyang** [comment]
Thanks.

**Comment by razonyang** [comment]
I didn't look closely. It should be fixed by latest commit.
