### ISSUE TITLE
Always one pinned post even when disabled

### ISSUE THREAD

**Issue by Monklite** [razonyang/hugo-theme-bootstrap#298]
**Describe the bug**
If `pinnedPost = false`, nothing changes with pinned posts. I still always see one pinned post even when I set `pinnedPostCount = 0` but the first setting should disable them completely.

**To Reproduce**
1. Set `pinnedPost` to false
2. See if anything changed, which should be nothing for now
3. Set `pinnedPostCount` to 0
4. See if one post is still pinned, there should be one.

**Expected behavior**
When `pinnedPost` is set to false, there should be no pinned posts.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Firefox
 - Version 94

**Comment by razonyang** [comment]
Thanks a lot, I just found that the parameter `pinnedPost` is just documented, not be implemented yet.
