### ISSUE TITLE
0.56: error calling Concat: slice []interface {} not supported in concat

### ISSUE THREAD

**Issue by chrisrummel** [razonyang/hugo-theme-bootstrap#303]
**Describe the bug**
Starting with 0.56 I am getting errors when building my site:

**To Reproduce**
I removed all changes in my layout- and assets-folders to make sure it isn't related to any of my changes.
Then: type "hugo" and wait.

**Expected behavior**
I would expect hugo to finish building my site and print a report.

**Screenshots**
hugo v0.90.0-DD0D3FDB+extended linux/amd64 BuildDate=2021-12-08T09:33:47Z VendorInfo=gohugoio
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:27:8: executing "_default/single.html" at <partial "body-end" .>: error calling partial: execute of template failed: template: partials/body-end.html:2:4: executing "partials/body-end.html" at <partial "assets/icons/js" .>: error calling partial: "/www/staging/hugo/themes/hugo-theme-bootstrap/layouts/partials/assets/icons/js.html:4:35": execute of template failed: template: partials/assets/icons/js.html:4:35: executing "partials/assets/icons/js.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat

**Commandline**
 - OS: Ubuntu 16.04.7 LTS
 - Hugo: 0.90
 - Bootstrap: 0.56

**Comment by razonyang** [comment]
Thanks for reporting this issue. Fixed by the latest version `v0.57.0`

**Comment by chrisrummel** [comment]
Thanks!
