### ISSUE TITLE
Palette buttons not auto-scaling to amount of palette colors set in theme

### ISSUE THREAD

**Issue by Monklite** [razonyang/hugo-theme-bootstrap#308]
**Describe the bug**
By default, all colors are available in the palette. If you limit it to just a few, they do not scale out to fill out the blank space like they did in prior versions (which could have been unintentional back in those days).

**To Reproduce**
1. Go into 'params.toml' and limit the palette selection
2. Go to the palette selection on the website
3. Notice how the missing space from the omitted palette colors is not filled in by scaling out the defined palette colors

**Expected behavior**
When palette limitations are in place, they should scale out to fill in the missing space that results from missing palette colors

**Screenshots**
Here is how it used to look for me with palette limitations:
![Old](https://i.imgur.com/QYsO4JR.jpg)

Here is how it looks now:
![New](https://i.imgur.com/TMsrg24.jpg)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Firefox
 - Version 95

**Comment by razonyang** [comment]
Fixed by e829681f51b8f63fdabb5d4390f3735949f2e7cf
