### ISSUE TITLE
Section sidebar

### ISSUE THREAD

**Issue by sagarbehere** [razonyang/hugo-theme-bootstrap#314]
This is an awesome theme. I'd like to request a feature that would make this theme even more useful for two use cases

1. Project documentation
2. Making a "digital garden"

Both use cases require the same underlying mechanisms, most of which are already present in this theme. The main missing element is a section sidebar, which is described in this feature request.

Consider a folder like `content/docs` or `content/notes`. Inside this folder there can be any number of files `foo.md`, `bar.md` etc. It may also contain other folders inside of which could be more files and folders etc.

Then, when the user navigates to e.g. `https://example.com/docs` or `https://example.com/notes` there will be a page with three columns. The rightmost column will be the existing sidebar with its widgets like recent(ly updated) posts, tags, categories etc. The middle column will be the main content of the documentation or note page. **The leftmost column, which is what this feature request is about, will be a sidebar that has the recursive listing, or tree-view,  of all the files under `content/docs` or `content/notes`.** See image below, as an example.

![sidebar-example](https://user-images.githubusercontent.com/1622959/147421846-1567e867-f16d-4e7a-bbb5-ad86cf7e3880.png)

## Features

1. **The contents of this sidebar should be automatically created at site build time**, based on the contents of the `content/docs` or `content/notes` folder. There should be no need to manually specify them.
2. If the sidebar list items have children, those items could be expanded or collapsed (with little arrows next to them which can be clicked to show their children. In the image above, such arrows are next to items like 'Getting Started', 'Core Tasks', 'Tutorials', 'Reference'). There could be a config option to have the list expanded/collapsed by default.
3. Would be good to have the option to specify the "depth of the tree view" in the sidebar. For example, if the depth is 4, then the sidebar would show e.g. all the files and folders up to `notes/topic/sub-topic/sub-sub-topic`, but nothing under `sub-sub-topic`.
4. If there are a LOT of files/folders, then the sidebar contents could be somehow cached if it'll affect build or site loading time. (The Hugo Docsy theme mentioned in the section below does this.)
5. The options described in the section 'Section Menu' of [this Docsy documentation page](https://www.docsy.dev/docs/adding-content/navigation/#section-menu) (UI options, icons, ability to add manual links and to prevent certain pages from appearing in the menu)
6. Mobile friendly. Invisible by default on mobile, but slides in from the side when a menu is touched. See last example in the section below. 

## Similar projects/examples for inspiration

Documentation projects

1. Hugo's [docsy theme](https://www.docsy.dev/docs/) has _exactly_ this feature. [ So we know that doing this is possible :) ]
2. [Material theme for MkDocs](https://squidfunk.github.io/mkdocs-material/getting-started/) has a similar sidebar. MkDocs is a Python project.

Digital garden projects

1. [Everything I know](https://wiki.nikitavoloboev.xyz/) is a really nice digital garden with a very beautiful left sidebar. It is created with GitBook
2. [My second-brain](https://garden.anthonyamar.fr/Welcome+in+my+mind+%F0%9F%A7%A0) is another example, created with Obsidian Publish. It also has a nice sidebar to the left. This example also shows how the sidebar should be when viewed with a mobile phone: Invisible by default, but slides in from the left when a “hamburger menu” is touched.  

## Questions?

I'd be happy to brainstorm ideas about how this feature should work or could be improved or to provide additional clarification :-)

**Comment by razonyang** [comment]
Sounds good. But it won't  be implemented quickly, since there are a lot of work need to do, such as separate CSS from the `blog` and `docs` sections, in order to avoid increasing the sizes of assets.

I'll make a simple implementation this week.

**Comment by sagarbehere** [comment]
Great! In case it helps, here are some links I found which may explain how to create some of the pieces of the solution

## Hugo - creating a recursive listing for a section

- https://discourse.gohugo.io/t/create-a-structured-content-listing-all-pages-recursively-by-section/31711
    - The accepted answer by jmooring looks good
- https://gist.github.com/myobie/00c1c51b18dde80b078e93ff06be17ed
- https://discourse.gohugo.io/t/list-all-pages-below-subsection/27418
    - The accepted Solution looks useful
- https://discourse.gohugo.io/t/how-to-list-all-pages-in-a-section-but-not-the-index-page/8441
    - I think we should render the index page (or have that as a config option). If specific indeed pages need not be rendered, that can be handled through that page’s front matter. 
- https://az.id.au/dev/hugo-recursive-templates/

## Bootstrap 5 sidebar

- https://dev.to/codeply/bootstrap-5-sidebar-examples-38pb
    - see last example for “push” sidebar
- https://getbootstrap.com/docs/5.0/examples/sidebars/
    - official examples
- https://bootstrapious.com/p/bootstrap-sidebar
    - Check out example 2. But this is for bootstrap 4, not 5. 

## Hugo partial caching

- https://www.regisphilibert.com/blog/2019/12/hugo-partial-series-part-1-caching-with-partialcached/
- https://gohugo.io/functions/partialcached/

**Comment by razonyang** [comment]
@sagarbehere Thanks for the code snippets and examples. I'll get around to implement it on this weekend.

**Comment by sagarbehere** [comment]
@razonyang just wondering if you’ve made any progress on this? I’d be happy to test any work-in-progress and provide feedback, if that will help.

**Comment by razonyang** [comment]
@sagarbehere Sorry for the late reply, I'm a bit busy recently, just created a simple version(#324).

**Comment by sagarbehere** [comment]
@razonyang I just checked out #324 and it's a really great start! Here are some thoughts on possible next steps

1. I wonder if it would be possible to show the hierarchy in the sidebar. For example, the screenshot below shows the hierarchy of some content as the output of the tree command on the left and the way it currently appears in the sidebar on the right.

![sidebar01](https://user-images.githubusercontent.com/1622959/148492939-40062dc6-8091-44b7-82da-6bf2ad2d684c.png)

As you can see, the sidebar only shows a flat list of Titles, with no indication of the hierarchy. It'd be cool if the side bar initially shows just 'Digital Garden' and 'Reference' with a little arrow next to 'Reference'. Clicking that arrow would then show 'Computers' below 'Reference' but a bit indented, and with a little arrow next to it. Then clicking on 'Computers' would show 'Setup' and 'Tips' etc. As an example, see the sidebar on this page on a computer screen: https://wiki.selfhosted.show/ and see how you can navigate to 'Home Automation' --> 'Home Assistant' --> 'Stats Monitoring' --> 'Unraid api configuration' etc. (By the way, that site's sidebar does something pretty clever when the viewport becomes narrow e.g. on mobile screens. It slides in from the right when a hamburger icon is pressed and instead of showing the entire hierarchy, it only shows the hierarchy's children with a 'back' arrow button at the top to navigate back up the hierarchy. Check it out. Would be cool to have such behavior).

2. If you look at the hierarchy to the left in the screenshot above, you'll see that the folder named 'setup' contains a file named _index.md (which has some content). So I was thinking: If a folder has a file named _index.md (with the name of the folder as its title in the frontmatter) then the folder name in the sidebar would be a hyperlink and clicking on it would show the contents of _index.md followed by the list of child-pages and child-folders in that folder. But if there is no _index.md file, then the folder name in the sidebar would not be a hyperlink. Clicking on it would not be possible.. it would only be possible to click on it (or the arrow next to it) to display its children in the sidebar.

3. Right now, in mobile view (or narrow viewports) the sidebar essentially becomes a button named 'Catalog' at the top, clicking on which shows the entire sidebar contents. This is awkward, because it'll require a lot of vertical scrolling when there are a lot of items in the sidebar. Would it be possible to have the sidebar in narrow viewports to slide in from the left when a >> button is pressed? An examples is on this site https://garden.anthonyamar.fr/Welcome+in+my+mind+%F0%9F%A7%A0 where clicking a hamburger menu icon on the top left makes the entire sidebar menu slide in from the left. Clicking anywhere outside that sidebar menu makes it disappear.

4. Having the ToC in the right sidebar is perfect. Would it be possible to just make a right-sidebar-toc widget as a partial that could be included in the sidebar templates in `layouts/docs` ? Then, additional widgets could also be added to the right-sidebar (like: Recently added/updated notes, or a list of backlinks etc.). Such a right-sidebar-toc widget could also be reused outside of the docs section. For example, I have some longer blog posts and would love to have the ToC in the right sidebar for those blog posts.

Thank you very much for considering these points.

**Comment by razonyang** [comment]
1. It has been implemented already([example](https://develop.hbs.razonyang.com/en/docs/widgets/author/)), you'll need to create `_index.md` in the `reference`, `computers` directories, so that those directories can be treated as [Section](https://gohugo.io/content-management/sections/) by Hugo.

I have thought about that sidebar behavior on the small screen, but it seems to conflict with the top app bar menu. We need to discuss this further.

![image](https://user-images.githubusercontent.com/17720932/148498648-7dde984c-8877-431c-8d85-f8ceb9020826.png)

2. As I mentioned above, `_index.md` is required.

3. Yep, it's temporary, because we have such a button on the small screen already(as the above image shown). We need to find a better way to do it. How about putting the button on the panel?

4. Np.

**Comment by razonyang** [comment]
I made some changes:

**1. Moved catalog(left sidebar) button to the top app bar on small screen:**

![image](https://user-images.githubusercontent.com/17720932/148526829-5121d9a3-961f-4ff4-b686-55f7d8a5e630.png)

**2. Created hooks: `docs/sidebar-begin` and `docs/sidebar-end`.**

Those hooks allow appending any widgets you wish on the right sidebar. It can also get rid of overriding `partials/docs/sidebar.html`.

```html
// layouts/partials/hooks/docs/sidebar-begin.html

{{ partial "sidebar/recent-posts" . }}
{{ partial "sidebar/featured-posts" . }}
```

**3. Changed catalog style**

Please feel free to test it in local or preview it [online](https://develop.hbs.razonyang.com/en/docs/getting-started/).

> Since I rebased `master` changes onto `develop`, so that you may not able to pull the `develop` branch directly.

**Comment by sagarbehere** [comment]
@razonyang This is wonderful progress. Thank you for being so responsive. I'll take a look over the weekend at how the hierarchy in the sidebar works. Meanwhile, here are some quick comments based on looking at the [online](https://develop.hbs.razonyang.com/en/docs/getting-started/) link.

1. The new style of the sidebar/catalog is really nice. Especially, expanding the Level 1 --> Level 2 --> Level 3 shows the visual hierarchy of the levels very clearly. Nice! (This lack of clear hierarchy visualization is a problem with many other solutions, but you have avoided that)

2. There seems to be a bug in the arrow icons for expanding/collapsing the sidebar hierarchies. When the page loads, the sidebar is collapsed and the arrow points to the right ➔, which is correct. Then, when you click on the link to expand the hierarchy, e.g. click on the 'Widgets' then the hierarchy expands and the arrow changes to pointing downwards ↓. That is also correct. BUT, when you again click on the 'Widgets' to collapse the hierarchy, the hierarchy collapses correctly, but the arrow continues pointing downwards. That's not correct. It should once again point to the right when the hierarchy is collapsed. I've basically not found a way to make a downward arrow point to the right again. I think this may be a bug.
3. Regarding moving the catalog (left sidebar) button to the top bar on a small screen: I think your solution works.. but it looks a bit weird because the button is to the right of the top bar. Of course, you have done this because there already exists the ☰ menu button to the left of the top bar. Maybe a cleaner solution would be to move the ☰ menu button to the center of the top bar on smaller screens, instead of keeping it on the left. This way, on smaller screens, the catalog button could be on the left, the ☰ menu button would be in the center, and the ⋮menu button would be on the right. Keeping the ☰ menu icon at the center of the top bar is how many other themes do it. For example, the popular GeneratePress theme for Wordpress does that. See how the menu button appears on smaller screens for this site: https://sagar.se
4. On smaller screens, the left sidebar/catalog menu still appears to "drop down from the top" instead of "moving in from the left"  (as shown on this site: https://garden.anthonyamar.fr/Welcome+in+my+mind+%F0%9F%A7%A0 See it on a small screen). To see why this "moving in from the left" is better, you can do a simple experiment. Visit the [online](https://develop.hbs.razonyang.com/en/docs/getting-started/) link on a small screen and scroll down to the bottom of the page. Then click the catalog button on the sticky top bar. The dropped down sidebar catalog menu will actually not be visible. Instead you'll just notice that the page scrolls up a little. In fact, unless you are at the top of the page, clicking the catalog button does not result in a visible sidebar menu. The menu has indeed "dropped down" but it is not visible unless you are at the top of the page.

**Comment by razonyang** [comment]
The arrow icon is a known issue #318.

As for the button position, I would prefer to keep the original menu button on the left, and the `⋮` setting button on the right.
Because of moving the catalog button to the left, which make the top app bar become inconsistent between `docs` and `posts` layout. The top bar should be consistent, no matter what layout it is, in order to avoid confusing users.

In my opinion, there are two places to put it.
![image](https://user-images.githubusercontent.com/17720932/148636646-3df0d0b1-5bea-49f1-b1c9-a9d8c85bbb4c.png)

As for the last point, I'll improve it after deciding the position of catalog button.

**Comment by razonyang** [comment]
The arrow icon issue has been fixed by f803aaf22778fbb0e806491f59117cb04bf0140c, you can preview it on the [test](https://develop.hbs.razonyang.com/en/docs/level-1/level-2/level-3/level-4/) or [FAQs](https://develop.hbs.razonyang.com/en/faq/) page.

I just noticed that you've sponsored this project, thanks for very much.

**Comment by sagarbehere** [comment]
The floating button on the left would be perfect. That way, it is in a natural position to replace the disappeared catalog sidebar. Also, from that position, it’d feel natural for the sidebar to “move in from the left” when the button is pressed. 

I think putting it in the posts panel is not ideal. This is because if someone decides to remove the  posts panel (some users of the theme have done that) because the other buttons in it are not needed for their use case, they won’t be able to do so if the still want to have the catalog button. And in that case, they may remove everything except the catalog button from the posts panel, which will leave the catalog button in the panel in an odd position on the page.

**Comment by sagarbehere** [comment]
@razonyang I just played with the sidebar after adding _index.md to each folder. You are correct! After adding _index.md, the hierarchy appears in the sidebar and everything looks good. See the screenshot below which shows how the file/folder structure is, and how it appears in the sidebar

![hierarchical-sidebar](https://user-images.githubusercontent.com/1622959/148669535-1803c0b4-9e3c-445e-aa2a-60e032befdf2.png)

Here are some potential improvements

1. It would be useful to also have a list template for `docs/`. Right now, there is only a single.html. If you navigate to http://example.com/docs , the left sidebar does not show up and the contents of the right sidebar are the default widgets that exist for other parts of the site. It would be good if the list template for `docs/` had the left sidebar/catalog and the right sidebar could be an empty ToC and whatever widgets the user adds for the docs section
2. The list template for docs (actually, for other sections too, not just the docs) could be improved such that the content of _index.md appears first, followed by the usual summary list of pages. That way, if there is a folder `content/docs/foo` with files `foo01.md`, `foo02.md`, and `foo03.md` inside, and `content/docs/foo/_index.md` contains the text, "This section is about foo. Please look at `foo01.md` to know more about foo01" etc., then navigating to http://example.com/docs/foo will show that text first, followed by the summary pages of foo01.md, foo02.md, and foo03.md. I actually managed to get this working by modifying `layout/partials/list.html` as follows: After the line `{{- partial "breadcrumb" . -}} I added
```
   {{- if gt (len .Content) 0 -}}
      <div class="row card post component">
        <div class="card-body">
          {{- .Content -}}
        </div>
      </div>
    {{- end -}}
```
I don't know if there is a better way to do this, but this works for including the content of any _index.md at the top of the corresponding list page. Perhaps this could be added to the official code of the template? Another example of why this is useful is that when the user clicks on a tag/category in the sidebar widget and navigates to the list page for that tag/category, it would be possible to write a bit about that tag/category in e.g. `content/categories/category-name/_index.md` and that content would appear first when visiting http://example.com/categories/category-name/ , followed by the usual summary list of pages in that category.
3. Right now, if you click on e.g. 'Tips' or 'Setup' in the sidebar shown in the screenshot above, that will only expand/collapse the hierarchy. It would be good if those are also hyperlinks to the corresponding list pages e.g. 'Setup' is also a hyperlink to http://example.com/docs/reference/computers/setup and clicking on 'Setup' takes you to that page, in addition to expanding/collapsing the hierarchy in the sidebar. Right now, http://example.com/docs/reference/computers/setup already exists (it lists the summaries of the files in that folder).. but the 'Setup' item in the sidebar does not hyperlink to that page. With that working, and combined with point 2 above, one can write some content in `docs/reference/computers/setup/_index.md` and that will be visible when the `Setup` in the left sidebar/catalog is clicked.
4. Would be good to include breadcrumbs in the single and list template files for `docs/`. Right now, the breadcrumbs are missing.
5. Would it be possible to sort the entries in the catalog sidebar, at any particular level in the hierarchy, in alphabetical order? Right now, it seems that the contents under the Computers hierarchy in the screenshot above are in reverse alphabetical order (Wordpress is first, followed by Tips, Setup, and Rclone. The sequence would be reversed if it was alphabetical ordering). I'm not really sure how the contents under 'Tips' are ordered - it does not seem to be alphabetical (forward or reverse). 
6. Could there be an option to customize the `{{ partial "sidebar/recent-posts" . }}` so that the recent posts are only from the current section? That way, the recent posts widget in `docs/` would only show the recent posts in the docs section. Similarly, the recent posts widget for the blog section would only show recent blog posts, not recent docs. And on the landing page, if necessary, the recent posts widget could show the recent posts from _all_ sections of the site.
7. I did both `git pull` as well as `git fetch` in both the master and develop branches and then switched to develop branch (I don't know much about git, but hoped that these commands would get me all your latest changes). This seems to have worked, but I am unable to see the catalog sidebar button in the top bar on smaller screensizes, similar to the image you posted. In my case, on smaller screens, the catalog disappears and the button to show it is .. nowhere. Did I make a mistake in updating my local git copy? Or did you remove the code to make the catalog button appear in the top bar? In any case, I hope you will consider making the catalog sidebar button floating on the left as you showed in the image in your post above.

**Comment by razonyang** [comment]
1. Moved the catalog toggle button to the left side.
2. Added `list.html`.
3. Added breadcrumb to list and single pages.
4. You can sort the section and pages by setting `weight` parameter in front matter.
5. I'm not sure that, but `git pull origin develop` works in most case. If it is not working, you can remove the `themes/hugo-theme-bootstrap`, and re clone and then checkout develop branch, for ensuring you're using the latest commit.

Since this issue contains too many requests, it's hard to track the progress and feedback of each request. So I recommend splitting requests into each issue.

There are some requests I saw:

- Linkable section, split section title and toggle button.
- Filter recent posts by current layout.

If there is any request I missed, please create an issue per request.

**Comment by sagarbehere** [comment]
> Linkable section, split section title and toggle button.
> Filter recent posts by current layout.

Yes, those are the two remaining requests. If I think of something else, I'll create a separate issue.

I also checked the behavior of the catalog menu on a smaller screen and noticed a bug. I created a separate issue for it as #329 

Finally, regarding
> You can sort the section and pages by setting weight parameter in front matter.

I understand that using the weight parameter in front matter is the preferred way to sort the section and pages with Hugo. However, I think that only works well for menus with a small number of pages/sections. In this case, for docs/notes, imagine having 1000 existing notes/pages. Now, the weight parameter would need to be manually added to the front matter of each note. Then, when you write another note, you again need to think of where its position needs to be and add appropriate weight parameter.. and then maybe change the weight parameters of many other pages, if the new note needs to be somewhere in the middle of the list. All this could be avoided if the contents of the catalog sidebar are ordered alphabetically. Would it be possible to get the best of both possibilities? Maybe sort by weight first.. but for those pages that have the same weight, or have no weight parameter at all, sort them alphabetically? This way, those who want to explicitly specify weights will get their sidebar entries sorted by weight. Those who don't want to specify a weight parameter for every page will simply get an alphabetically sorted list. What do you think?

**Comment by razonyang** [comment]
It makes sense, I also created #330, #331 and @332 for those features.

**Comment by sagarbehere** [comment]
Nice! Then we can probably close this issue as Done.
