### ISSUE TITLE
Add a "Read more ..." link to post summaries

### ISSUE THREAD

**Issue by sagarbehere** [razonyang/hugo-theme-bootstrap#316]
Currently, list pages display a summary of posts. It is not obvious if there is more content to read beyond the summary. This can be fixed by adding a "Read more ..." link at the bottom of a post summary, in case there is additional content in the post that is not shown in the summary. The link can point to the post's single page.

After playing around a bit, I get this desired feature by adding the following code to the end of `layouts/partials/post/excerpt.html`

```
{{- if or .Truncated .Description -}}
  <div>
    <a href="{{ .RelPermalink }}">Read More...</a>
  </div>
{{- end -}}
```
Could this be added to the code of the official theme template? I am sure others will find this useful.

Note that I am not sure about the `.Description` in the IF condition in the code above. It seems that if the summary is created from the description field of the frontmatter, instead of truncating the post content, then .Truncated may return false. To avoid that, I added `.Description` in the IF condition, assuming that code is the correct way to say "If the content has been truncated OR if the summary is generated from the description front matter field, then.." . See more here

https://github.com/gohugoio/hugo/issues/6252

**Comment by razonyang** [comment]
The `description` option was introduced by #140.

I decided to use the second parameter of `truncate` function for doing this.
