### ISSUE TITLE
Palette not working?

### ISSUE THREAD

**Issue by zwoop** [razonyang/hugo-theme-bootstrap#317]
I've tried to modify the default palette color, but no matter what I do, it seems to default to "blue" always. I've made the following two changes ton my .toml:

```
palette = "pink" # Default palette. Optional.
palettes = ["pink", "blue", "red", "green"] # Available palettes. Default to ALL.
```

The second works, and limits the palette chooser to just those colors. But the default palette does not seem to take effect.

**Comment by razonyang** [comment]
The default palette(`blue`) will be stored in `localStorage`(browser side) when you visit your site, in order to remember the choice of users. So that modify the configuration is not enough, until the user cleans up the browser cache.

**Comment by iamsuk** [comment]
I'm having the exactly same issue.  
Deleted localStorage/browser cache/cookies and all the things but still it's not working.  
So I added `document.body.parentElement.setAttribute("data-palette", "pink");` onto assets/js/custom.js (which is a custom javascript file) manually, as can be seen in theme/hugo-theme-bootstrap/assets/bootstrap/template.js.

**Comment by iamsuk** [comment]
To my understanding,  this issue comes from themes/hugo-theme-bootstrap/layout/_default/baseof.html not setting data-palette attribute to <html> tag. 
One can simply fix this issue by appending data-palette like this: 
```html
<!-- baseof.html -->
<!doctype html>
{{- $color := $.Site.Params.color -}}
{{- $palette := $.Site.Params.palette -}}
<html lang="{{ .Lang }}"  data-palette="{{ $palette }}"
  {{ if in (slice "light" "dark") $color }}{{ printf " data-mode=\"%s\"" $color | safeHTMLAttr }}{{ end }}>
  ....
```

**Comment by razonyang** [comment]
@iamsuk Thanks a lot.
