### ISSUE TITLE
Catalog sidebar not visible after scrolling on small screens

### ISSUE THREAD

**Issue by sagarbehere** [razonyang/hugo-theme-bootstrap#329]
**Describe the bug**

1. The catalog sidebar is not visible on small screens when you i. Visit a page ii. Scroll down the page iii. Press the catalog sidebar floating button to the left. After doing this, the catalog sidebar apparently does "move in from the left".. but it is at the top of the page and not visible. Scrolling also does not work when the sidebar has moved in from the left, so it is difficult to scroll up to see the catalog sidebar. See the gif below
2. Arrows of the catalog sidebar end up overlapping the "close sidebar" button. See the end of the gif below

See gif below

![peek_rs](https://user-images.githubusercontent.com/1622959/148722879-4e967ac4-76b4-438f-a652-ca3d5ede197b.gif)

**To Reproduce**
1. Go to https://develop.hbs.razonyang.com/en/docs/image-processing/ on a very small screen (just resize the browser window to be very narrow)
2. Scroll towards the bottom of the page
3. Click the "show catalog sidebar" button that is floating to the left of the page
4. See error: The sidebar will apparently "move in from the left" but the catalog won't be visible unless the page is somehow scrolled to the top (e.g. by pressing the return to top button. The mouse scroll wheel does not work)
5. Also, notice that the arrows to expand/collapse the catalog items overlap with the "close sidebar" button.

**Expected behavior**
1. The sidebar moves in from the left and is visible and can be scrolled. See the gif below as a good example of expected behavior (from [this website](https://garden.anthonyamar.fr/Welcome+in+my+mind+%F0%9F%A7%A0) )

![expected](https://user-images.githubusercontent.com/1622959/148722958-3712cced-5341-489e-a80e-2507f50226cd.gif)

2. The arrows to expand/collapse the list item hierarchies do not overlap with the close sidebar button, so that they can be easily clicked on smaller screens.

**Comment by razonyang** [comment]
It looks strange, would you please provide the browser you use? I can't reproduce the issue in Chrome and Firefox.

**Comment by razonyang** [comment]
I changed the style, I've tested in Chrome and Firefox. Please feel free to test it and submit your feedback.

https://user-images.githubusercontent.com/17720932/148805394-829ddebc-c7d7-4567-9ba9-742d1d0ee4b1.mp4

The GIF you posted above looks strange, if there is the same issue on the current implementation, please provide the browser details(such as brand, version, OS), so that I can reproduce it. I recommend clearing the browser cache before testing.

BTW, I think all the important requests(except the backlinks, still in discussing) have been implemented. So I'll draft a new release for those changes, if there is no issue. I look forward to your feedback.

**Comment by sagarbehere** [comment]
Hi @razonyang, thank you for the quick updates. I played with the updated version and discovered where the issue appears. The issue is described below and shown in the GIF further below

1. Everything looks good and works as expected on a large screen/window.
2. Everything looks good and works as expected on a very small screen/window. It looks like the video you posted above. (I even tried this on an iPhone. It works.)
3. When the screen/window is a bit bigger than 'very small' but smaller than 'regular desktop size' then the problem appears. With the updated version, the behavior is
    1. Pressing the sidebar catalog button causes scrolling up to where the catalog sidebar is
    2. Scrolling is not possible. If the catalog sidebar is longer than the window size, it is not possible to scroll and see all the sidebar contents
    3. The "show catalog sidebar" button's visual appearance and position seems stuck. It looks exactly the way it did _before_ I clicked it to make the sidebar appear. Clicking on it one more time makes the sidebar disappear.

Here is the GIF

![catalog-sidebar-rs](https://user-images.githubusercontent.com/1622959/148826751-c41db2aa-047b-45d4-ac7c-70deda6bfa0d.gif)

I have tested this and seen the exact same behavior on 
1. Firefox 94.0 (64-bit) "Mozilla Firefox for Ubuntu canonical -1.0" on Linux Pop OS (which is based on Ubuntu 21.04).
2. Chrome Version 96.0.4664.93 (Official Build) (64-bit) on the same Linux Pop OS
3. The same chrome version as above on MacOS Big Sur
4. Brave version 1.32.115 based on Chromium 96.0.4664.93 (Official Build) (x86_64) on MacOS Big Sur
5. Safari 15.1 (17612.2.9.1.20) on MacOS Big Sur

I don't think this could be related to the browser cache because this happened on various browsers on MacOS too, and I had not opened the site on MacOS earlier. Please let me know if you are able to recreate/see this issue on your computer.

And yes, once the above issue is fixed I agree that all the important requests have been implemented and a new release can be drafted. If you wish, I'd be happy to write a documentation post for this theme's docs that describes the new template features for `content/docs`, why those features exist, and how to use them. I could write this as a markdown file and email it to you (am not familiar enough with coding/git/github to create a pull request. But if you can tell me how (or point me to some tutorials) I can try making a pull request too. Please let me know if you'd like me to help with the documentation :-)

**Comment by razonyang** [comment]
Oops, I forgot the medium screen totally, it only works on small(`sm`) and large(`lg`) screen. Now the catalog behavior on medium screen is same as small screen. I think this issue has been fixed.

**Comment by sagarbehere** [comment]
@razonyang Thank you. Now it seems to work well for all screen sizes.

**Comment by razonyang** [comment]
I drafted a new release `v0.63.0`, thanks for your feedback and help.

It would be great if you're willing to write some documentations. Here are instructions for creating a PR if you want to contribute documentation to this project.

- `Fork` this repository.
- Clone the fork repo: `git clone https://github.com/sagarbehere/hugo-theme-bootstrap`.
- Go to the `exampleSite` folder: `cd exampleSite`.
- Write post: `hugo new --themesDir=../../ docs/foo/index.md`
- Preview the post: `hugo server --themesDir=../../`
- Commit files: `git add content/docs/foo/index.md` and `git commit -m 'docs: create page: docs/foo'`
- Push to remote: `git push origin master`
- And then navigate to https://github.com/sagarbehere/hugo-theme-bootstrap, GitHub probably shows a button to create pull request.
