### ISSUE TITLE
Sidebar widget in docs/ layout scrolls over ToC

### ISSUE THREAD

**Issue by sagarbehere** [razonyang/hugo-theme-bootstrap#333]
**Describe the bug**
I added `{{ partial "sidebar/recent-posts" . }}` to `layouts/partials/hooks/docs/sidebar-end.html` in order to get a Recent Posts widget below the Table of Contents in the right sidebar, as suggested [here](https://github.com/razonyang/hugo-theme-bootstrap/issues/314#issuecomment-1007286395).

When scrolling the page, the Recent Posts widget scrolls right over the top of the "stick" ToC widget. See the GIF below

![taxonomy-widget-scroll-rs](https://user-images.githubusercontent.com/1622959/148851586-fb7b66dd-7084-41de-979f-76661e19ee18.gif)

**Expected behavior**
A sidebar widget should not scroll over another widget. A simple fix could be to make all sidebar widgets "sticky" in the `docs` layout. Alternatively, the ToC widget could be made "not sticky" but I think having a sticky ToC widget is nicer for the docs layout. 

Any of these two solutions would be better than the existing behavior. Happy to hear other solution ideas if you have any.

**Comment by razonyang** [comment]
Done. The sidebar is sticky now.

**Comment by sagarbehere** [comment]
Thank you. This is working well now.
