### ISSUE TITLE
No RSS link in social-links

### ISSUE THREAD

**Issue by c20d-us** [razonyang/hugo-theme-bootstrap#334]
**Describe the bug**
The RSS link and icon do not show up in the social-links section, either in the sidebar profile or page footer.

**To Reproduce**
1. Create a new Hugo site
2. Place hugo-bootstrap-theme v0.62.1 theme folder in themes directory, copy in example site
3. Run hugo server

**Expected behavior**
The RSS link and icon should display.

**Hugo version:**
hugo v0.91.2-1798BD3F darwin/amd64 BuildDate=2021-12-23T15:33:34Z VendorInfo=gohugoio

**Desktop (please complete the following information):**
 - OS: MacOS 12.0.1
 - Browser Chrome
 - Version 97.0.4692.71

**Additional context**
The issue seems to be in the ./layouts/partials/helpers/social-links.html helper trying to get the .OutputFormats variable when it is not in scope. If .OutputFormats is passed to the partial within the dict (e.g. "OutputFormats" $.OutputFormats in the partial call), all works as expected.

./layouts/partials/helpers/social-links.html is called by:
    ./layouts/partials/footer/social-links.html
    ./layouts/partials/sidebar/profile/meta.html

**Comment by razonyang** [comment]
You're right. I didn't notice that, thanks for your feedback.
