### ISSUE TITLE
archive-layout has no sidebar

### ISSUE THREAD

**Issue by chrisrummel** [razonyang/hugo-theme-bootstrap#336]
**Describe the bug**
I noticed that all content features the sidebar with one exception: the archive-layout.

**To Reproduce**
1. Go to [Archives](https://hbs.razonyang.com/en/archives/)
2. Go to any other page like [Categories](https://hbs.razonyang.com/en/categories/)

**Expected behavior**
Since layout "archive" is the only layout without the sidebar, I am not sure if this is intentional. I think it would be logical, if the layout would be consistant for all layouts.

**Hugo version:**
```shell
$ hugo version
hugo v0.91.2-1798BD3F+extended linux/amd64 BuildDate=2021-12-23T15:33:34Z VendorInfo=gohugoio
```

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any

**Comment by razonyang** [comment]
Yep, it's intentional. But it may be good to have a sidebar.

**Comment by razonyang** [comment]
Added by f10e77c
