### ISSUE TITLE
Docs catalog doesn't work well on large screen

### ISSUE THREAD

**Issue by razonyang** [razonyang/hugo-theme-bootstrap#338]
**Describe the bug**

Docs catalog prevents body from scrolling on a large screen.

https://user-images.githubusercontent.com/17720932/149281500-696a8fdd-1ef9-449f-bc38-4f0ba2d7b666.mp4

**Comment by razonyang** [comment]
@sagarbehere There is an important bug fix, I think should let you know.

**Comment by sagarbehere** [comment]
@razonyang thank you for noticing this and for informing me (else I wouldn’t have noticed this). I’ll subscribe to issues in this repository so that I get notifications about issues in future.
