### ISSUE TITLE
Improvements to post summaries

### ISSUE THREAD

**Issue by sagarbehere** [razonyang/hugo-theme-bootstrap#341]
**Is your feature request related to a problem? Please describe.**
1. If `excerpt = "description"` is set in `params.toml` then **every** post **must** have a `description` variable in its frontmatter, which will be shown as the post summary in a list page. If there is no `description` variable in the frontmatter, or if `description = ""`, then nothing is shown in the post summary in the list pages.
2. If `excerpt = "description"` is not set, then the theme uses `.Summary` as the post summary. If the post contains `<!--more-->` then .Summary has all the post content up to `<!--more-->`and includes all the formatting of that content. However, if there is no `<!--more-->` then Hugo uses by default the first 70 words of the post as the summary (see this [this documentation page](https://gohugo.io/content-management/summaries/)).. HOWEVER, in that case Hugo does something weird: It removes from the .Summary all HTML elements/images as well as all markdown formatting from those first 70 words (it does not do that when constructing a summary in the presence of `<!--more-->`. Apparently, this is by design. See bep's response to [this post](https://discourse.gohugo.io/t/markdown-content-renders-as-regular-text-in-summary/1396)). This is a problem for posts where `<!--more-->` is not present **and** the markdown formatting needs to be preserved in the summary that Hugo automatically generates from the first 70 words. [The default of 70 words can be configured by `summaryLength` variable in Hugo configs. Therefore, not sure what the `$maxLength` and `$.Site.Params.post.excerptMaxLength` do in `layouts/partials/post/excerpt.html` unless `$maxLength` < `summaryLength`. But anyway...]

**Describe the solution you'd like**
1. It would be great to have logic where the post summary contains the content of the description variable in the front matter IF `excerpt = "description"` is sent in the config AND the `description` variable in the frontmatter is not empty. But if the `description` variable IS empty, then the summary can be `.Summary`. That way, authors can choose what the content of their post summaries should be. If they are happy with Hugo's .Summary, they leave the `description` frontmatter variable blank. But if they want a special summary for a particular post, they can simply add it as the value of the `description` variable in the frontmatter. This avoids the existing situation where if they want a special summary only for a particular post and not other posts.. well, it isn't possible.
2. I don't really understand why Hugo removes HTML/images/formatting etc. when automatically generating a summary from the first 70 (or `summaryLength`) words of the post. It becomes a problem for posts that start with an image followed by very few words, and the image as well as words are desired to be in the post summary (see [this site](https://sagar.se/category/microblog/page/2/), which I'm trying to migrate to Hugo, as an example. The list page shows an image followed by few words in the summary of the posts). It would be great to "fix" this issue in Hugo by having a way to preserve the formatting/HTML/images in the automatically generated summary of a post that does not contain `<!--more-->`

**Possible solution**
If the content of `layout/partials/post/excerpt.html` contains the following code, then both the above issues are resolved. This code also correctly ensures that the "Read More" button is present whenever the post contains more content than shown in the summary, regardless of how the summary is calculated. (I'm sure the code can be improved, but this basically does the job)

```
{{- $key := $.Site.Params.post.excerpt -}}
{{- $content :=  "" -}}
{{- $maxLength := default 320 $.Site.Params.post.excerptMaxLength -}}
{{- if and (eq $key "description") (gt (len .Description) 0) -}}
  {{- $content = .Description -}}
{{- else if strings.Contains .RawContent "<!--more-->" -}}
  {{- $content = .Summary -}}
{{- else -}}
  {{- $content = .Content | safeHTML | truncate $maxLength -}}
{{- end -}}
{{- $content }}
{{- if or .Truncated .Description -}}
  <div>
    <a href="{{ .RelPermalink }}">Read More...</a>
  </div>
{{- end -}}
```
Notes:
1. The `{{- $content = .Content | safeHTML | truncate $maxLength -}}` is to preserve the formatting when `<!--more-->` is not present in the post's content.
2. If `$content = .Description` then `.Truncated` is false. However, because .Description is unlikely to have all the content of the post, therefore the "Read More" should still appear. Hence `{{- if or .Truncated .Description -}}`

**Comment by razonyang** [comment]
It makes sense that fallback to summary if `post.excerpt = description` and the `description` is empty.

As for your main request, I found an issue addressed in gohugoio/hugo#7926, but it may not be fixed quickly.

And the code snippet doesn't suit all summary cases, see also [Summary Selection Order](https://gohugo.io/content-management/summaries/#summary-selection-order). The other two cases will never be used.
It may be better to define another value for `post.excerpt`, such as `content`, so that we can always use the `Summary` as fallback.

**Comment by sagarbehere** [comment]
> the code snippet doesn't suit all summary cases, see also [Summary Selection Order](https://gohugo.io/content-management/summaries/#summary-selection-order). The other two cases will never be used.

? The [Summary Selection Order](https://gohugo.io/content-management/summaries/#summary-selection-order) lists 3 cases

1. Case 1 - With a `<!--more-->` divider: This is supported in the code snippet with `{{- else if strings.Contains .RawContent "<!--more-->" -}}` so this case is being used
2. Case 2 - `summary` variable in frontmatter: Yes, currently this is not being used, because the HBS theme uses the `description` variable in the frontmatter for the same purpose (which the above code snippet supports). At first, I was puzzled why the theme uses its own `description` variable rather than just using the `summary` variable.. and thought maybe you had added this feature to the theme before Hugo introduced the `summary` variable method for creating summaries. I actually think that we may no longer need the `description` variable.. we could just use the `summary` variable instead.. unless you think there is a reason to have both `summary` and e.g. `description`/`content`.
3. Case 3 - Automatic summary created from the initial text of the post: The problem with this is that Hugo removes the formatting. So the code snippet enables this exact same use case, but "fixes" it with `{{- $content = .Content | safeHTML | truncate $maxLength -}}` instead of `.Summary`

So it seems that the code snippet _does_ support all the conceptual use cases in [Summary Selection Order](https://gohugo.io/content-management/summaries/#summary-selection-order) ? Or have I missed something?

> It may be better to define another value for post.excerpt, such as content, so that we can always use the Summary as fallback.

Yes, that would work. But maybe we could even remove the `description` variable for the summary entirely? Is there a use case you are thinking of, where it would be useful to have such a theme-specific frontmatter variable *in addition to* the `summary` front matter variable? Can't users simply use the `summary`  variable if they want to create a summary that is different from the first few lines of their post?

**Comment by razonyang** [comment]
Actually, the `description` is not a replacement of `summary` parameter in the front matter. The [`description`](https://gohugo.io/variables/page/) is used by the `description` meta tag(SEO).

IMO, the expected selection order should be:

1. If `post.excerpt = "description"` and `description` is not empty, then it'll be used.
2. Manual splitting via `<!--more-->`.
3. If `summary` is set and not empty, then `summary` will be selected.
4. The text of content will be cut off by `post.excerptMaxLength` and formatted in HTML.

So that the `summary` is same as Hugo(`post.excerpt` is empty by default). Once the issue gohugoio/hugo#7926 has been fixed, what we need to do is just use `.Summary` instead of the `2-4`. What do you think?

**Comment by sagarbehere** [comment]
Ah, I didn’t know that ‘description’ was used for SEO. It makes sense now. 

Yes, I agree that the expected selection order you described makes sense. And later when the Hugo issue is fixed, .Summary can then be used instead of 2-4.
