### ISSUE TITLE
求助：无法搜索

### ISSUE THREAD

**Issue by kasusa** [razonyang/hugo-theme-bootstrap#344]
**Describe the bug**
我在本地hugoserver编译的时候，搜索是可以用的，但是我push到github上面，搜索就不能用了，就只有一个转圈图标一直一直在那里转，我进行了简单的排查，不清楚造成这的原因是什么，故来此提issue求助。

**To Reproduce**
hugo 编译之后push到github.io，访问搜索即会出现
[我的hugo博客](https://kasusa.github.io/hugo/)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/49443405/149610782-74be9b84-b4b3-4f17-b4e8-646afeac8dfd.png)

**Hugo version: 0.89.4**

**Desktop (please complete the following information):**
 - OS: win11
 - Browser chrome
 - Version 89

**Comment by razonyang** [comment]
这个是因为 JS 脚本被浏览器屏蔽了：

> Failed to find a valid digest in the 'integrity' attribute for resource 'https://kasusa.github.io/hugo/js/search.3e394af0db6c142a6fc472f61dbed4315414c382b857f953191f2fd017c74c08.js' with computed SHA-256 integrity 'Q7Z8uwOALvoOp9d3V//rxfZR/tg8SuCZFMDS73z9+qs='. The resource has been blocked.

我也尝试用 GitHub Pages 发布（Windows 下构建站点上传），不过没有重现这个问题出来：https://razonyang.github.io/en/search/?q=a

可以参考下[这篇文章](https://docs.github.com/cn/get-started/getting-started-with-git/configuring-git-to-handle-line-endings)，或者尝试升级下主题的版本。

相关问题：

- #124
- #209

**Comment by razonyang** [comment]
我先关闭这个 Issue ，如果有后续补充，可以再打开。

**Comment by kasusa** [comment]
我修复了，以下经验供他人参考:
修改search.html的内容：
把这个：
`<script src="{{ $script.Permalink }}" integrity="{{ $script.Data.Integrity }}" crossorigin="anonymous"></script>`

修改成这个
`<script src="{{ $script.Permalink }}"  crossorigin="anonymous"></script>`

问题就解决了，应该是integrity验证失败的问题，我也看不懂这个`{{ $script.Data.Integrity }}`是什么意思，总之删掉就能用用了。

ps 最新版用的是扩展版hugo，尝试升级了一下，失败了，还是继续用老版本了~

**Comment by kasusa** [comment]
并不是 行结束符 的问题
我这里是本地编译再上传的，建立了两个repo，因为我不会用action在线构建…
