### ISSUE TITLE
theme automatically changed to os default after printing

### ISSUE THREAD

**Issue by ltxlouis** [razonyang/hugo-theme-bootstrap#358]
**Describe the bug**
The dark/light color theme gets changed after printing current page ignoring user settings.

**To Reproduce**
1. OS theme set to dark
2. goto https://hbs.razonyang.com/en/, Settings -> Mode -> light mode
3. print current page
4. the color theme will be changed to 'dark mode'

**Expected behavior**
the color theme will still be light after printing

**Desktop**
 - OS: macos apple silicon
 - Browser chrome
 - Version 97.0.4692.99 (Official Build) (arm64)

**Comment by razonyang** [comment]
The `MediaQueryListEvent` was fired twice when printing a page on Chrome(works fine on Firefox). The former event is mismatched(`light`), the latter is matched(`dark`), so it always is `dark` mode after printing in Chrome. But I didn't find a solution so far.

```
window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', (e) => {});
```
