### ISSUE TITLE
'Read More' appearing incorrectly

### ISSUE THREAD

**Issue by sagarbehere** [razonyang/hugo-theme-bootstrap#362]
**Describe the bug**
After updating to v0.65.1, I am using `post.plainifyExcerpt = false` and have some very short (shorter than `post.excerptMaxLength`) blog posts. The 'Read More' button is still appearing in the list page summaries of those posts.

**To Reproduce**
1. Use HBS v0.65.1
2. Set `post.plainifyExcerpt = false` in `params.toml`
3. Create two very short blog posts. One which contains a `<!--more-->` as the last line, and one which does not contain a `<!--more-->` at all. The posts should not have `description` frontmatter variable
4. See error: On both the blog posts, the 'Read More' button will be present

**Expected behavior**
The 'Read More' button should not appear in the list page summaries when all of the content of the post is present in the summary and there is no additional content to be shown.

**Screenshots**
See below for an example. The three lines shown are the entire content of that post

![Screenshot from 2022-02-01 22-05-12](https://user-images.githubusercontent.com/1622959/152101614-c7915634-0a1f-48fe-8c76-a65efcfe851e.png)

**Hugo version:**

```shell
hugo v0.92.1+extended linux/amd64 BuildDate=2022-01-27T15:08:20Z
```
**Additional context**
There seem to be at least two bugs in `layouts/partials/post/excerpt.html`

The first one bug is in the logic for when the post contains `<!--more-->` and the relevant snippet is below
```
{{- else if strings.Contains .RawContent "<!--more-->" -}}
  {{- $content = .Summary -}}
  {{- $readMore := .Truncated -}}
```
After some testing, I've concluded that the line `{{- $readMore := .Truncated -}}` has no impact. It SEEMS that the line should be `{{- $readMore = .Truncated -}}` i.e. not ` :=` but `=`. See [this post](https://discourse.gohugo.io/t/solved-unsure-how-to-set-variable-value-after-declaring/1443) and the example at the end of the [Variables section](https://gohugo.io/templates/introduction/#variables) on this page. Basically, variables defined inside `if` conditionals and similar are not visible on the outside... which might explain why `{{- $readMore := .Truncated -}}` seems to have no effect. I can confirm that changing the `:=` to `=` makes the logic work as expected. This fixes the issue for short blog posts that do contain `<!--more-->`

The second bug is related to very short posts that do not have `<!--more-->` and the 'Read More' button still appears. In these cases,  the following lines are where the problem maybe lies
```
  {{- $readMore = false -}}
  {{- if findRE $ellipsis $content -}}
    {{- $readMore = true -}}
  {{- end -}}
```
I don't understand the logic here and what the whole `$ellipsis` thing is supposed to do. However, I can confirm that deleting those lines and instead adding the line `{{- $readMore = .Truncated -}}` as shown in the snippet below fixes the issue
```
{{- if default true .Site.Params.post.plainifyExcerpt -}}
    {{- $content = .Plain | htmlUnescape | truncate $maxLength $ellipsis | printf "<p>%s</p>" | safeHTML -}}
  {{- else -}}
    {{- $content = .Content | truncate $maxLength $ellipsis -}}
    {{- $readMore = .Truncated -}}
  {{- end -}}
```
The above fixes it for short blog posts that do not have `<!--more-->` and when `post.plainifyExcerpt = false`. I have not tried the case where `post.plainifyExcerpt = true`, but suspect that a similar bug (and potential fix) exists for that case too.

**Comment by razonyang** [comment]
Thanks for your feedback, you're right, `{{- $readMore := .Truncated -}}` will be treated as a local variable, it won't impact the outer variable. I'll fix the typo later.

Since we truncate the content by ourselves, and the `$ellipsis` is used to indicate whether the content is truncated or not.
According to the [.Truncated](https://gohugo.io/variables/page/), it's relative to `.Summary` variable, so it can't prove whether the content is truncated or not. I'll do some test and submit a patch tonight.

**Comment by sagarbehere** [comment]
Confirmed that this fixes all mentioned issues. Thank you :)
