### ISSUE TITLE
Default image for Twitter Card and Open Graph

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#367]
**Is your feature request related to a problem? Please describe.**
If there are no images for a post then the twitter card and open graph does not have an image entry.

I think that for example WordPress uses a default image in such a case, for example the main logo or anything else you can configure.

**Describe the solution you'd like**
Allow to set a default image for twitter card and open graph.

Thank you :)

**Comment by razonyang** [comment]
Sounds good, I'll implement it after closing the #368.

**Comment by razonyang** [comment]
The logo will be used as the social meta content if no image specified.
