### ISSUE TITLE
Menu closes when user click the search bar in mobile browser 

### ISSUE THREAD

**Issue by 0xsuk** [razonyang/hugo-theme-bootstrap#369]
**Gif**
![is_this_a_bug](https://user-images.githubusercontent.com/97814789/152338973-6c10ffce-7a42-4fc0-ba12-f6de59967ee1.gif)

**To Reproduce**
1. Go to https://hbs-cn.razonyang.com/en/ in mobile browser (or use developer tool in PC browser to test mobile view)
2. Click menu icon, then click search bar. 
3. Menu closes

**Tested on**
Brave browser on ubuntu
Safari on iphone

**Comment by razonyang** [comment]
Thanks for your feedback.
