### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by AnonymousDebug** [razonyang/hugo-theme-bootstrap#373]
I want to give the user a popup when that user first visits the site for accepting privacy policy, and if the user disagrees then the site is reloaded and they get that popup again, but if the user agrees then I store a cookie in their browser (acceptedPrivacy) and never show them that popup again.
I am thinking of doing this via javascript so that on every page it checks if that cookie exists, if not then if popups the user and if it exists then it does nothing but is thier a better way to do this in hugo, or in this theme?

**Comment by razonyang** [comment]
I can't think of a better way, since it's a static site.
