### ISSUE TITLE
Do options of config/_default/parmas.toml work in md files 

### ISSUE THREAD

**Issue by AnonymousDebug** [razonyang/hugo-theme-bootstrap#374]
In my contact.md file, I have set ```relatedPostCount = false
recentPostCount = false
featuredPostCount = false
``` in between the `+++  +++` area, but I still see them.
I am not sure if it is a bug or its not intended to work that way.
![image](https://user-images.githubusercontent.com/76240678/152400495-ce817f8f-e2b9-4839-9e85-537b06fa0305.png)

**Comment by sagarbehere** [comment]
I believe that these settings are not 'per post or per page' but apply universally across the site when used in the `params.toml` file. So you should probably not be setting them in a .md file's frontmatter.

**Comment by AnonymousDebug** [comment]
Alright, I would like to disable related posts for a specific page such as contact page, is that possible? If so then how may I go about doing that?

**Comment by razonyang** [comment]
As @sagarbehere said, there is no such parameter for disabling those sections on a particular page(front matter). But it would be good to have it, I'll handle it   tonight.

**Comment by AnonymousDebug** [comment]
Alright, I will wait for the update!

**Comment by razonyang** [comment]
I reopen this issue until it was implemented.
