### ISSUE TITLE
Colon (:) in title messes up catalog sidebar

### ISSUE THREAD

**Issue by sagarbehere** [razonyang/hugo-theme-bootstrap#375]
**Describe the bug**
If the title of any `_index.md` file in `content/docs` contains the `:` character, then

1. Clicking the arrow on the corresponding entry of the catalog sidebar to expand/collapse the entry does not work. 
2. Clicking the arrows on other entries to expand/collapse those entries and their children requires clicking the arrows multiple times. The arrows do not point downwards when the entry is expanded (they continue pointing to the right), nor do they point to the right when the entry is collapsed (they continue pointing downwards)

See GIF under Screenshots below

**To Reproduce**
1. In the exampleSite, edit the title of `content/docs/layouts/_index.md` to `title = "foo: Layouts"`
2. Visit the site. e.g. http://localhost:1313/en/docs/
3. Try clicking on the arrow in the  'foo: Layouts' entry to expand it. It will not work.
4. Try clicking the arrows to show Level 1/Level 2/Level 3/Level 4. It will require multiple clicks. As the Levels are shown, the arrow continues pointing to the right instead of pointing downwards
5. Click on Level 4. All the arrows on Level X will suddenly start pointing downwards.
6. Click on the arrow on Level 1. After several clicks, everything under Level 1 will collapse, but the arrow will keep pointing downwards.

**Expected behavior**
Clicking on an arrow to expand/collapse should not require multiple clicks and the arrow state should correctly indicate expanded/collapsed state.

**Screenshots**

![colon-catalog](https://user-images.githubusercontent.com/1622959/152459363-092b1777-88fb-4a91-a59b-50376b049fbe.gif)

**Additional context**
While doing all the above, the debug console will continuously show the message
```
Uncaught DOMException: Document.querySelector: '#catalogFoo:Layouts' is not a valid selector
```

**Comment by sagarbehere** [comment]
This also happens if the `|` character is present in the title of the `_index.md` file. I have not tested with other characters, but maybe there is a list of special characters which will trigger the same issue if they are present in the title?

**Comment by razonyang** [comment]
I use `.File.UniqueID` instead of `.Title` for generating catalog selector ID. So we can get rid of the invalid characters of CSS selector. That is, you can type any characters on the title now.

Thanks for your feedback!
