### ISSUE TITLE
Space character after every link

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#377]
**Describe the bug**
When using markdown syntax for links a space character is inserted after the resulting link.

From my friend, who tried to fix this:
I figured out, that the problem probably lies in the custom markdown render hook found here: https://github.com/razonyang/hugo-theme-bootstrap/blob/master/layouts/_default/_markup/render-link.html.
Somehow it doesn't prevent the line break following the link (can be seen in page source) that gets interpreted as a space (can be seen in accessibility properties) by Firefox and Chromium.

**To Reproduce**
`([Blog](https://example.com/bla), [Wiki](https://example.com/blu)`

**Expected behavior**
No space characters after a link.

**Screenshots**
![image](https://user-images.githubusercontent.com/385995/152600755-48abe459-1752-4edf-aa8d-374743e72c9f.png)

**Hugo version:**
- hugo v0.92.1+extended linux/amd64 BuildDate=2022-01-29T07:56:42Z VendorInfo=debian:0.92.1-1
- Same result with the current version on Arch Linux, which my friend used.

**Comment by razonyang** [comment]
Thank you.
