### ISSUE TITLE
"Offline" page should be excluded from post navigation

### ISSUE THREAD

**Issue by XJTUmg** [razonyang/hugo-theme-bootstrap#387]
**Describe the bug**
"Offline" is not a post and should be excluded from post navigation

**To Reproduce**
1. Go to https://hbs.razonyang.com/en/docs/level-1/level-2/level-3/level-4/

**Screenshot**
![hugo](https://user-images.githubusercontent.com/24864562/152697346-f0aeb47c-f854-43e9-9c9e-23102fcd09bd.PNG)

**Comment by Natenom** [comment]
The same applies for content in "pages/" :)
