### ISSUE TITLE
Catalog sidebar entries collapsing automatically after being expanded

### ISSUE THREAD

**Issue by sagarbehere** [razonyang/hugo-theme-bootstrap#388]
**Describe the bug**
@razonyang The most recent changes to the catalog sidebar menu seem to have introduced a new bug. Clicking the right arrow of a catalog sidebar menu entry to expand it and show its children causes the entry to expand as expected, but then it immediately collapses again. See GIF below.

**To Reproduce**
1. Go to https://hbs.razonyang.com/en/docs/configuration/
2. Click on the arrow of menu item 'Level 1'. It expands to show 'Level 2' as expected.
3. Click on the arrow of 'Level 2'. It expands, but immediately the entire Level 1 menu collapses. 
4. Clicking on Level 1 arrow again to expand it shows Level 2 _and_ Level 3.
4. Click on arrow of Level 3 to expand it. It expands to show Level 4, but immediately the entire Level 1 menu once again collapses.

**Expected behavior**
An expanded menu should remain expanded. It should not collapse immediately.

**Screenshots**

![catalog-scrollup](https://user-images.githubusercontent.com/1622959/152704855-1f7a1e59-1e9a-46c1-bc9d-9a40f0184bef.gif)

**Desktop (please complete the following information):**
 
This behavior is seen at least on Firefox and Chrome on Linux, as well as on Safari on iOS

**Comment by chrisrummel** [comment]
I can reproduce it in Windows 10 with Edge v98, too.

**Comment by razonyang** [comment]
It should be fixed now.
