### ISSUE TITLE
Automatically resize logo for use in top menu

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#403]
**Is your feature request related to a problem? Please describe.**
The file from logo Parameter in Params is used for 1. twitter card and open graph image if no image was set manually AND 2. for the logo in the top menu. Especially for being used as default image for 1. you want to have a high resolution image. But for 2. the image is displayed in 26x26 Pixel.

**Describe the solution you'd like**
Automatically created a resized version of the logo image to 26x26 pixels and use it.

:)

**Comment by razonyang** [comment]
Another approach is that specify `images` in the `params.toml`. The `images`'s priority is greater than logo.

```toml
images = [
  "/images/logo-large.png"
]
```

I think this feature is good, I'll handle it after switching to Hugo pipes.

**Comment by razonyang** [comment]
I'm going close this issue, it would not be a big deal, it can be achieved by `images` parameter.

**Comment by Natenom** [comment]
Works. Thank you. Totally forgot this.
