### ISSUE TITLE
Incorrect content in Recent Posts sidebar widget

### ISSUE THREAD

**Issue by sagarbehere** [razonyang/hugo-theme-bootstrap#406]
**Describe the bug**

In `content/docs` (but probably also in other Section types)

- If there are more than `.Params.recentPostCount` number of pages with the `weight` frontmatter variable present, then
- The Recent Posts sidebar widget will only show posts that have the `weight` frontmatter variable present. Any posts that do not have the `weight` frontmatter variable present will not be shown in Recent Posts, **even if** those posts are more recent.
- Actually, even if **just one single** page has the `weight` frontmatter variable present, and no other pages have the `weight` frontmatter variable present, then the page with the `weight` frontmatter variable will be added to the top of Recent Posts **even if** that page is much older and would normally not be present in Recent Posts.

**To Reproduce**
1. Look at a page in the exampleSite e.g. like the one at https://hbs.razonyang.com/en/docs/look-and-feel/
2. Note the posts shown in the Recent Posts widget.
3. Find a page that is **not** present in Recent Posts.. e.g. `content/docs/hooks/index.md` and add e.g. `weight = 900` to the frontmatter, immediately under the `title` frontmatter variable. Save and run `hugo server` command.
4. Observe that 'Hooks' is now the top item in Recent Posts, even though it is a much older post

**Expected behavior**
The Recent Posts widget should show the most recently added posts, regardless of the presence of the `weight` frontmatter variable.

**Hugo version:**

```
hugo v0.92.2+extended linux/amd64 BuildDate=2022-02-11T15:19:37Z
```
**Additional context**

I suspect that the problem is in this line in `layouts/partials/sidebar/recent-posts.html`

```
{{- range first $count (where site.RegularPages "Type" "in" $sections) -}}
```
The [Hugo docs](https://gohugo.io/templates/lists/#default-weight--date--linktitle--filepath) state that Hugo lists render the content by default in the order Weight > Date > LinkTitle > FilePath. I think this means that if there exist any pages that have the `weight` frontmatter variable, those will be listed first.. and that is probably what is happening here. The problem seems to be fixed if the above statement is replaced with

```
{{- range first $count (where site.RegularPages.ByDate.Reverse "Type" "in" $sections) -}}
```

Then the Recent Posts content indeed has the most recent posts, regardless of whether the `weight` parameter is present or not.

**Comment by razonyang** [comment]
Thank you.
