### ISSUE TITLE
LinkedIn social URL incorrect

### ISSUE THREAD

**Issue by ericcsinger** [razonyang/hugo-theme-bootstrap#408]
**Describe the bug**
I think the URL for LinkedIn is incorrect.  Right now it redirects to https://www.linkedin.com/USERNAME?_l=en_US, but I *think* it needs to redirect to https://www.linkedin.com/in/USERNAME

**To Reproduce**

In my config.yaml I have the following:

```YAML
author:
 social:
  linkedIn: USERNAME
```

When clicking on my LinkedIn icon, it redirects to the URL I mentioned above which leads to a page not found error.

**Expected behavior**
Redirect to my linked in profile :-)

**Hugo version:**

```shell
hugo v0.92.1-85E2E862+extended windows/amd64 BuildDate=2022-01-27T11:44:41Z VendorInfo=gohugoio
```

**Theme version:**

```shell
e353272e423387aafd3d3310fe78a4ced74a3e51 (HEAD -> master, tag: v0.67.0, origin/master, origin/HEAD) fix(sidebar-taxonomies): ignore empty name
```

**additional info:**
I can see in the \hugo-theme-bootstrap\layouts\partials\helpers\social-links.html there is a LinkedIn line that has the following string:

```
{{- $linkedin := dict "linkedin" (dict "url" "https://linkedin.com/%s" "icon" "fab fa-linkedin-in" "title" "LinkedIn") -}}
```

I suspect what it probably needs to be set to is.

```
{{- $linkedin := dict "linkedin" (dict "url" "https://linkedin.com/in/%s" "icon" "fab fa-linkedin-in" "title" "LinkedIn") -}}
```

**Comment by c20d-us** [comment]
+1 to this issue. I've worked around it by using "in/USERNAME" in my social.toml, but agree that the partial should be fixed.

**Comment by razonyang** [comment]
Thanks for your feedback.
