### ISSUE TITLE
Twitter card image being overloaded by new social partial

### ISSUE THREAD

**Issue by c20d-us** [razonyang/hugo-theme-bootstrap#410]
**Describe the bug**
The change to the social partial in ./layouts/partials/head/meta is causing a second Twitter card and Open Graph image to be added to the meta section. Looks like the intent was to use the site logo if there are no defined feature, cover, or thumbnail images, but the reference to the images param has incorrect scope.

**To Reproduce**
- Define "images" parameter in ./config/_default/params.toml that includes an image with *feature* in the name
- Define a site logo in ./config/_default/params.toml
- Build the site
- The meta section will now include the <meta> Twitter card and Open Graph images as defined in the images param, but also have Twitter card and Open Graph image metas using the logo image.

Ex:
```
<meta property="og:image" content="https://images.c20d.us/src/site-images/tweetcard-feature-image.png"/>
<meta name="twitter:card" content="summary"/>
<meta name="twitter:image" content="https://images.c20d.us/src/site-images/tweetcard-feature-image.png"/>
<meta name="twitter:title" content="Some post title"/>
<meta name="twitter:description" content="Some post description"/>
<meta name="twitter:site" content="@chalst"/>
<meta property="og:image" content="https://images.c20d.us/src/site-images/round-logo.png"/>
<meta name="twitter:image" content="https://images.c20d.us/src/site-images/round-logo.png"/>
```

**Expected behavior**
If a feature image exists in the images param, it should be the only Twitter card and Open Graph image defined in metas.

**Hugo version:**
```hugo v0.92.2-CDF6A0D6 darwin/amd64 BuildDate=2022-02-11T14:17:39Z VendorInfo=gohugoio```

**Theme version:**
hugo-theme-bootstrap-0.67.0
```a8d1092a14830e6fd32092970a9b1f9102783a29 (HEAD -> main, origin/main, origin/HEAD) Update social.html```

**Additional context**
Line 11 in ./layouts/partials/head/meta/social.html should be:
```{{- if and (not $featured) (not .Site.Params.images) -}}```

(".Site.Params.images" instead of ".Params.images")

**Comment by razonyang** [comment]
Thank you.
