### ISSUE TITLE
Sidebar does not open v0.67.1

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#414]
**Describe the bug**
Side bar (palette, dark/light mode) does not open. Intead the scroll bar(?) appears

**To Reproduce**
Click on the 3 dots on the to right corner.

**Expected behavior**
Open Sidebar

**Screenshots**
![image](https://user-images.githubusercontent.com/385995/155400096-c4ad0d7f-bcde-4f3a-a106-22240f2cb9be.png)

**Hugo version:**
hugo v0.92.1+extended linux/amd64 BuildDate=2022-01-29T07:56:42Z VendorInfo=debian:0.92.1-1

**Theme version:**
d925941d8c3074772fe530fce728de068fbb4427 (HEAD -> develop, origin/develop) fix(faq): question toggle icon

**Desktop (please complete the following information):**
 - Browser: Chromium and Firefox

**Comment by razonyang** [comment]
The `develop` would be the next version(unstable and breaking changes), the v0.67.1 exists on master branch.
`git checkout v0.67.1`.
I'll check this later.

**Comment by razonyang** [comment]
Could you please provide the console output(`F12` -> Console)?

**Comment by Natenom** [comment]
Did you mean Ctrl + F5? Alt + F5 seems to have no effect.

I reloaded a few times with Ctrl + F5 in Firefox and suddenly the side bar appeared. But after another reload it did not appear anymore.

Then I tried in Chromium, this is the output of console. The violation thing is printed after clicking the three dots in the top right corner:

![image](https://user-images.githubusercontent.com/385995/155648011-4390b2e6-a9dc-412c-aab1-ab8762e67b35.png)

This is the output in Firefox:
![image](https://user-images.githubusercontent.com/385995/155648085-faec45cc-2941-4006-be9c-c5e31e08976b.png)

**Comment by razonyang** [comment]
It seems not related to this issue. Are there any outputs in Console after clicking the menu icon?
I can't reproduce this issue.

**Comment by Natenom** [comment]
I cleared the storage in Chromium and in Firefox. Still the same.

I updated today to the current master and uploaded my blog. Can you please check if you can find a solution? blog.natenom.com

Thank you. (I also tried to remove all my _custom.css but it didn't fix the problem.)

**Comment by razonyang** [comment]
Would you mind sharing your repo with me? I need to reproduce this issue on my local environment.

**Comment by Natenom** [comment]
Done, via E-Mail.

**Comment by razonyang** [comment]
Thanks for the details, the issue should be fixed by the latest version.

**Comment by Natenom** [comment]
Is fixed. Thank you :)
