### ISSUE TITLE
Use "partialCached" for reduced build time

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#424]
**Is your feature request related to a problem? Please describe.**
My blog has around 2600 blog posts and many tags. A full build takes ~46 seconds.

I tested `partialCached` instead of `partial` in the file `layouts/partials/sidebar/main.html`with following results:

* use partialCached for "sidebar/taxonomies": Build time 36s
* use also partialCached for "sidebar/recent-posts": Build time 28s
* use also partialCached for "sidebar/featured-posts": Build time 13s 

**Describe the solution you'd like**
Use `partialCached` for parts with the same contents on all pages.

**Comment by razonyang** [comment]
Which version(`master` or `develop`) do you use?

**Comment by Natenom** [comment]
master.

**Comment by razonyang** [comment]
I drafted a new release about using Hugo Pipes to generate assets, I also cache some templates. Would you mind sharing your blog repo with me, so that I can simulate the performance issue of a real large site?

**Comment by razonyang** [comment]
I tested your repo with the latest release, it took about 7s for building the site on my laptop. Is it acceptable?

```text
                   |  DE   
-------------------+-------
  Pages            | 1295  
  Paginator pages  |  310  
  Non-page files   |  658  
  Static files     |  111  
  Processed images |  839  
  Aliases          |  454  
  Sitemaps         |    1  
  Cleaned          |    0  

Total in 6725 ms
```

**Comment by Natenom** [comment]
`
                   |  DE   
-------------------+-------
  Pages            | 4359  
  Paginator pages  | 1692  
  Non-page files   | 1002  
  Static files     |  111  
  Processed images | 1211  
  Aliases          |  898  
  Sitemaps         |    1  
  Cleaned          |    0  

Built in 16808 ms
`

For the complete blog. This is nice with partialCached.

Thank you :)

**Comment by razonyang** [comment]
I'm going to close this issue, please let me know if you found out any potential cacheable partials.
