### ISSUE TITLE
Font size selector not working

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#437]
**Describe the bug**
The font size selector in the sidbar does not work anymore.

**To Reproduce**
There are 5 steps you can choose:
| 1 2 3 4 5 |

Default is 3. Selecting 1, 2, 4, 5 increases the font size by 1(?) step. Selecting 3 sets font size back to normal.

**Expected behavior**
1 smallest and 5 largest font size

**Hugo version:**
hugo v0.92.1+extended linux/amd64 BuildDate=2022-01-29T07:56:42Z VendorInfo=debian:0.92.1-1

**Theme version:**
```shell
93a0a2dabb2b75e9b8f4e24b35c6a5138cf939bb (HEAD -> master, origin/master, origin/HEAD) style(docs-catalog): change padding as .5rem
```

**Desktop (please complete the following information):**
 - Firefox
 - Chromium

- [blog.natenom.com](https://blog.natenom.com/)

**Comment by razonyang** [comment]
Fixed by 433090d
