### ISSUE TITLE
hugo-theme-bootstrap not found when following Install via Hugo Module

### ISSUE THREAD

**Issue by breyed** [razonyang/hugo-theme-bootstrap#454]
**Describe the bug**
I followed [Install via Hugo Module](https://hbs.razonyang.com/en/docs/installation/hugo-module/) step by step, including the optional step 4. In step 5, `hugo mod npm pack` fails with:
> Error: module "hugo-theme-bootstrap" not found; either add it as a Hugo Module or store it in "[path]/my-new-blog/themes".: module does not exist

**To Reproduce**
1. Follow steps 1 through 5 of Install via Hugo Module.

**Hugo version**
hugo v0.94.2+extended darwin/amd64 BuildDate=unknown

**Desktop**
 - OS: macOS

**Additional context**
Hugo, npm, and Go all updated as of today via homebrew.

**Comment by razonyang** [comment]
Please replace the `theme` as `github.com/razonyang/hugo-theme-bootstrap`, and restart the hugo server.

**Comment by breyed** [comment]
That fixed it. Looks like another substep is needed in the docs at the end of step 4. I can submit a PR to fix the docs bug if you point me to the repo for the docs.

**Comment by razonyang** [comment]
@breyed PR are welcome. The docs are located at https://github.com/razonyang/hugo-theme-bootstrap/blob/master/exampleSite/content/docs/installation/hugo-module/index.md.
