### ISSUE TITLE
 executing "content" at <$paginator.Pages>: error calling Pages: runtime error: invalid memory address or nil pointer dereferenc

### ISSUE THREAD

**Issue by halobug** [razonyang/hugo-theme-bootstrap#462]
> [hugo 5/5] RUN hugo:
#17 0.680 Start building sites …
#17 0.681 hugo v0.95.0-9F2E76AF linux/amd64 BuildDate=2022-03-16T14:20:19Z VendorInfo=gohugoio
#17 2.052 Error: Error building site: failed to render pages: render of "page" failed: "/src/themes/hugo-theme-bootstrap/layouts/_default/archive.html:7:28": execute of template failed: template: _default/archive.html:7:28: executing "content" at <$paginator.Pages>: error calling Pages: runtime error: invalid memory address or nil pointer dereference
#17 2.053 Total in 1606 ms
------
executor failed running [/bin/sh -c hugo]: exit code: 255

**Comment by halobug** [comment]
0.95版本存在问题，0.85版本正常

**Comment by razonyang** [comment]
@halobug 我没重现出来，有重现步骤吗？
![image](https://user-images.githubusercontent.com/17720932/159428437-e20dfbe7-2ac6-4cde-a504-b0eff654c619.png)

**Comment by jehoshua7** [comment]
So I translated 

> translate 0.95版本存在问题，0.85版本正常

and it is

> there is a problem with version 0 95 0 version 85 is healthy

`hugo server --source=exampleSite --themesDir=../..`

> Start building sites … 
hugo v0.98.0-165d299cde259c8b801abadc6d3405a229e449f6 linux/amd64 BuildDate=2022-04-28T10:23:30Z VendorInfo=gohugoio
Error: Error building site: failed to render pages: render of "page" failed: "/home/********/Hugo/mysite/themes/hugo-theme-bootstrap/layouts/_default/archive.html:7:32": execute of template failed: template: _default/archive.html:7:32: executing "content" at <$paginator.Pages>: error calling Pages: runtime error: invalid memory address or nil pointer dereference
Built in 415 ms

Line 7 of /archive.html is

>     {{- $count := len $paginator.Pages -}}

I seem to remember that error msg before though. I had to change the number of posts/page ??

**BUT**, I'm using version 0.67.1

**Comment by razonyang** [comment]
This issue should be fixed by 0ff419c220d48cac168ae8807657069847ed8e6d and 567ab0b5a124b7191fc26c36aac51992d3b28cfb.

**Comment by jehoshua7** [comment]
@razonyang - thank you, that's fine now.

**Comment by razonyang** [comment]
@jehoshua7 My pleasure.
