### ISSUE TITLE
Featured image at the beginning of a post/page

### ISSUE THREAD

**Issue by LITUATUI** [razonyang/hugo-theme-bootstrap#467]
I would like to be able to set a featured image in the front matter that is shown at the beginning of a post as [discussed here](https://github.com/razonyang/hugo-theme-bootstrap/discussions/463). 

Bloggers that are migrating from WordPress to Hugo expect to have the capability of setting a main image (called featured image) for a post, that will be used as a thumbnail in homepage and at the top of the post.

The most popular [plugin](https://github.com/SchumacherFM/wordpress-to-hugo-exporter) to convert WordPress posts to markdown generates the following fields in the front matter:

title:
author:
type:
date:
url:
featureImage:
categories:
tags:

It would be nice to be able to use the featureImage field or something similar to set a main image that is shown the top a post or page.

In the [Mainroad theme](https://github.com/Vimux/Mainroad), If I set a `thumbnail: image.jpg` in the front matter, it's used as thumbnail shown at the homepage and on top of a post/page.

The [PaperMod theme](https://github.com/adityatelange/hugo-PaperMod) for the same function uses this format:

cover: 
    image: image.jpg

The image.jpg will be shown as a thumbnail in the homepage and at the beginning of the post/page.

I want to replicate the current design I have on my [WordPress blog](https://pushevs.com) to migrate to Hugo. This is easy to do with some Hugo themes like Mainroad and Papermod for example.

**Comment by LITUATUI** [comment]
Another example is the [Clarity theme](https://github.com/chipzoller/hugo-clarity#article-thumbnail-image).

> Article thumbnail image
> 
> `thumbnail: "images/2020-04/capv-overview/thumbnail.jpg"`
> 
> Article featured image
> 
> `featureImage: "images/2020-04/capv-overview/featured.jpg"`

**Comment by razonyang** [comment]
There is `images` parameter for this already, but it **MUST** be an array, not a string. That is the limitation of Hugo twitter card and open graph templates.

You can change it via editor easily, take VS Code as an example(replace with regular expression):
![image](https://user-images.githubusercontent.com/17720932/159600653-b18a417e-19ec-49e8-a89c-fad320e9d391.png)

> `thumbnail: (.+)` to `images: [$1]`.

As for the featured images shown on the beginning of posts, I'll handle it this weekend.

**Comment by razonyang** [comment]
@LITUATUI FYI, I just added a new parameter for toggling this feature, default to `false`, so that users will not be confused after upgrading the theme, see also #473. You'll need to turn it on by setting `post.featuredImage` as `true`:

```toml
// config/_defualt/params.toml

[post]
  featuredImage = true
```

Sorry for the inconvenience.

**Comment by chrisrummel** [comment]
Fantastic, thanks a lot!

**Comment by LITUATUI** [comment]
Thanks @razonyang. 

I actually prefer this new more flexible way, so everybody is happy.

**Comment by Natenom** [comment]
Thank you for this feature. Always wanted to have it. :)
