### ISSUE TITLE
featured.jpg gets displayed even if it is not used

### ISSUE THREAD

**Issue by chrisrummel** [razonyang/hugo-theme-bootstrap#473]
**Describe the bug**
Posts are organized in one directory per post, including index.md, at least one picture featured.jpg and sometimes more pictures.
Usually featured.jpg is NOT used in the markdown but only for preview purposes in index listings. That means the pages markdown code includes only image links using all the other pictures and not featured.jpg

Nevertheless featured.jpg is always displayed as the first piece of content on every page.

**To Reproduce**
Have a look at http://bronski.net/

**Expected behavior**
If featured.jpg is not listed in frontmatter nor in markdown, it should not be displayed.

**Hugo version:**

```shell
$ hugo version
hugo v0.95.0-9F2E76AF+extended linux/amd64 BuildDate=2022-03-16T14:20:19Z VendorInfo=gohugoio
```

**Theme version:**

```shell
$ cd themes/hugo-theme-bootstrap
$ git log -n 1 --decorate --pretty=oneline
7d4ba4f07f1236a808b6a4f65eb32f7f8a064a9a (HEAD -> master, tag: v0.72.0, origin/master, origin/HEAD) i18n: update pl.toml
```

**Desktop (please complete the following information):**
 - OS: Ubuntu LTS 16.04

**Comment by razonyang** [comment]
Actually, the `featured.jpg` should be treated as featured images. Maybe we can define a parameter `post.featuredImage`(default to `false`) indicates whether to show the featured images above the posts?

**Comment by chrisrummel** [comment]
I am not sure, but I think when the change about the search order for featured, thumbnail etc. was implemented, there was no image shown at the top of the post.
Anyways... Just showing a picture whithout being able to influence anything about it, sounds like a not optimal solution. I sure would like to suppress that, e.g. as you suggested with a false/true toggle.

**Comment by razonyang** [comment]
That's a feature request #467 about showing the featured images above the posts. It makes sense to add a new parameter for toggling this feature. I'll implement this tonight.
