### ISSUE TITLE
Support RTL languages natively

### ISSUE THREAD

**Issue by yshalsager** [razonyang/hugo-theme-bootstrap#477]
**Is your feature request related to a problem? Please describe.**
Out of the box, the theme doesn't support right to left languages like Arabic, Persian, and Hebrew.

To be able to use the theme for my personal website, both versions ([English](https://yshalsager.com/en/) and [Arabic](https://yshalsager.com/ar/)), I had to do some [CSS workarounds](https://github.com/yshalsager/personal_website/blob/master/assets/main/scss/_custom.scss) to make the theme work nicely with RTL content (still has many things that doesn't).

But I think having native compatibility with RTL would be a huge plus for our theme.

**Describe the solution you'd like**
Ideally, we can do the following:
- Add a `LanguageDirection` variable, that should be `ltr` by default, and `rtl` if the user set the language to be so.

```html
<html lang="{{ .Site.LanguageCode }}" dir="{{ default `ltr` .Language.LanguageDirection }}">
```
- Update some CSS properties in the theme to use logical properties to show stuff correctly for both of LTR and RTL like:
	- `margin/padding/border-right` to `margin/padding/border-inline-end`
	- `margin/padding/border-left` to `margin/padding/border-inline-start`
	- `left` to `inset-inline-start`
	- `right` to `inset-inline-end`
- Make fa-chevron-circle-down in posts navigation show in the correct directions.
- Make sure that codeblocks are kept LTR
- Add some example page for RTL content, like markdown page in French example site.

**Describe alternatives you've considered**
Some CSS that isn't nice at all [here](https://github.com/yshalsager/personal_website/blob/master/assets/main/scss/_custom.scss)

**Additional context**
I am ready to work on this or help with it if you prefer to work on it.
Inspired by https://github.com/CaiJimmy/hugo-theme-stack/pull/519 and https://github.com/adityatelange/hugo-PaperMod/pull/47

**Comment by razonyang** [comment]
I didn't know about RTL, it may be implemented by [Bootstrap built-in RTL](https://getbootstrap.com/docs/5.1/getting-started/rtl/) functionality easily. I can create a PR for that tonight. PR are also welcome.

**Comment by razonyang** [comment]
I'm just wondering that should all elements be RTL? Such as top-app-bar, layout etc.

**Comment by yshalsager** [comment]
@razonyang 
I have gave a try to what I listed here yesterday and the results are promising with minor visual problems in the rtl version, will draft a PR. 

The layout is fine to be as is, the post in the right then the side bar on the left, same for the top bar.

**Comment by razonyang** [comment]
@yshalsager I'm looking forward to your PR, I'll review it if it's ready.
