### ISSUE TITLE
Display heading 4 in TOC (and possibly 5?)

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#488]
**Is your feature request related to a problem? Please describe.**
The TOC on a page shows headings down to h3 only. Because the Page title is h1, you have only h2 and h3 to structure your content. But in some long blog posts I would need at lease h4, maybe even h5.

**Describe the solution you'd like**
By decreasing the indentation of sub headings it sould be possible to display at least h4.

**Describe alternatives you've considered**
Instead of using h4 I use something like

```
## h2-title
### h3-title
### h3-title – h4-sub
### h3-title – h4-sub2
```

Which is not very intuitive from my point of view.
![image](https://user-images.githubusercontent.com/385995/160268536-0b0c98ef-5d5a-46ec-8f71-6fc1f9ba0961.png)

**Comment by razonyang** [comment]
The TOC end level default to `3`, you could change it by configuring [Markup](https://gohugo.io/getting-started/configuration-markup):

```toml
# config.toml
[markup]
  [markup.tableOfContents]
    endLevel = 6
```

**Comment by Natenom** [comment]
Thank you :)
