### ISSUE TITLE
Some items are shown in menu and footer even after menu.toml is empty

### ISSUE THREAD

**Issue by TheJavaGuy** [razonyang/hugo-theme-bootstrap#500]
**Describe the bug**
After emptying `config\_default\menu.toml` and rebuilding site, some items are still shown in the dropdown menu and the footer.

**To Reproduce**
1. Create an example site like described at https://hbs.razonyang.com/en/docs/installation/hugo-module/
2. Edit file `config\_default\menu.toml` and delete all content (but leave the file on disk)
3. Rebuild the site

**Expected behavior**
Dropdown menu in header doesn't exist. Footer menu doesn't exist.

**Screenshots**
![image](https://user-images.githubusercontent.com/11942401/161438380-4aed377b-f692-4272-af4f-6c1da9d77cd3.png)
![image](https://user-images.githubusercontent.com/11942401/161438414-661ac11d-f977-44e6-94a4-27aea32b7c3b.png)

**Hugo version:**

```shell
$ hugo version
hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb+extended windows/amd64 BuildDate=2022-03-26T09:15:58Z VendorInfo=gohugoio
```

**Theme version:**

```shell
$ cd themes/hugo-theme-bootstrap
$ git log -n 1 --decorate --pretty=oneline
69144efc9f264380f7a01e151e5ddbcee537cc6e (HEAD -> master, tag: v0.74.0, origin/master, origin/HEAD) fix(viewer): filter the linkable picture tags
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 98.0.2

**Comment by razonyang** [comment]
There are multiple ways to configure menus, you need to remove the menu from front matter as well.
See also https://hbs.razonyang.com/en/docs/menu/
