### ISSUE TITLE
images missing title element

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#510]
**Is your feature request related to a problem? Please describe.**
Markdown in Hugo allows to set an image title with:

```![alt text](b.jpg "title")```

The default render-image.html(?) renders to:

```<p><img src="b.jpg" alt="alt text" title="title"></p>```

While your render-image.html renders to:

```
<p><picture><img class="img-fluid" alt="alt text" src="b.jpg" loading="lazy">
</picture>

</p>
```

**Describe the solution you'd like**
Please add the title attribute to html code. :)

**Comment by razonyang** [comment]
Thanks for your feedback.
