### ISSUE TITLE
Please sort taxonomy

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#512]
**Is your feature request related to a problem? Please describe.**
Tags/Categories in Posts are not sorted.

`Mobilität Autos Falschparken Feuerwehr Perouse OpenBikeSensor FahrradInfrastruktur`

**Describe the solution you'd like**
Should be:

`Autos Falschparken FahrradInfrastruktur Feuerwehr Mobilität OpenBikeSensor Perouse`

Tried to achieve that with sort in `post/meta.html` but it didn't work.

**Comment by chrisrummel** [comment]
Is it always sorted by title now? I quite liked that it was ordered by the most used taxonomy down to taxonomies that have only been used once. If possible, I would like that to be configurapble by a param taxonomySortOrder.

**Comment by razonyang** [comment]
> Is it always sorted by title now? I quite liked that it was ordered by the most used taxonomy down to taxonomies that have only been used once. If possible, I would like that to be configurapble by a param taxonomySortOrder.

Sounds better, reopen it.

**Comment by Natenom** [comment]
Are you sure it worked anyway? Seems not to on my blog (built locally and on the server)

https://blog.natenom.com/2022/04/linkdump-8-2022/

![image](https://user-images.githubusercontent.com/385995/165047157-6fe0ee23-99b8-406e-8b14-c5e85c1ba333.png)

**Comment by Natenom** [comment]
Now there is another problem. There is no seperation between categories and tags. So now the tags are somewhere in between the tags.

**Comment by razonyang** [comment]
@Natenom  @chrisrummel I created the `taxonomySortingMethod` parameter. The taxonomies are sorting in alphabetical order by default, you can sort taxonomies by their popularity setting `taxonomySortingMethod="popularity"`. It sorts the taxonomies in taxonomy's pages(such as `/tags`, `/categories`) and the post's meta. The taxonomies on the sidebar always be sorted in popularity order.

**Comment by chrisrummel** [comment]
@razonyang Thanks, that works nicely. I just pulled all the latest changes and I really like the alphabetical order under /tags while still having popularity order in the sidebar.

I am getting a
`WARNING: calling IsSet with unsupported type "bool" (bool) will always return false.`
while building, though.

**Comment by razonyang** [comment]
> I am getting a
> `WARNING: calling IsSet with unsupported type "bool" (bool) will always return false.`
> while building, though.

That is a known warning message about fullWidth parameter, it won't bring any errors.
