### ISSUE TITLE
Error in documentation of tocPosition ?

### ISSUE THREAD

**Issue by sagarbehere** [razonyang/hugo-theme-bootstrap#527]
**Describe the bug**

The `tocPosition` parameter is shown as being under Page Parameters in [the documentation](https://hbs.razonyang.com/en/docs/configuration/#page-parameters), which states that page parameters are found in a post's FrontMatter.

However, looking at the implementation, e.g. in `layouts/partials/sidebar/main.html` 
```
{{- if ne "content" .Site.Params.tocPosition -}}
{{- partial "sidebar/toc" . -}}
{{- end -}}
```

it seems that `tocPosition` is not a Page Parameter. It is a Site Parameter. So it should be documented in [2. Site Parameters](https://hbs.razonyang.com/en/docs/configuration/#site-parameters) and not in [3. Page Parameters](https://hbs.razonyang.com/en/docs/configuration/#page-parameters) ?

Also, it seems that the `tocPosition` only affects the `posts` layout. This should be mentioned in the documentation.

**Comment by razonyang** [comment]
Thank you.
