### ISSUE TITLE
Add "noscript" tag to search page :)

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#531]
**Is your feature request related to a problem? Please describe.**
Currently there is no information that JS is needed for search.

**Describe the solution you'd like**
Add <noscript>lala you need js for search</noscript>

Thank you :)

**Comment by razonyang** [comment]
I'll handle it after migrating to Bootstrap 5.2 and redesigning the UI.

**Comment by razonyang** [comment]
Just show an alert message if the browser doesn't support JavaScript.

![Screenshot_20220612_220332](https://user-images.githubusercontent.com/17720932/173237016-ce60882e-ff35-468d-a9d1-c1cb879778db.png)

Preview: https://develop.hbs.razonyang.com/

Please feel free to share if you got any ideas of this.
