### ISSUE TITLE
Move tags to bottom of post article

### ISSUE THREAD

**Issue by Mecanik** [razonyang/hugo-theme-bootstrap#538]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It's pretty hard to differentiate the Category from Tags since they are so next to each other, especially if you add 10 tags it would be horrible.

My suggestion is to move the tags below the article (above the next posts), it would have more space and would follow a natural blog system.

Thanks

**Comment by Natenom** [comment]
I solved that issue by prefixing # to a tag. Not perfect but seems to work.
![image](https://user-images.githubusercontent.com/385995/170550268-2f08344e-dcf9-4f2b-9e39-ae2058762a54.png)

**Comment by Mecanik** [comment]
> I solved that issue by prefixing # to a tag. Not perfect but seems to work. ![image](https://user-images.githubusercontent.com/385995/170550268-2f08344e-dcf9-4f2b-9e39-ae2058762a54.png)

Not a bad idea, can you share modification?

**Comment by Natenom** [comment]
I did not make this modification so I am not sure if this is all that you need (css only):

```
div.post-meta span.post-taxonomies a.badge.post-taxonomy {
	clip-path: unset; /* Spitze von Tags und Kategorien entfernen*/
	font-size: .9em; /* Tags in Beiträgen größer machen. default ist .75em */
	padding-left: .25em; /* Abstand ohne Spitze verringern */
	&[href*=tags]::before {
		content: "#"; /* Vor Tags ein # setzen */
	}
}
```

**Comment by razonyang** [comment]
I'm going to close this issue, since it's a taste matter, but it can be solved by customizing the `post/meta.html` partial and CSS easily.
