### ISSUE TITLE
Improving dark mode for Bootstrap elements

### ISSUE THREAD

**Issue by Mecanik** [razonyang/hugo-theme-bootstrap#542]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Some elements do not switch to "dark mode", like outline buttons, cards and more. The ideal solution would be to switch all elements, although I understand this would take considerable time.

**Describe alternatives you've considered**
Provide a documentation how the user can fix/improve this himself.

Thanks

**Comment by razonyang** [comment]
Bootstrap twbs/bootstrap#35857 add dark mode support officially. I'll handle it after that.

**Comment by Mecanik** [comment]
Sounds great, can't wait!
