### ISSUE TITLE
Don't scoll up on dark-mode change/font size change

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#570]
**Describe the bug**
When changing the current dark/light/auto mode or font size in the top bar, the "page" always scrolls up.

**Expected behavior**
Do not scroll at all. See color change for example :)

**Hugo version:**

hugo v0.100.2+extended linux/amd64 BuildDate=unknown VendorInfo=debian:0.100.2-1

**Theme version:**

```
3137ac2bc96600650e57efcd678bef04e59dba1a (HEAD -> master, origin/master, origin/HEAD) style(post): update headings
```

**Desktop (please complete the following information):**
 - Chromium, Firefox

- Live Site https://blog.natenom.com/

**Comment by razonyang** [comment]
Thanks for your feedback.
