### ISSUE TITLE
Errors in bundle.min.js when running in docker

### ISSUE THREAD

**Issue by costalfy** [razonyang/hugo-theme-bootstrap#588]
Hi, there's 2 errors in bundle.min.js in main branch when we run in docker:

- Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at new Nn (bundle.min.f99d099257469bc486b7f472207e950859c052f72fe4baaeb753d5b4f6801d21.js:1:85008)
- Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "undefined".

How to reproduce:
git clone ...
docker build -t my-image:latest .
docker run -d -p 8080:80 my-image:latest
open localhost:8080
check dev console with F12

**Comment by razonyang** [comment]
Which theme version do you use?

**Comment by costalfy** [comment]
Commit : [0177ba1](https://github.com/razonyang/hugo-theme-bootstrap/tree/0177ba107533128dae1cec670878caa5936a517f)
on https://github.com/darktable-fr/darktable-fr/tree/main/themes

**Comment by razonyang** [comment]
Fixed by latest commit. As to the second error, it is related to third party(FontAwesome), nothing I can do in this theme, but it works as expected.
