### ISSUE TITLE
Fade in anchor for headings

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#596]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
You changed from the icon to a # character for the anchor in headings. Thanks for that :)
In my wiki I use the Hugo theme docsy where the anchors are invisible and become visible when you hover the heading (or the complete line). I thinks that is much nicer than an always visible # character. I can change that probably with CSS but wanted to tell you how others do it. :)

Can see this for example here: https://wiki.natenom.com/docs/minimalismus/gruenerfaden/

**Comment by razonyang** [comment]
Good to know, it's easy to achieve. How about placing the anchor `#` on the left of headings(`position: absolute`)?

**Comment by Natenom** [comment]
Could look weird with numbered headings. Also confusing for markdown users?

**Comment by razonyang** [comment]
Ok, keep the original position, just show it up on hover.
