### ISSUE TITLE
Search doesn't work if baseUrl is not a root URL

### ISSUE THREAD

**Issue by costalfy** [razonyang/hugo-theme-bootstrap#602]
Hi razonyang,
I've switch my old theme to hugo-theme-bootstrap and run it throught gitlab pages https://andycostanza.gitlab.io/blog.
Here is my [config.toml](https://gitlab.com/andycostanza/blog/-/blob/master/config/_default/config.toml) and the baseURL value is https://andycostanza.gitlab.io/blog/
When i use the search input in nav bar, the form submit an action on https://andycostanza.gitlab.io/fr/search instead of [https://andycostanza.gitlab.io/**blog**/fr/search](https://andycostanza.gitlab.io/blog/fr/search)
I thinlk it's related to https://github.com/gohugoio/hugo/issues/4995 but i'm not sure

Could you please verify if you have same issue on your side?

btw, i use hugo 0.101.0 extended

**Comment by razonyang** [comment]
Yes, it looks like the `absLangURL` doesn't work on non-root `baseURL`.
