### ISSUE TITLE
Native support for Giscus comments

### ISSUE THREAD

**Issue by yshalsager** [razonyang/hugo-theme-bootstrap#613]
**Is your feature request related to a problem? Please describe.**
The theme provide support for Utterances comments and any custom widget, but custom widgets aren't well integrated with the theme. E.g. Toggling light/dark mode won't affect the custom comment widget.

I am using https://github.com/giscus as an alternative of  Utterances comments, it does exactly the same thing but depends on GitHub Discussions instead of issues which I find more appealing to me.

As you can see [here](https://yshalsager.com/en/posts/debugging-and-fixing-selenium-send-keys-wrong-text-input/#post-comments), in dark theme the widget is still using the white theme as set in [custom.html](https://github.com/yshalsager/personal_website/blob/master/layouts/partials/post/comments/custom.html) partial.

**Describe the solution you'd like**
I would like to suggest adding https://github.com/giscus as a native option for comments, and integrate it with the theme the same way Utterances is supported.

**Describe alternatives you've considered**
Only setting up my own custom widget.

**Comment by razonyang** [comment]
For others who want to change the theme of your custom comments' engine, the theme does emit a custom event called `hbs:mode`, you can change it via event listener.

```js
import { getPreferMode } from 'js/mode/prefer';

document.addEventListener('hbs:mode', (e: CustomEvent) => {
  changeTheme(e.detail.mode === 'auto' ? getPreferMode() : e.detail.mode);
});
```

**Comment by razonyang** [comment]
Implemented via #615. https://hbs.razonyang.com/v1/en/docs/widgets/comments/#giscus

**Comment by yshalsager** [comment]
> Implemented via #615. https://hbs.razonyang.com/v1/en/docs/widgets/comments/#giscus

Awesome! Thank you!

**Comment by razonyang** [comment]
@yshalsager FYI, I saw that you've added the Arabic language to Giscus, you'll need to upgrade the theme to the latest commit to make it work. Since the theme maintaining it own languages list for avoiding getting errors of Giscus giscus/giscus#620 on the case of unsupported languages.

https://github.com/razonyang/hugo-theme-bootstrap/blob/04629ed6fba740e93cc99d7152c7974c9b7057ed/layouts/partials/post/comments/giscus.html#L3

**Comment by yshalsager** [comment]
> 

Thanks for letting me know, will do now :)
