### ISSUE TITLE
There is no rel="canonical" link tag

### ISSUE THREAD

**Issue by Mecanik** [razonyang/hugo-theme-bootstrap#617]
**Describe the bug**
Site does not get indexed. After spending a bit of time analysing I realised there is no rel="canonical" link header, which is a big problem.

https://techtitbits.com/posts/hugo-canonical-url/

**Comment by razonyang** [comment]
That meta tag is used on duplicate pages. 

https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls
