### ISSUE TITLE
Incorrect table of contents count

### ISSUE THREAD

**Issue by nemu1113** [razonyang/hugo-theme-bootstrap#619]
I have discovered that the numbers displayed in the heading tags of this site template are not calculated correctly.

The calculation of the numbers was implemented in SCSS, so I looked into it in detail and found the following bug, which I would appreciate your fixing.

Target file
/assets/main/scss/post/index.scss
→L91

Before: "counter-reset: h#{$heading + 1}counter;"
After: "counter-reset: h#{$heading + 1}Counter;"

I have confirmed that the correct numbers were displayed after a simple modification of the SCSS and testing on a sample site.

I would be happy if I could contribute to your HBS template improvement.

**Comment by razonyang** [comment]
Oh, I didn't notice that, it may be format issue, PR are welcome.

**Comment by razonyang** [comment]
@nemu1113 would you mind creating a pull request? I can do it for you, but I need your email address, so that I can mark this contributed by you.

**Comment by nemu1113** [comment]
> @nemu1113 would you mind creating a pull request? I can do it for you, but I need your email address, so that I can mark this contributed by you.

@razonyang Thank you for your consideration.
Please check the pull request and merge if there are no problems.

example:
https://deploy-preview-620--hbs-docs.netlify.app/en/docs/image-processing/

before:
https://hbs.razonyang.com/v1/en/docs/image-processing/
