### ISSUE TITLE
Ability to set mastodon username + instance

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#626]
**Is your feature request related to a problem? Please describe.**
You can currently add a mastodon username which is always linked to mastodon.social. There are many instances as this is a federated network.

**Describe the solution you'd like**
Ability to set username + instance or full url to user profile.

**Describe alternatives you've considered**
Changing partials.

**Comment by razonyang** [comment]
Hi,  I didn't use Mastodon before, I'm curious about what full URL is used for? Does Mastodon support custom profile URL?

**Comment by Natenom** [comment]
Full url would in my case be: https://social.anoxinon.de/@natenom

But can be https://anything.foo.tld/@username
