### ISSUE TITLE
Disable site logo's animation

### ISSUE THREAD

**Issue by ArvindRSingh** [razonyang/hugo-theme-bootstrap#639]
Low or no priority as a workaround is available and noted below. Posting this here for quick reference.

The site's logo animates on hovering, some users of the theme might like it disabled or apply a different animation.

Two possible solutions:
1. Add a parameter in the parameter configuration file to conditionally add animation.
2. Override the CSS to disable the transformation of the logo.

Add below code in assets\main\scss\_custom.scss to disable animation by overriding CSS style.

```
.top-app-bar .logo:hover  {
  transform: none!important; 
 // Or apply some other transformation :)
}
```

**Comment by razonyang** [comment]
I just added an option named `$logo-animation` for this:
```scss
// assets/main/scss/_variables.scss
$logo-animation: false;
```
