### ISSUE TITLE
Search (fusejs) has become very slow

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#646]
**Describe the bug**
The new search is very slow.

**To Reproduce**
1. Go to https://blog.natenom.com/search/?q=wochen

- Takes ~1 second for 125 results.
- This is an old version of your theme.

With the current theme version it takes ~24 seconds of full cpu usage for the same 125 search results in Chromium. In Firefox much worse.

**Expected behavior**
1 second, not 24. :)

**Hugo version:**
hugo v0.101.0+extended linux/amd64 BuildDate=unknown VendorInfo=debian:0.101.0-1

**Theme version:**
100533ac212200b25f6f8dd114636540cc4e5190 (HEAD -> master, origin/master, origin/HEAD) style(search): display result score

**Comment by razonyang** [comment]
Could you share your repo for me to test the performance issue?
I can also emulate the issue with fake posts if it's inconvenient.
BTW, how many posts of your site?

**Comment by Natenom** [comment]
I did send you part of my repo some time ago, all from 2020 to 2022. Do you still have it? I am on a very slow connection with 1 MBit upload only, it would take very long time to upload 1,6 GB for my current repo.

Therer are currently ~2600 blog posts on my blog.

**Comment by Natenom** [comment]
And this is the theme version on the live blog:

26b65d12c178203cf8c963fa4c3337de18d92f0a (HEAD, origin/master, origin/HEAD) style: fix the social links of top app bar

**Comment by Natenom** [comment]
I could send you the generated index.json (4,6 MiB) if it could help. Preferred via E-Mail.

**Comment by razonyang** [comment]
@Natenom Yep, send me the index.json as well via email.

**Comment by razonyang** [comment]
I found the email that you sent me before, but the archive.zip is not long exist on your server, I couldn't download it. I didn't have the copy on local cuz I reinstalled my OS a few months ago.
