### ISSUE TITLE
code fences are not rendered in alert shortcode.

### ISSUE THREAD

**Issue by landure** [razonyang/hugo-theme-bootstrap#653]
I'm using alert short code to highlight important command lines, or dangerous commands :+1: 

````markdown
{{< alert warning >}}

Store the MariaDB root password in a password manager:

```bash
command echo "The password for MySQL root account is: '${mariadb_root_password}'."
```

{{< / alert >}}
````

This render as following:

![image](https://user-images.githubusercontent.com/1490071/183616027-ac88a76e-c379-41a7-bbbd-44aa253a2590.png)

I would like it to render as :

![image](https://user-images.githubusercontent.com/1490071/183616243-f5c31068-7105-4e04-84aa-7fdcaa762985.png)

In order to achieve this, I took inspiration from [hugo-notice theme component](https://github.com/martignoni/hugo-notice), and modifier the alert short code to render .Inner contents using .Page.RenderString.

````twig
{{/* Available notice types: primary secondary success danger warning info light dark */}}
{{- $type := default "info" (.Get 0) -}}
{{/* Render inner markdown with Page.RenderString, to render code fences. */}}
{{ $renderStringOptions := dict "display" "inline" }}
{{- $raw := ( .Page.RenderString $renderStringOptions .Inner ) -}}
{{- $block := findRE "(?is)^<(?:address|article|aside|blockquote|canvas|dd|div|dl|dt|fieldset|figcaption|figure|footer|form|h(?:1|2|3|4|5|6)|header|hgroup|hr|li|main|nav|noscript|ol|output|p|pre|section|table|tfoot|ul|video)\\b" $raw 1 -}}
{{/* Store the optional alert icon in variable. */}}
{{- if not (findRE "<i.*class=\"alert-icon.*\".*></i>" $raw) -}}
  {{- .Scratch.Set "alertIcon" ( partial "utilities/alert-icon" $type ) -}}
{{- else -}}
  {{- .Scratch.Set "alertIcon" "" -}}
{{- end -}}
<div class="alert alert-{{ $type }}" role="alert">
  {{- if or $block (not $raw) -}}
    {{/* Insert alert icon in the first block, to fix ugly line break after icon. */}}
    {{ replaceRE "(?is)^(<[^>]+>)" ( print "$1" ( .Scratch.Get "alertIcon" ) ) $raw 1 | safeHTML }}
  {{- else -}}
    {{ .Scratch.Get "alertIcon" }}{{ $raw }}
  {{- end -}}
</div>
````

This modified short code need Goldmark renderer to be unsafe to prevent "raw HTML omitted" problem when using shortcodes generating HTML in the inner content (eg. {{< highlight bash >}}) :

```yaml
markup:
  goldmark:
    renderer:
      unsafe: true
```

I'm no Hugo specialist, and there is surely a better way to do this, hence this feature request. Thank you for your hard work.

**Comment by razonyang** [comment]
You'll need to replace the `<` and `>` with `%` and `%` if your shortcode content is Markdown.

````markdown
{{% alert warning %}}
Store the MariaDB root password in a password manager:
```bash
command echo "The password for MySQL root account is: '${mariadb_root_password}'."
```
{{% /alert %}}
````

You can also specify the heading with following:

````markdown
{{% alert warning %}}
{{< alert-heading >}}WARNING{{< /alert-heading>}}
Store the MariaDB root password in a password manager:
```bash
command echo "The password for MySQL root account is: '${mariadb_root_password}'."
```
{{% /alert %}}
````

![image](https://user-images.githubusercontent.com/17720932/183625835-9cf227ea-118a-4f52-ae19-6c4b74d96fb3.png)

**Comment by landure** [comment]
My bad. In my defense, i tried this with : `markup.goldmark.renderer.unsafe: false`. In this case, the result of using `{{% alert warning %}}` is;

![image](https://user-images.githubusercontent.com/1490071/183829138-5f2a23ca-c22a-409f-8fc2-df69315a0c2f.png)

Once the goldmark renderer is set to unsafe:

```yaml
markup:
  goldmark:
    renderer:
      unsafe: true
```

The result is:

![image](https://user-images.githubusercontent.com/1490071/183829379-1516f073-a162-469e-97a7-5f2928a7445c.png)

The need to set the unsafe value should be added to the documentation.

Note that my proposition allow for the alert icon to be on the same line without additional writer action:

![image](https://user-images.githubusercontent.com/1490071/183829953-a9349521-fe51-4e6e-95eb-2c4e2a35b549.png)

**Comment by razonyang** [comment]
I see, I'll keep this open until fix this.
