### ISSUE TITLE
Indicate search is ongoing

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#658]
**Is your feature request related to a problem? Please describe.**
When changing search string in the search results page there is no indication that a new search is ongoing.

**Describe the solution you'd like**
If you change the search string there should be an indication that a new search is "running".

**Comment by razonyang** [comment]
I think it has been implemented already, there will be a loading spinner while perform searching, its existence time is related to the search speed. If the search is too fast, it may not be visible to our naked eyes.

**Comment by Natenom** [comment]
There is an icon. What I meant is, when the search was finished you can change the search string and search again. Then there is no indication.

**Comment by razonyang** [comment]
Hmm, I didn't get it, I add a delay with `2s` to show how it works, the search actually takes `75ms`, that happens too fast, so you couldn't see that loading icon.
![loading](https://user-images.githubusercontent.com/17720932/185025724-5ba68234-a287-4e0f-8470-7185ce0cc97c.gif)

**Comment by Natenom** [comment]
Trying that in Chromium it is always too fast to see the circle. But using Firefox, which is slow compared to Chromium, there is no such circle for the second search. Neither on my blog nor on your site.

**Comment by razonyang** [comment]
@Natenom Looks like a bug. I'll fix it later

**Comment by razonyang** [comment]
@Natenom the issue should be fixed now, you can preview and test it on my site before updating the theme.
