### ISSUE TITLE
Dark Mode selector disappears

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#659]
**Describe the bug**
When the value for hbs:mode is "dynamic", which is default on first visit on my [blog](https://blog.natenom.com/), the Dark mode selector is not visible. Chaning it to "dark", "light" or "auto" makes it visible.

Could that be a bug related to `color = "dynamic"` in my [params] section of the config?

(EDIT: When I comment out this line in the config it works as it should, without the need to delete local storage. Just reload.)

I tried the same in your blog and the default value there is set on first visit to "auto".

**To Reproduce**
Visit my blog. Clear Local Storage (F12), reload.
hbs:mode is set to "dynamic", Dark Mode selector not visible.

**Expected behavior**
Visible selector.

**Hugo version:**
hugo v0.101.0+extended linux/amd64 BuildDate=unknown VendorInfo=debian:0.101.0-1

**Theme version:**
c9198fab8513081c438510367726fe857836be8e (HEAD -> master, origin/master, origin/HEAD) feat(search): display the language name on search results

**Desktop (please complete the following information):**
 - Chromium and Firefox

**Comment by Natenom** [comment]
Setting color to "auto" instead of "dynamic" (as described in the documentation) seems to work.

**Comment by razonyang** [comment]
Looks like a docs bug, I'll fix it later~

**Comment by razonyang** [comment]
Fix docs and the others unsupported value will be treated as `auto`.
