### ISSUE TITLE
Sort search result

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#671]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests

### Proposal

Ability to sort search results.

For example by (asc AND desc):
- Date
- Length (words)
- 

### Motivation and context

Searching for content is sometimes easier if not sorted by "score" only.

**Comment by razonyang** [comment]
The `length` doesn't make sense.

**Comment by Natenom** [comment]
Tested :)

The entry "Sorting" could be replaced by "Default (Score)"?

**Comment by razonyang** [comment]
hmm, I guess no, we need the label indicate what the select form used for.
