### ISSUE TITLE
Read more -> jump to "more" anchor

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#693]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests

### Proposal

Currently "read more" is just a link to a blog post.

In WordPress it worked different. It was a link to a blog posts `more` anchor, which could be manually set with `<!--more-->`.

Would be nice if you could implement this into your theme.

### Motivation and context

Sometimes blog posts need more "preview" and if you click on "read more" you would not want to read the preview again.

**Comment by razonyang** [comment]
Sounds good, it's possible to implement it, but there should be a parameter that control this behavior, it's hard to name that parameter, any suggestions about naming?

**Comment by Natenom** [comment]
- post.jumpto = readmore|start

Thought about it. Nothing useful yet. :)

**Comment by razonyang** [comment]
@Natenom Thanks for the suggestion, I think `post.readMoreFromContent` may be more clear. I'll merge that PR #696 if the name is OK for you.
