### ISSUE TITLE
First lines of text appear on top(?)

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#701]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

If there is no `more` tag within a blog post, the first lines appear twice.

### Steps to reproduce

Here a screenshot:
![image](https://user-images.githubusercontent.com/385995/189646779-8b7c28bf-8c01-440c-bc4f-654d0f13c12f.png)

When I add the more tag OR checkout 13a9124dafa1765fd3e67a3ef05e40d50257b727 of your theme, it works again:
![image](https://user-images.githubusercontent.com/385995/189646926-a8255a30-56db-4a0a-927b-900a5a674e0b.png)

### Expected behavior

Not to double the first lines.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of theme are you using?

7b40de488aa48014a7b82990d82e4128f43ece69 (HEAD -> master, origin/master, origin/HEAD) feat(rss): add custom RSS template (#697)

### What version of Hugo are you using?

hugo v0.102.3+extended linux/amd64 BuildDate=2022-09-01T15:30:07Z VendorInfo=debian:0.102.3-1

### What version of Node.js are you using?

v18.7.0

### What version of Git are you using?

git version 2.35.1

### Additional context

This is the blogs source code if you want to test:

```markdown
---
title: Testing Theme
slug: testing-theme
date: 2022-09-06T00:51:23+02:00
draft: false
author: Natenom
#description:
categories:
  -
tags:
  -
---

## This is a Test
La1 la1 plum1 foo1 bar1 bla1.

La2 la2 plum2 foo2 bar2 bla2.

Without a more tag.

## Another h2
This is h2 content.

```

**Comment by razonyang** [comment]
Should be fixed by #702, btw, non-manual summaries(without `<!--more-->`) does work with `post.readMoreFromContent`.
