### ISSUE TITLE
Hide/show sidebar through a configuration option

### ISSUE THREAD

**Issue by Rubonnek** [razonyang/hugo-theme-bootstrap#708]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests

### Proposal

Currently there's no way to provide a configuration value to hide or show the whole sidebar on a first-page load. It would be nice to have that feature specifically for pages where the content does not fit properly on the screen.

### Motivation and context

See the [site parameters documentation page](https://hbs.razonyang.com/v1/en/docs/configuration/site-params/) for example.

On a 1080p monitor, the contents of that page do not properly fit the screen. However, if one were to toggle the sidebar through the sidebar toggler, the page fits rather well and looks much better with the sidebar disabled by default on that page.

Perhaps a configuration such as `sidebar.masterToggle` or `sitebar.enable` would suffice. Something like the following:
```yaml
sitebar:
  masterToggle: false # Disables sidebar on the right side of the screen
```

Also, in #336 the original intention of the archives layout was for it to not have a sidebar -- a decision I agree with and currently it doesn't seem possible to disable the sidebar through the configuration files, or by modifying the frontMatter in of `content/archives/_index.md` for example. It would also be nice to be able to disable the sidebar on other places such as the landing page.

**Comment by razonyang** [comment]
I think it's reasonable to have a parameter for disabling sidebar on landing pages. 

But the default value sidebar toggle doesn't make much sense, since the sidebar toggle should be enabled by default in large screen, and disabled by default in medium screen. It would become too complex if the toggle value depends on the screen width.

**Comment by Rubonnek** [comment]
> But the default value sidebar toggle doesn't make much sense, since the sidebar toggle should be enabled by default in large screen, and disabled by default in medium screen. It would become too complex if the toggle value depends on the screen width..

I agree. Sorry, I basically meant what you did on your recent.

Also, I didn't quite understand the page parameters until now -- I didn't quite know how to use them before. Your recent patches is what I was looking for! Thank you!
