### ISSUE TITLE
cannot disable "Archives" on sidebar

### ISSUE THREAD

**Issue by FuadEfendi** [razonyang/hugo-theme-bootstrap#713]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

Hi,

This doesn't work for params.yaml:

```
sidebar:
  archives: false
  categories: false
```

However, this worked almost as expected, except "Archives" is still shown:
```
sidebarTaxonomies:
#  - series
  - categories
#  - tags
#  - authors

```

I am trying to disable "Archives" tab... using latest theme commit, as of today.

### Steps to reproduce

This doesn't work for params.yaml:

```
sidebar:
  archives: false
  categories: false
```

However, this worked almost as expected, except "Archives" is still shown:
```
sidebarTaxonomies:
#  - series
  - categories
#  - tags
#  - authors

```

### Expected behavior

Archives is not shown on sidebar

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of theme are you using?

 caf131d758ea365c653772720152965dfeee6f9a [caf131d7]

### What version of Hugo are you using?

0.101.0

**Comment by razonyang** [comment]
I think you're going to hide this from the taxonomies toggle?

![image](https://user-images.githubusercontent.com/17720932/190428262-63f38f24-b345-4553-b355-57937cd420e4.png)

**Comment by FuadEfendi** [comment]
Yes, I tried to hide it via config change (as it was documented in exampleSite/config); but I found temporary solution: modified copy of taxonomies-toggle.html

**Comment by razonyang** [comment]
I see, there's no parameter for disabling the archives so far, those parameters you mentioned are used to hide the whole widgets from sidebar. 

We may need to add  another parameter to remove it.

**Comment by razonyang** [comment]
Hi, You're able to disable it by setting `sidebar.taxonomiesToggleArchives` as `false` with latest commit now.
