### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#735]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

Build fails with:

`
Error: Error building site: failed to render pages: render of "home" failed: "/blog/themes/hugo-theme-bootstrap/layouts/index.json:1:4": execute of template failed: template: index.json:1:4: executing "index.json" at <partial "search/index.json" .>: error calling partial: "/blog/themes/hugo-theme-bootstrap/layouts/partials/search/index.json:4:12": execute of template failed: template: partials/search/index.json:4:12: executing "partials/search/index.json" at <mul $paginate $currentPage>: error calling mul: can't apply the operator to the values

Built in 42952 ms
`

### Steps to reproduce

Build :)

### Expected behavior

Finish

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of theme are you using?

8fb6ff070f687f3bb6e6035d5e37d1add11a4a3f (HEAD -> main) (maint) theme update

### What version of Hugo are you using?

hugo v0.103.0+extended linux/amd64 BuildDate=2022-09-16T20:37:28Z VendorInfo=debian:0.103.0-1

### What version of Node.js are you using?

v18.7.0

### What version of Git are you using?

git version 2.35.1

**Comment by razonyang** [comment]
> 8fb6ff070f687f3bb6e6035d5e37d1add11a4a3f (HEAD -> main) (maint) theme update

It seems is your repo commit, not theme version, could you please check it again?

**Comment by razonyang** [comment]
I couldn't reproduce the issue with hugo `v0.103.1`, have you overridden some partials? Such as `layouts/partials/head/assets.html`, `layouts/partials/head.html`.

**Comment by Natenom** [comment]
Oh, sorry. The theme version is: 

7fd2e74f180e7ceb9fcc07592f4faac806206c41 (HEAD -> master, origin/master, origin/HEAD) perf(search): remove the *_titles from index file

These are my partials:

```partials
.
├── hooks
│   ├── footer-end.html
│   └── head-end.html
└── post
    ├── comments
    │   └── custom.html
    ├── meta.html_
    ├── related-posts.html
    └── toc.html
```

**Comment by razonyang** [comment]
Thanks for the detail. And the `JSON` is not required by theme now, you can remove the JSON safely, since the search page will generate the index file automatically.
I made a backward compatible patch for this as well for this, even the `JSON` present in the `home` outputs.

```toml
[outputs]
  home = ["HTML", "RSS"]
```
