### ISSUE TITLE
relative urls in rss

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#741]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

There are relative urls in the rss feed, but should be absolut?

https://blog.natenom.com/index.xml

```
<item>
<title>Falsch gedrehte Bilder in Hugo durch Verwendung von Funktionen zur Bildbearbeitung</title>
<link>/2022/09/falsch-gedrehte-bilder-in-hugo-durch-verwendung-von-funktionen-zur-bildbearbeitung/</link>
<pubDate>Sun, 11 Sep 2022 20:11:13 +0200</pubDate>
<guid>/2022/09/falsch-gedrehte-bilder-in-hugo-durch-verwendung-von-funktionen-zur-bildbearbeitung/</guid>

```

My website builds on the server with the same hugo extended version as on my local pc.

There the link field looks like this:

```
<link>//localhost:1313/2022/09/falsch-gedrehte-bilder-in-hugo-durch-verwendung-von-funktionen-zur-bildbearbeitung/</link>
```

### Steps to reproduce

Build.

### Expected behavior

Absolute urls.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of theme are you using?

afc9eb4de40683cb22d8d28c2a4edd166356e5de (HEAD -> master, origin/master, origin/HEAD) chore: print the fuse.js options to console

### What version of Hugo are you using?

hugo v0.103.0+extended linux/amd64 BuildDate=2022-09-16T20:37:28Z VendorInfo=debian:0.103.0-1

### What version of Node.js are you using?

v18.7.0

### What version of Git are you using?

git version 2.35.1

**Comment by razonyang** [comment]
I guess you haven't specified the `baseURL` on production.

**Comment by Natenom** [comment]
It was specified, the first line in my config and I didn't change .... oh, I did change it by accident somehow, it was 

`GbaseURL = "https://blog.natenom.com/"`

Thank you :)

I checked that today but missed the `G`.

**Comment by razonyang** [comment]
Np.
