### ISSUE TITLE
Image description (alt text) for cover image

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#743]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests

### Proposal

If twitter:image and og:image is used there should also be twitter:image:alt and og:image:alt.

It could be a new tag(?) in the front matter that is applied only if there is a cover image.

### Motivation and context

Would like to be able to support readers who are visually impaired.

The same alt text or a similiar could then be applied to the post image.

Maybe
- image-alt-text-cover
- image-alt-text-feature (defaults to image-alt-text-cover if not set)

**Comment by razonyang** [comment]
Could you please provide any docs about those meta?

**Comment by Natenom** [comment]
For Open Graph: https://ogp.me/#structured
For Twitter Cards: https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image (search for image:alt)

**Comment by razonyang** [comment]
I think it would be better to change it in Hugo. I don't intend to implement our own [OpenGraph](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/opengraph.html) and [Twitter cards](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/twitter_cards.html) templates.

Let's keep this issue open, there is a default social image need to adjust if this proposal is accepted by Hugo.

**Comment by razonyang** [comment]
Now you can specify the alternative text by the `featuredImageAlt` parameter, it'll fall back to use the page title if not set.
