### ISSUE TITLE
When building for production the page doesn't load correctly

### ISSUE THREAD

**Issue by stillie** [razonyang/hugo-theme-bootstrap#751]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

When I build my site for production, it looks like the CSS doesn't load correctly (not a web dev so if I am wrong here please forgive me)

<img width="759" alt="Screenshot 2022-10-27 at 13 06 36" src="https://user-images.githubusercontent.com/8945355/198268604-62b9274e-a6ba-473f-9cd6-9fd8900463a3.png">

### Steps to reproduce

I am building using the `hugo` command as well as the `hugo -e production` command but both seem to give the same result

### Expected behavior

For the site to look like this when I upload it to my server

<img width="1387" alt="Screenshot 2022-10-27 at 13 07 48" src="https://user-images.githubusercontent.com/8945355/198268814-e39924b3-93b8-454e-a283-dea59e2cf2df.png">

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox

### What version of theme are you using?

require github.com/razonyang/hugo-theme-bootstrap v1.0.0-alpha.11 // indirect

### What version of Hugo are you using?

hugo v0.104.3+extended darwin/amd64 BuildDate=unknown

### What version of Node.js are you using?

v18.9.0

### What version of Git are you using?

git version 2.36.1

### Additional context

This only started happening once I added a new post? When I had the one post, it was working fine but as soon as I added a second one, it seemed to break?

**Comment by stillie** [comment]
Here is the site if you are interested in seeing it yourself: https://www.stillie.co.za

**Comment by razonyang** [comment]
Hi, the problem is related to the CORS policy, you will find that it works fine on https://stillie.co.za/(without `www`), I guess your `baseURL` is `https://stillie.co.za/` in this case.

```
Access to CSS stylesheet at 'https://stillie.co.za/assets/viewer/bundle.min.6d0fc65b8b058ac563091dc5c36f61afba5dd705058680aa24f1d5a3bcf0064d.css' from origin 'https://www.stillie.co.za' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

There are multiple ways to solve it, and the simplest way is that to redirect to `stillie.co.za` from `www.stillie.co.za`(web server configuration).
