### ISSUE TITLE
White page at first load (no css loaded)

### ISSUE THREAD

**Issue by iamgiannisx** [razonyang/hugo-theme-bootstrap#760]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

When I try to to load an article a white page appears, it seems css does not load at first hit if reload the same page everything is working fine.
The same happens at version 12 

Check the video 

https://user-images.githubusercontent.com/33219224/199998369-a8f9b00a-6984-478d-99d0-25858d647d9f.mp4

### Steps to reproduce

  Try to load on clean browser.

### Expected behavior

Load properly.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of theme are you using?

13 and 12

### What version of Hugo are you using?

0.93

**Comment by razonyang** [comment]
Hi, I couldn't reproduce it, does this issue still present after clearing the cache?

Press `F12` and then.

![image](https://user-images.githubusercontent.com/17720932/200003603-c0441447-0aea-4373-8096-e7f5b08ce256.png)

**Comment by iamgiannisx** [comment]
I cleared the cache and seems it's working ok, the same issue have on Safari too.

Check the screenshot before clearing the cache.

![Screenshot 2022-11-04 at 18 41 19](https://user-images.githubusercontent.com/33219224/200030515-55cd3914-e78f-42ae-a74d-5f1d4ba90199.png)

**Comment by razonyang** [comment]
@iamgiannisx Thanks for the details, will check and reproduce the issue later.

**Comment by razonyang** [comment]
Unfortunately, I'm still unable to reproduce it. 
According to the logs, the browser loads an old page(`StaleWhileRevalidate` strategy) that requires old nonexistent assets(CSS), and the meanwhile, the old page was updated by the `StaleWhileRevalidate` strategy on first load, so that we'll see the page was rendering correctly next time.
So the #762 is a bold fix, please feel free to reopen this issue or comment under this topic if the problem persists.
