### ISSUE TITLE
Add rel="me" attribute to mastodon social hyperlink

### ISSUE THREAD

**Issue by costalfy** [razonyang/hugo-theme-bootstrap#766]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests

### Proposal

I think, with a simple if statement, we can check if it's a mastodon link and add the rel="me" attribute on these

### Motivation and context

In the social link wizard, all links have the same shape, but with mastodon we have the possibility to check the ownership of our website.
This feature has been explained here :
* https://www.zylstra.org/blog/2018/10/mastodon-rel-me/
* https://docs.joinmastodon.org/user/profile/#fields

**Comment by razonyang** [comment]
> rel="me" is used on hyperlinks from one page about a person to other pages about that same person.
Just do some research, `rel=me` seems OK for all social links.
