### ISSUE TITLE
Invisible ToC in small screens when page parameter `sidebar` is set to `false`

### ISSUE THREAD

**Issue by Rubonnek** [razonyang/hugo-theme-bootstrap#798]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

Same as title. Invisible ToC in small screens when page parameter `sidebar` is set to `false`

### Steps to reproduce

Over the [skeleton](https://github.com/razonyang/hugo-theme-bootstrap-skeleton), apply this patch:

```diff
diff --git a/content/news/more-image-processing-methods/index.md b/content/news/more-image-processing-methods/index.md
index 85342ca..948ecdf 100644
--- a/content/news/more-image-processing-methods/index.md
+++ b/content/news/more-image-processing-methods/index.md
@@ -21,10 +21,16 @@ tags:
 authors:
   - RazonYang
 images: []
+sidebar: false
 ---
 
 Since `v1.0.0-alpha.1`, HBS supports much more image processing methods. Such as Crop, Fit and Fill images. You can also apply filters on an image.
 
 <!--more-->
 
+# 1
+## 2
+### 3
+#### 4
+
```

See the ToC:

![2022-11-16-133603_956x1036_scrot](https://user-images.githubusercontent.com/8337880/202264697-7f0e0a9b-029b-4a8b-a2dd-85dd5699cba6.png)

### Expected behavior

![Screenshot 2022-11-16 at 13-37-11 More Image Processing Methods](https://user-images.githubusercontent.com/8337880/202264998-0ed5e3e1-5163-4645-a6f2-fccd3867315e.png)

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of theme are you using?

v1.0.0-alpha.15.0.20221115114142-09a902be931f // indirect

### What version of Hugo are you using?

hugo v0.105.0+extended linux/amd64 BuildDate=unknown

### What version of Node.js are you using?

16

### What version of Git are you using?

2.38

**Comment by razonyang** [comment]
Thanks for the feedback, the TOC will always be shown if the sidebar is disabled, regardless of the screen sizes.
