### ISSUE TITLE
Extending the new game shortcode for data protection compliant embedding

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#806]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests

### Proposal

Instead of only for "games" your cool new shortcode could be used for data protection compliant embedding of OpenStreetMaps, umap, videos, etc. (?)

For this there should be two new parameters:
- button_text: Instead of just "Run Game"
- preload_description: A text (markdown allowed) that could include information about what would be loaded from where if you click on $button_text.

### Motivation and context

Data protection laws in Germany/Europe (and elsewhere?) forbid to load resources from third party websites without previous consent from your website visitors.

**Comment by razonyang** [comment]
LGTM.

**Comment by Rubonnek** [comment]
@Natenom are you referring to GDPR here? I'm curious as to what laws specifically you are hinting at.

**Comment by razonyang** [comment]
@Natenom Implemented via #807, please feel free to test it [online](https://deploy-preview-807--hbs-docs.netlify.app/en/docs/shortcodes/iframe/) or locally, and submit your feedback below, I'll merge that PR later.

**Comment by Natenom** [comment]
> @Natenom are you referring to GDPR here? I'm curious as to what laws specifically you are hinting at.

Yep, GDPR or DSGVO in Germany.

**Comment by Natenom** [comment]
> @Natenom Implemented via #807, please feel free to test it [online](https://deploy-preview-807--hbs-docs.netlify.app/en/docs/shortcodes/iframe/) or locally, and submit your feedback below, I'll merge that PR later.

Thank you :) Will test it in the evening.
