### ISSUE TITLE
您好，如何关闭除中文之外其他语言

### ISSUE THREAD

**Issue by Dikea** [razonyang/hugo-theme-bootstrap#83]
您好，只想显示中文，其他语言的资源编译上传挺麻烦，想关闭该如何关闭呢

**Comment by razonyang** [comment]
假设你按照 `exampleSite` 进行配置，你需要进行以下步骤删除不需要的语言。
1. 删除 `content` 下不需要的目录，比如 `en`。
2. 修改 `config/_default/languages.toml` 配置，删除其中不需要的语言。
3. 删掉 `config` 目录下不需要的配置和菜单，比如 `menu.en.toml`。
4. 修改 `config/_default/config.toml`，将其中的 `defaultContentLanguage` 改为对应的语言。比如 `zh-cn`。如果只有一种语言，也可以将 `defaultContentLanguageInSubdir` 改为 `false`，这个只会影响语言标识（`zh-cn`）是否会显示在URL中。 
5. 最后重新生成站点，或重启 hugo 服务，看看是否生效。

PS：默认的站点是分开简繁体的，如果你只需要简体的话，也可以按照上面的步骤，删掉繁体 `zh-tw`。

**Comment by Dikea** [comment]
感谢，我试试呢，我刚刚微信向您小小的赞赏了一下，感谢您的辛勤付出，这个模板太赞了，可以加个好友交流吗，我的微信是 vip_today_go 期待能够添加您好友

**Comment by razonyang** [comment]
非常感谢支持，那我就先关闭 issue 了。
