### ISSUE TITLE
Ads loading forever at Safari

### ISSUE THREAD

**Issue by iamgiannisx** [razonyang/hugo-theme-bootstrap#840]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

Ads by google loading forever at Safari and mobile Safari at Version 1.0.0 beta

### Steps to reproduce

Load this https://hbs.razonyang.com/v1/en/ at Safari 
Open web inspector 
Check network tab 

### Expected behavior

Expecting to load normaly

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Safari

### What version of theme are you using?

v1.0.0 beta1

### What version of Hugo are you using?

109

### What version of Node.js are you using?

16

**### Merry Christmas to everyone**

**Comment by razonyang** [comment]
Could you please provide extra info about this (screenshots or videos)? I couldn't reproduce it.

![image](https://user-images.githubusercontent.com/17720932/209490862-029eaace-55ef-4efc-9214-81aeab064aae.png)

**Comment by iamgiannisx** [comment]
Check this video it's take about 6-9 second to load the page, in chrome the page load rapidly.

Download it for better resolution.


https://photos.app.goo.gl/qCfTKdyZVHz9Di4F8

**Comment by razonyang** [comment]
I see, I'm afraid that there's nothing I can do about this, since the theme just include the following code.

```html
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-xxx"></script>
```

Any resources loaded by that script are not controllable by this theme.

**Comment by iamgiannisx** [comment]
Ok, I asked cause I noticed this delay on load after I update to version 1.0.0 beta1, now seems OK so I suppose this is google adsense issue.
Thanks
