### ISSUE TITLE
github 首页 没有样式，但是其他页面有

### ISSUE THREAD

**Issue by mykaneki** [razonyang/hugo-theme-bootstrap#842]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

在本地预览页面没有问题，但是当我打包到github page时就出现问题了
具体来说就是首页没有样式，如果点开别的文章就会有，但是网址似乎是跳转出去了
比如我在github page 首页点击doc ，就会跳转到网址https://hbs-skeleton.netlify.app/docs/
![image](https://user-images.githubusercontent.com/76584735/210305220-39c6e17d-c27f-4317-8dff-4c2efe28c0ce.png)
<img width="773" alt="image" src="https://user-images.githubusercontent.com/76584735/210305235-69251b28-a03b-4b78-a1a7-383eebb9094d.png">

另外，我注意到您的github page示例网址也有相同的问题
https://razonyang.github.io/hugo-theme-bootstrap-skeleton/

### Steps to reproduce

我尝试了很多种构建方法
1. Git Submodule and Hugo Module
2. 打包public文件 and github工作流

### Expected behavior

我希望像示例网站上所看到的那样
<img width="960" alt="image" src="https://user-images.githubusercontent.com/76584735/210305646-d87401bf-f191-4c8c-9196-26e03c41a70e.png">

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of theme are you using?

v1.0.0-alpha.15

### What version of Hugo are you using?

v0.108.0

### What version of Node.js are you using?

16

### What version of Git are you using?

2.36.1.windows.1

**Comment by razonyang** [comment]
感谢反馈，这是由于之前配置了自定义域名，忘记修改相应的项目 URL 了

新地址应该为：https://projects.razonyang.com/hugo-theme-bootstrap-skeleton/

此外，你还需要从 `gh-pages.yml` 工作流中去掉（则默认使用配置的 `BaseURL`）或修改 `-b url` 为你的站点地址。

> 这是因为该模板将会被发布到各种平台，无法共用配置里的同一个 `BaseURL`.

https://github.com/razonyang/hugo-theme-bootstrap-skeleton/blob/2d5c350d923ec0e7a17ed7ec18ecd8b68f3c68e0/.github/workflows/gh-pages.yml#L42
