### ISSUE TITLE
Possible enableGitRepo issue

### ISSUE THREAD

**Issue by snesbittsea** [razonyang/hugo-theme-bootstrap#844]
There appears to be a problem with the enableGitRepo configuration parameter. 

Per the documentation, I attempted to disable the display of this widget with by setting enableGitInfo: false in the config.yaml file without success.

Instead I ending up removing it by deleting the partial/hooks/docs/sidebar-end.html file.

It seems to me that either the docs need to be updated or better, IMHO, if the enableGitInfo config parameter were implemented and the sidebar-end hook updated to check for true/false.

**Comment by razonyang** [comment]
Thanks for reporting this, just update the [deployment](https://github.com/razonyang/hugo-theme-bootstrap-skeleton#deployment) section, I think it's related to the skeleton template.
