### ISSUE TITLE
static icons in bootstrap site are overriding fvicon.png in assets

### ISSUE THREAD

**Issue by snesbittsea** [razonyang/hugo-theme-bootstrap#845]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

Based on documentation I expected that a custom favicon.png placed in assets would be the basis for site related icons such as in the web browser tab and the about panel on the main page.

In order to get this to work, I had to delete all the static/images/icons in the bootstrap site.

I'm not sure if this is a Steve issue, a precedence issue (static images taking precedence over asset images) or asset image generation not generating all the necessary icons.

Also, it would be nice if the favicon mechanism would accept both png or webp format.

### Steps to reproduce

1. Create 500x500 custom image (different from any image in static/images/icons) in assets/favicon.png
2. Start server
3. Note that custom image is not used in all places as expected. Specifically the browser tab icon and icon in main page about panel will not be the custom icon but one of the icons in static/images/icons)
4. Remove images in static/images/icons and reload server - icons are now correct.

### Expected behavior

Expected behavior was that using favicon.png as a template, all bootstrap site icons would be replaced.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of theme are you using?

ad3b22d99f95caa82a6ae0b27d162f0b3f0794f5

### What version of Hugo are you using?

hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=snap:0.110.0

### What version of Node.js are you using?

v18.7.0

### What version of Git are you using?

git version 2.37.2

**Comment by razonyang** [comment]
The main reason is that the static favicons get higher priority to get backwards compatibility.

It's reasonable to support `webp` format (not sure if it's possible) and configurable sizes, will make a PR for that.

**Comment by snesbittsea** [comment]
Thanks!



Backward compatibility makes sense and is quite understandable. A brief note in the favicon doc section regards the static images would be helpful!



-steve






---- On Thu, 19 Jan 2023 17:08:14 -0700 Razon Yang ***@***.***> wrote ---





The main reason is that the static favicons get higher priority to get backwards compatibility.

It's reasonable to support webp format (not sure if it's possible) and configurable sizes, will make a PR for that.

**Comment by razonyang** [comment]
Thanks for your feedback, the feature is live now, see the [favicon](https://hbs.razonyang.com/v1/en/docs/look-and-feel/#favicons) section.
