### ISSUE TITLE
relatedPostCount front page parameter behavior is unexpected

### ISSUE THREAD

**Issue by snesbittsea** [razonyang/hugo-theme-bootstrap#864]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

The documentation indicates that there is a relatedPostCount parameter that can be set either in Site parameters or in the front matter. For one of my pages I set this value to 0 in the expectation that it would turn off the related posts section. I was surprised when it didn't.

After poking around I think I discovered the reason. The first statement in the related-posts partial is:
`{{- $count := default .Params.relatedPostCount .Site.Params.relatedPostCount -}}`

If I read this correctly this means that the Site relatedPostCount takes precedence over the Page relatedPostCount setting. This strikes me as odd behavior given that I would expect the more specific setting - the page - would have precedence over the lessor specific setting - the site.

I can think of a couple of solutions. One would be switching the default argument list so the page parameter takes precedence. I can see this might cause issues with existing sites.

Alternatively, documentation could be updated to indicate the the Site setting has precedence and if one wants to control relatedPosts on a page  basis, the site relatedPostCount should be set to 0 and the page relatedPost set to a non zero value.

I haven't tested it, but I wonder if the recentPostCount and featuredPostCount parameters exhibit the same behavior.

### Steps to reproduce

- ensure that the relatedPostCount parameter in config is either not set or set to a non-zero value
- on a test page, set the relatedPostCount parameter to zero
- the Related Posts section for the page will be displayed

### Expected behavior

Expected behavior was that the relatedPostCount parameter setting on the Page would take precedence over the Site parameter

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of theme are you using?

ad3b22d99f95caa82a6ae0b27d162f0b3f0794f5

### What version of Hugo are you using?

hugo v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended linux/amd64 BuildDate=2023-01-17T12:16:09Z VendorInfo=snap:0.110.0

### What version of Node.js are you using?

v18.7.0

### What version of Git are you using?

git version 2.37.2

**Comment by razonyang** [comment]
Thanks for reporting this, you're right, I misused the `default` syntax on those page parameters.

Btw, you'll need to disable it by setting the corresponding parameter to `false` instead of `0`, since `0` isn't treated as a valid value by `default`, i.e. `default 100 0` got `100`.
