### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'cloneNode') at r.active

### ISSUE THREAD

**Issue by Mecanik** [razonyang/hugo-theme-bootstrap#871]
Hi,

I get this browser error for some reason in production using this skeleton:

`TypeError: Cannot read properties of null (reading 'cloneNode') at r.active (.../assets/init/bundle.min.49ca593671343b66a416b4bd8189e17a42797780b147ad52850b38b96c697fad.js:1:2588) at .../assets/init/bundle.min.49ca593671343b66a416b4bd8189e17a42797780b147ad52850b38b96c697fad.js:1:1949`

I unpacked the minified script and the culprit is here:

```
         active(t) {
                (this.mode = t),
                    s.setItem(this.key, t),
                    this.items.forEach((o) => {
                        let a = o.querySelector(".dropdown-item").classList;
                        o.getAttribute("data-color-mode") === t ? a.add("active") : a.remove("active");
                    });
                **let e = document.querySelector('.mode-item[data-color-mode="' + t + '"] .mode-icon').cloneNode(!0);**
                e.setAttribute("id", "modeIcon"), document.querySelector("#modeIcon").replaceWith(e);
           }
```

Possible to add an if case for everyone to benefit?

Thanks

**Comment by razonyang** [comment]
Fixed, you may need to upgrade the theme to the `master` branch via `hugo mod get github.com/razonyang/hugo-theme-bootstrap@master`.

Thanks for reporting this issue.

**Comment by Mecanik** [comment]
Thank you.
