### ISSUE TITLE
Incorrect heading level for Menu

### ISSUE THREAD

**Issue by Mecanik** [razonyang/hugo-theme-bootstrap#873]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

The SEO is affected because of the incorrect heading levels. Inside the menu the title is specificied with h5 tag, which causes incorrect level.

Please amend:

`<h5 class="offcanvas-title" id="navbarMenusLabel">`

To:

`<h1 class="offcanvas-title fs-5" id="navbarMenusLabel">`

Or even better, do not use H tag at all:

`<span class="offcanvas-title fs-5 fw-bold" id="navbarMenusLabel">`

Thanks

### Steps to reproduce

Analyze SEO.

### Expected behavior

This bug report is very annoying.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of theme are you using?

v1.0.0-beta2.0.20230127171944-4e82cc64584f

### What version of Hugo are you using?

v0.110.0-e32a493b7826d02763c3b79623952e625402b168+extended

### What version of Node.js are you using?

v18.12.1

### What version of Git are you using?

2.34.1

### Additional context

This bug report is time wasting and makes people not want to report anything.

**Comment by Mecanik** [comment]
Thank you.

**Comment by razonyang** [comment]
My pleasure.
