### ISSUE TITLE
Page title improving

### ISSUE THREAD

**Issue by Mecanik** [razonyang/hugo-theme-bootstrap#874]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests

### Proposal

The current page title is combined with the site title without a separator.

Example: **Page** Title **Site** Title

### Motivation and context

Please add a basic separator or a variable so users can define their pages like:

My Page | My site

**Comment by razonyang** [comment]
Umm, that's weird, there is a `titleSeparator` (default to `-`) site parameter. Could you please provide the pages without the separator?

**Comment by Mecanik** [comment]
> Umm, that's weird, there is a `titleSeparator` (default to `-`) site parameter. Could you please provide the pages without the separator?

Yes, there is, but only for the homepage. I have some partials/hooks, but I cannot see anywhere if I break it. Which file specifies the page title?

**Comment by razonyang** [comment]
> Which file specifies the page title?

The `layouts/partials/head/title.html`.

Btw, if there is a `title` block defined in your partial, then it will be used instead (higher priority).

```go
{{ define "title" }}
  My custom title
{{ end }}
```

**Comment by Mecanik** [comment]
> > Which file specifies the page title?
> 
> The `layouts/partials/head/title.html`.
> 
> Btw, if there is a `title` block defined in your partial, then it will be used instead (higher priority).
> 
> ```go
> {{ define "title" }}
>   My custom title
> {{ end }}
> ```

I do not have such file.

**Comment by razonyang** [comment]
That's a YAML syntax issue, just quote the separator will be OK, i.e. `'|'`.

> I've fixed the skeleton template as well.

**Comment by Mecanik** [comment]
Thank you.
