### ISSUE TITLE
chore: hbs.razonyang.com: correct invalid html

### ISSUE THREAD

**Issue by deining** [razonyang/hugo-theme-bootstrap#894]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

**Check of hbs example site with [W3C validation service](https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fhbs.razonyang.com%2F):**

### Steps to reproduce

One error is reported:

- Element [div](https://html.spec.whatwg.org/multipage/#the-div-element) not allowed as child of element [ul](https://html.spec.whatwg.org/multipage/#the-ul-element) in this context.

### Expected behavior

Were great if this error (and maybe also the warnings) could be fixed.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of theme are you using?

HEAD of repo

### What version of Hugo are you using?

0.110.0

### What version of Node.js are you using?

18

### What version of Git are you using?

2.39.1

**Comment by razonyang** [comment]
Thanks for reporting this.
