### ISSUE TITLE
hbs.razonyang.com: broken links

### ISSUE THREAD

**Issue by deining** [razonyang/hugo-theme-bootstrap#901]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

Several link on https://hbs.razonyang.com are broken:

![grafik](https://user-images.githubusercontent.com/18169566/218418971-c5c41364-406d-4b6b-8f6c-90f34fd49257.png)

### Steps to reproduce

Visit https://www.deadlinkchecker.com and check links for https://hbs.razonyang.com.

### Expected behavior

No broken links should be reported.

### What operating system(s) are you seeing the problem on?

Windows

### What version of theme are you using?

HEAD of repo

### What version of Hugo are you using?

0.110.0

**Comment by razonyang** [comment]
Thank you.
