### ISSUE TITLE
error calling Resize: this method is only available for image resources

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#910]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

https://github.com/razonyang/hugo-theme-bootstrap/commit/36871bbd2e1bcd95b05d460731f562608207b7ca breaks my blog with:

`Error: Error building site: EXECUTE-AS-TEMPLATE: failed to transform "search/index.json" (application/json): template: search/index.json:1:4: executing "search/index.json" at <partial "search/index.json" .>: error calling partial: "/home/blog/web/themes/hugo-theme-bootstrap/layouts/partials/search/index.json:25:27": execute of template failed: template: partials/search/index.json:25:27: executing "partials/search/index.json" at <.Resize>: error calling Resize: this method is only available for image resources`

### Steps to reproduce

I tried debug log but cannot get which blog post exactly it is.

### Expected behavior

Build.

### What operating system(s) are you seeing the problem on?

Linux

### What version of theme are you using?

current master from now

### What version of Hugo are you using?

hugo v0.110.0+extended linux/amd64 BuildDate=2023-01-27T10:03:29Z VendorInfo=debian:0.110.0-1

### What version of Node.js are you using?

v18.13.0

### What version of Git are you using?

2.39.1

**Comment by razonyang** [comment]
Is there any page's resource naming `feature*`, `cover*` or `thumbnail*`?

**Comment by razonyang** [comment]
Please upgrade to `v1.0.0-beta4.5` tag to check if the issue has been fixed, thanks for the feedback.

**Comment by Natenom** [comment]
That was fast. It is fixed, thank you :)
