### ISSUE TITLE
missing opening section in taxonomies sidebar

### ISSUE THREAD

**Issue by mgisbers** [razonyang/hugo-theme-bootstrap#923]
https://github.com/razonyang/hugo-theme-bootstrap/blob/b9a97a3b4817711b44289f76674f764ba291f84b/layouts/partials/sidebar/taxonomies.html#L15

The opening `<section ` is missing on line 15. Got removed by commit bf3805749

**Comment by razonyang** [comment]
Sorry for removing this by mistake... Thanks for your feedback.

**Comment by mgisbers** [comment]
Thanks for fixing that fast.
