### ISSUE TITLE
Navbar Options and Question About Social Links

### ISSUE THREAD

**Issue by nevikw39** [razonyang/hugo-theme-bootstrap#93]
大大您好，

首先感謝您開發的這個 hugo 主題！！這大概是我看過最完美、吻合我需求的主題了。

但是我有一些問題想要請教：

首先，是導航列上調整語言、顏色、字體大小及暗色模式的選單能否隱藏？？而能不能設定總是默認預設使用暗色主題？？

另外，有關社交連結的部分，能不能增加更多彈性，以俾自行插入 medium, last-fm 等 font awesome 支援的 icon??

感謝

**Comment by razonyang** [comment]
1. 語言選項在刪除其他語言的菜單配置和文章內容之後，應該會自動隱藏。
2. 字體、調色板還有暗色主題的選項我得驗證一下。
3. 社交連結可以添加，有其他的也可以提出來，我目前只是列了我瞭解的平臺。
大概這週末或者下週末修改下。

**Comment by razonyang** [comment]
除了默認暗色主題外，其他修改都提交至[Develop](https://github.com/razonyang/hugo-theme-bootstrap/tree/develop)分支。

1. 刪除相關語言菜單、配置和內容後，語言下拉菜單會自動隱藏。本地需要重新啓動 hugo server，才能查看最終效果。
2. 刪除或註釋 `fontSize` 參數，相應選單會隱藏。
3. 設置 `palettes` 爲空值 `[]` 可以禁用調色板，修改默認配色後，需要清除瀏覽器 Cookie 後生效。PS：這個可能後續可以優化一下。
4. 已添加相應的社交連結，對應的 key 爲 `medium` 和 `lastfm`。

如果有任何bug和問題，歡迎反饋。

**Comment by razonyang** [comment]
另外關於暗色主題的問題，目前默認隨操作系統主題色，之後可以手動切換。我想瞭解下你的確切的要求，再看看是否會有衝突。

**Comment by nevikw39** [comment]
大佬真是效率之高，著實令人折服驚嘆！！

暗色主題的部分，我是想全局設定為默認而且總是暗色這樣。

另外想要請教一下關於 Hugo 本身的一點問題：

我的文章在 Front Matter 有設定 keywords 了，但我打開源碼看 meta 裡的 keywords 都只有 tags 的內容。

還有就是文章日期旁的預估閱讀時間，跟 meta 裡的 wordCount 貌似都是基於外文以空白為單位的習慣，連帶影響到超過多少字顯示 toc 的功能。

這個 issue 我先關了，感謝！！

**Comment by razonyang** [comment]
颜色风格已修改了，更新至最新的commit即可。在参数配置中，添加 `color = "dark"` 则总是暗色风格，`light` 总是亮色风格，默认随系统/手动变换。

**Comment by razonyang** [comment]
目前主题没有处理有关 keywords 的 meta 标签，你所看到的 keywords 是由 Hugo 内置的模板`_internal/schema.html
`生成。

另外我认为 keywords meta 标签对 SEO 并没有多少作用，不过你还是可以通过 HOOK 来实现。在你项目的根目录创建文件 `layouts/partials/hooks/head-end.html`：

```html
{{- if .Params.keywords -}}
<meta name="keywords" content="{{ delimit .Params.keywords ", " }}">
{{- end -}}
```

**Comment by razonyang** [comment]
至于 wordCount 这块都是基于 Hugo 内置提供的信息，暂时没有更好的想法。

**Comment by nevikw39** [comment]
謝謝大大！！

**Comment by nevikw39** [comment]
回答一下自己：
關於 wordCount, estimated reading time 的部分，在 _config.toml_ 加入 `hasCJKLanguage = true` 都會變正常惹！！
- [Ref](https://mogeko.me/2018/033/)

**Comment by razonyang** [comment]
> 回答一下自己：
> 關於 wordCount, estimated reading time 的部分，在 _config.toml_ 加入 `hasCJKLanguage = true` 都會變正常惹！！
> 
> * [Ref](https://mogeko.me/2018/033/)

谢谢，还真不知道有这个配置。

**Comment by razonyang** [comment]
> 我的文章在 Front Matter 有設定 keywords 了，但我打開源碼看 meta 裡的 keywords 都只有 tags 的內容。

FYI，由于不少人需要这个，刚在主题实现 keywords 元标签，如果你还在使用这个主题的话，可以升级到最新的主题版本，指定相关 keywords 。🤝
