### ISSUE TITLE
Search results always empty

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#938]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

I updated to the latest version of the theme and today tried the search. It is always empty. On two different websites (~~https://natenom.de~~ (changed preload to true, see next comment) try on https://kagube.de).

### Steps to reproduce

Search for anything.-

### Expected behavior

Search result.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of theme are you using?

29cba7fd53b2b866806c1183280356d65526c6e6 (HEAD -> master, origin/master, origin/HEAD) chore(i18n): update de.toml

### What version of Hugo are you using?

hugo v0.111.3+extended linux/amd64 BuildDate=2023-03-16T08:41:31Z VendorInfo=debian:0.111.3-1

### What version of Node.js are you using?

v18.13.0

### What version of Git are you using?

2.39.2

**Comment by Natenom** [comment]
When I change `search.indexPreload` to `true` it works. Is false in my config.toml.

**Comment by razonyang** [comment]
Thanks for your feedback, I didn't noticed that, fixed since `v1.0.1`.
