### ISSUE TITLE
Top bar on search page smaller than normal

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#940]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

The top bar on search page is smaller than on other pages. Just a few pixels.

I noticed some time ago that you increased the top bar height, maybe it didn't affect the search page?

### Steps to reproduce

Compare normal page and search page :)

### Expected behavior

Same height.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of theme are you using?

7dac66a8ec19d4694bbf5b4dc720d6d0826e8d27 (HEAD -> master, origin/master, origin/HEAD) chore(ci-cd): set HUGO_BASEURL

### What version of Hugo are you using?

hugo v0.111.3+extended linux/amd64 BuildDate=2023-03-16T08:41:31Z VendorInfo=debian:0.111.3-1

### What version of Node.js are you using?

v18.13.0

### What version of Git are you using?

2.39.2

**Comment by razonyang** [comment]
Hi, it should be same on same device (same width of screen). 

![image](https://user-images.githubusercontent.com/17720932/236719374-baed0743-bf48-44cf-8263-7ab66a808be1.png)

![image](https://user-images.githubusercontent.com/17720932/236719405-24a04286-f8c4-4808-aa71-edeaadf60bbb.png)

**Comment by razonyang** [comment]
Should fixed, it was caused by the search input, since search page doesn't have search input on the top app bar.
