### ISSUE TITLE
目前reward配置在博客页面下面没有显示出来

### ISSUE THREAD

**Issue by m430** [razonyang/hugo-theme-bootstrap#944]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

```yaml
reward:
  wechat: url
  alipay: url
```
上面这个配置配好后没有生效
 

### Steps to reproduce

如上

### Expected behavior

可以再博客页面正常显示

### What operating system(s) are you seeing the problem on?

macOS

### What version of theme are you using?

v1.0.0

### What version of Hugo are you using?

v0.111.3

### What version of Node.js are you using?

18

### What version of Git are you using?

2.40.0

**Comment by razonyang** [comment]
刚试了下，并没有重现出这个问题，请问是于什么文件中设置的 `reward` 参数呢？正常需要在 `config/_default/params.yaml` 中设置，初始模板已经带有示例。

还有一种情况就是页面的 Front Matter 设置了 `reward` 为 `false` 那么该小部件也不会显示出来。

**Comment by m430** [comment]
我刚才看了一下初始模板，发现问题所在了，因为我把post的panel禁用了导致的。这个是我的锅。其实我希望赞赏的方式是可以直接在每个post的后面加一个赞赏模块，类似版权模块一样，因为点击panel的icon太隐晦了。这个我是不是只能自定义模板来实现了

**Comment by razonyang** [comment]
> 这个我是不是只能自定义模板来实现了

是的，你可以通过钩子进行自定义，举个栗子。创建 `layouts/partials/hooks/content-end.html` 并输入以下 HTML，则会于内容下方显示一个打赏按钮。

```html
<div class="text-center">
    <a
      class="action btn-reward"
      role="button"
      data-bs-toggle="modal"
      data-bs-target="#rewardModal">
      <i class="fas fa-fw fa-coffee"></i>
      {{ i18n "buy_me_a_coffee" }}
    </a>
</div>
```

也可以直接显示二维码图片。

```html
<ul class="nav nav-fill">
  <li class="nav-item">
    <img
      class="img-fluid post-reward-img"
      src="{{ .Site.Params.reward.alipay | absURL }}" />
  </li>
  <li class="nav-item">
    <img
      class="img-fluid post-reward-img"
      src="{{ .Site.Params.reward.wechat | absURL }}" />
  </li>
</ul>
```

细节你需要自行调整了，Bootstrap 有很多工具类和组件可以使用。

**Comment by m430** [comment]
@razonyang 非常感谢你的回复。我去试一下
