### ISSUE TITLE
希望可以集成访问统计插件

### ISSUE THREAD

**Issue by m430** [razonyang/hugo-theme-bootstrap#946]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests

### Proposal

希望可以集成访问统计插件：
- 文章可以展示阅读次数
- 文章底部可以展示总访问次数和人数

### Motivation and context

如上

**Comment by razonyang** [comment]
这个数据来源众多，不好集成。而这个也可以通过[钩子](https://hbs.razonyang.com/v1/zh-hans/docs/advanced/hooks/)实现。

1. `content-end` 用于显示数据的位置。
2. `body-end` 用于引入第三方 JS，可选，因为某些数据来源可以通过图片显示而无须 JS，如：

```html
{{ if .IsPage }}
JS SCRIPT
{{ end }}
```
