### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by MrHobbie** [razonyang/hugo-theme-bootstrap#948]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

I am following the installation instructions on this page:
https://hbs.razonyang.com/v1/en/docs/getting-started/installation/git-submodule/

This is the error received:

$hugo mod npm pack
WARN 2023/05/22 13:08:52 Module "hugo-theme-bootstrap" is not compatible with this Hugo version; run "hugo mod graph" for more information.
Error: add site dependencies: load resources: loading templates: "/home/mrhobbie/myblog/themes/hugo-theme-bootstrap/layouts/_default/_markup/render-image.html:1:1": parse failed: template: _default/_markup/render-image.html:1: unclosed action

$hugo version
Hugo Static Site Generator v0.80.0/extended linux/arm64 BuildDate: 2021-07-18T09:32:15Z (debian 0.80.0-6+b5)

There isn't an upgrade available.

Thanks....

John

### Steps to reproduce

see above

### Expected behavior

see above

### What operating system(s) are you seeing the problem on?

Linux

### What version of theme are you using?

unknown

### What version of Hugo are you using?

0.80.0/extended

### What version of Node.js are you using?

14.21.3

### What version of Git are you using?

2.30.2

**Comment by razonyang** [comment]
Hi, according to the logs, you're using regular Hugo version, but this theme require extended Hugo version to build SCSS, switch to extended version should work.

**Comment by razonyang** [comment]
> # runtime/cgo cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in $PATH

Some packages are missing for building Hugo from source, it's related to the OS, i.e. for Ubuntu:

```
sudo apt-get install build-essential
```

I didn't test yet, please Google it if not working.

You can download and extract Hugo from [GitHub releases](https://github.com/gohugoio/hugo/releases/tag/v0.111.3), the assets are naming with _extended_

**Comment by razonyang** [comment]
I am closing this, please feel free to comment on this topic if it's not solved.

**Comment by MozeBaltyk** [comment]
if it can help someone, on Ubuntu (Hugo deb from ubuntu repo is pretty outdated... so better install it manually) 

```sh
# Install GO
wget https://go.dev/dl/go1.21.0.linux-amd64.tar.gz
sudo tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin

# Install DART SASS 
DART_SASS_VERSION="1.66.1"
curl -LJO https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz
tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz

# Install Hugo source
HUGO_VERSION="0.117.0"
curl -LJO https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
sudo apt install -y /tmp/hugo_extended_${HUGO_VERSION}_linux-amd64.deb

hugo version                                                                                                                            
hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended linux/amd64 BuildDate=2023-08-07T12:49:48Z VendorInfo=gohugoio
```

**Comment by razonyang** [comment]
@MrHobbie Thanks for sharing this. There is also another way to install Hugo via snap on Linux platforms, take Ubuntu for example.

```sh
$ sudo snap install hugo

$ which hugo
/snap/bin/hugo

$ hugo version
hugo v0.117.0-b2f0696cad918fb61420a6aff173eb36662b406e+extended linux/amd64 BuildDate=2023-08-07T12:49:48Z VendorInfo=snap:0.117.0
```

> If the command not found, you probably forgot to add the `/snap/bin` to the `PATH` (env vars).

Upgrade hugo

```sh
$ sudo snap refresh hugo
```

Similarlly, you can install the Go and Dart SASS via snap as well.
