### ISSUE TITLE
有傻瓜安装的办法吗，

### ISSUE THREAD

**Issue by xiaoyaozz** [razonyang/hugo-theme-bootstrap#954]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests

### Proposal

对小白来说这些都是天书

### Motivation and context

有傻瓜安装方法吗，用windows + hugo 文件，来使用这个主题

**Comment by xiaoyaozz** [comment]
哇塞，大佬您的回答简直就是人类智慧的结晶啊！我这就奋勇前行去尝试一下，虽然成功率可能跟抽中彩票差不多。但是无论如何，我要再次强调感谢大佬您的细心解答，谢谢您让我感受到了人间大爱！

**Comment by xiaoyaozz** [comment]
到这一步，卡住不动了。大佬，江湖救急。
![image](https://github.com/razonyang/hugo-theme-bootstrap/assets/24558840/60931560-d765-412d-bb09-973112963e7b)

**Comment by xiaoyaozz** [comment]
> 哇塞，大佬您的回答简直就是人类智慧的结晶啊！我这就奋勇前行去尝试一下，虽然成功率可能跟抽中彩票差不多。但是无论如何，我要再次强调感谢大佬您的细心解答，谢谢您让我感受到了人间大爱！


2023年6月14日14:47:06
啊哈！终于把这个鬼畜东西搞定了，运行起来貌似也没什么大问题。可是我跟它对着干的时候，感觉自己就像个蒟蒻一样，毕竟这东西不太适合新手玩，还是要感谢大佬们的良苦用心呀！

**Comment by razonyang** [comment]
不客气，那我就先关闭这个 issue 了。
