### ISSUE TITLE
Questions About CSS Style

### ISSUE THREAD

**Issue by nevikw39** [razonyang/hugo-theme-bootstrap#97]
您好，
關於 CSS 的部分，我有一些問題跟建議。
首先是 `<blockquote>` 的部分，**display** 是 _flex_ 導致如果有多個段落的話會變成類似 multi column 的感覺，不曉得這是有什麼特別的涵義嗎？？
還有用 markdown 畫水平線的 `<hr>`，**border** 0 加上 **opacity** .25 實在不甚明顯。
再麻煩惹
感謝

**Comment by razonyang** [comment]
`blockquote` 确实有问题，以前没注意到，我晚上再改一下。
至于 `hr` 标签，我再调整一下。

**Comment by nevikw39** [comment]
另外想請問一下， `params` 的 **image** 功能為何？？
我看 `og:image` 似乎沒有起作用耶

**Comment by razonyang** [comment]
`blockquote` 已修改了。
至于 `hr` 样式是 Bootstrap 默认的，感觉这个比较难统一，我比较偏向维持原样。或者可以提供一些样式建议。
另外也可以通过[自定义 CSS](https://github.com/razonyang/hugo-theme-bootstrap/blob/master/README.zh-TW.md#自定義資源) 以达到该目的。

**Comment by nevikw39** [comment]
'<hr>' 的部分好像是我自己瀏覽器設定的問題
Issue 我先關了

**Comment by nevikw39** [comment]
我現在遇到的狀況是如果在 Front Matter 設置 **image** 那麼就會正確呈現 _og:image_
但全域的 `params.toml` 的 **image** 就不會顯示
我是希望首頁之類非 posts 的文章也能有預覽

**Comment by razonyang** [comment]
看了下 hugo 内置模板的源码，其只会从 Front matter 读取图片信息，所以在 params 中配置是不起作用的。
不过通过其他方式配置 Front matter，比如说首页，可以在内容根目录创建 `_index.md`，并填写相关 images 即可。

**Comment by nevikw39** [comment]
了解了 感謝

**Comment by nevikw39** [comment]
關於 `og:image` 的部分，我參考了[官方文檔](https://github.com/razonyang/hugo-theme-bootstrap/blob/master/exampleSite/config/_default/params.toml)。

原來是 Example Site [params.toml](https://github.com/razonyang/hugo-theme-bootstrap/blob/master/exampleSite/config/_default/params.toml) 第六行被註解掉的 `image` 少了 **s**。

加上後如果葉面沒有指定 `images` 就會從 **params** 讀取。

**Comment by razonyang** [comment]
感谢提醒，确实如此，我修改一下默认配置。
