### ISSUE TITLE
安装出现问题，帮帮我

### ISSUE THREAD

**Issue by reatiny** [razonyang/hugo-theme-bootstrap#99]
1、cp -a themes/hugo-clarity/exampleSite/* . 这个在windows命令行下应该咋写呢。
2、复制后localhost显示不完整

**Comment by razonyang** [comment]
你好, 这个命令复制的是 `hugo-clarity` 主题，而不是本主题的内容和配置，你应该复制错了。
另外在 Windows 没有 `cp`，不过可以使用 `xcopy`

```shell
xcopy .\themes\hugo-theme-bootstrap\exampleSite  /E
```

相关文档：https://docs.microsoft.com/zh-cn/windows-server/administration/windows-commands/xcopy

**Comment by reatiny** [comment]
万分感谢，修改toml文件后hugo server容易出现Error: "D:\reatiny\hugo\sites\myblog\config\_default\languages.toml:1:1": unmarshal failed: Near line 0 (last key parsed ''): bare keys cannot contain '\ufeff'。
这是为啥呢

**Comment by razonyang** [comment]
应该是格式不对，你仔细检查一下，也可以贴内容上来。

**Comment by reatiny** [comment]
[zh-cn]
  languageName = "简体中文"
  weight = 4
  contentDir = "content/zh-cn"


就是这样子，没发现有什么多余的空格。
看这个链接说是多了Nul 
https://blog.csdn.net/xiao_feng007/article/details/106366218
我还是不知道哪里出了问题。。

**Comment by razonyang** [comment]
> [zh-cn]
> languageName = "简体中文"
> weight = 4
> contentDir = "content/zh-cn"
> 
> 就是这样子，没发现有什么多余的空格。
> 看这个链接说是多了Nul
> https://blog.csdn.net/xiao_feng007/article/details/106366218
> 我还是不知道哪里出了问题。。

我在 Windows 试了下，配置没有问题，感觉像是 BOM（gohugoio/hugo#1262），你查一下你编辑器如何去除 BOM `Encode as UTF-8 (without BOM)`

**Comment by reatiny** [comment]
好的哥
