### ISSUE TITLE
Google Analytics async will be removed from hugo in the future

### ISSUE THREAD

**Issue by Natenom** [razonyang/hugo-theme-bootstrap#990]
### Prerequisites

- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [searched](https://github.com/razonyang/hugo-theme-bootstrap/discussions) for relatived questions
- [X] I have read [documentations](https://hbs.razonyang.com)

### Describe the issue

```WARN  _internal/google_analytics_async.html is no longer supported by Google and will be removed in a future version of Hugo```

### Steps to reproduce

Build

### Expected behavior

No warning

### What operating system(s) are you seeing the problem on?

Linux

### What version of theme are you using?

581f060e26d8bef704d48a3d84bcd7d1da1b4e28 (HEAD -> master, origin/master, origin/HEAD) style: tweak search bar (#988)

### What version of Hugo are you using?

hugo v0.119.0+extended linux/amd64 BuildDate=2023-10-15T23:06:00Z VendorInfo=debian:0.119.0-2

### What version of Node.js are you using?

v18.13.0

### What version of Git are you using?

git version 2.42.0

**Comment by razonyang** [comment]
Thanks for pointing it out, drafte a new release for this.
